// This Pine Script™ code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © drebel

//@version=6
indicator(title = 'DRE Event Gap Up and Up', shorttitle = 'EGUAU', overlay = true, timeframe = '1D')

iDo1stCandle = input.bool(defval = true, title = 'Check 1st candle Marubozu')
iLowTfFirstCandleVolumeMultiple = input.int(defval = 10, title = 'Low Timeframe 1st Candle Volume Miltiple', minval = 1, step = 1)
iDoLaterHighBo = input.bool(defval = true, title = 'High Bo') // not ready
iLowerTimeframe = input.timeframe(defval = '5', title = 'Lower Timeframe', options=['3', '5', '10', '15', '30', '45', '60'])

// filters
iCalcLength = input.int(defval = 50, title = 'Calc. parameters length', minval = 5, group = 'Common signal filters')
iMinTurnover = input.float(defval = 0.5, title = 'Min. Turnover for signal ($M)', minval = 0, step = 0.1, group = 'Common signal filters')
iMinAdr = input.float(defval = 4.0, title = 'Min. ADR% for signal', minval = 0, step = 0.2, group = 'Common signal filters')

// filters
gTurnoverMa = ta.sma(close * volume, iCalcLength)
gTurnoverCond = gTurnoverMa > iMinTurnover * 1000000
gAdr = 100 * (ta.sma(high / low, iCalcLength) - 1)
gAdrCond = gAdr > iMinAdr
gFilter = gTurnoverCond and gAdrCond

// earnings
// earnings = request.earnings(ticker = syminfo.tickerid, field = earnings.actual)
// earningsDay = earnings != earnings[1]
// gEarningsCond = earningsDay or earningsDay[1]

// calculations
gAtr = ta.atr(iCalcLength)

[lowTfOpen, lowTfHigh, lowTfLow, lowTfClose, lowTfVolume] = request.security_lower_tf(symbol = syminfo.tickerid, timeframe = iLowerTimeframe, expression = [open, high, low, close, volume])
firstLowTfOpen = array.size(lowTfOpen) == 2 ? array.get(lowTfOpen, 0) : na   //check if array.size > 1 because we need a closed 1st candle
firstLowTfHigh = array.size(lowTfHigh) == 2 ? array.get(lowTfHigh, 0) : na
firstLowTfLow = array.size(lowTfLow) == 2 ? array.get(lowTfLow, 0) : na
firstLowTfClose = array.size(lowTfClose) == 2 ? array.get(lowTfClose, 0) : na
firstLowTfVolume = array.size(lowTfVolume) == 2 ? array.get(lowTfVolume, 0) : na
secondLowTfOpen = array.size(lowTfOpen) == 3 ? array.get(lowTfOpen, 1) : na   //check if array.size > 2 because we need a closed 2nd candle
secondLowTfHigh = array.size(lowTfHigh) == 3 ? array.get(lowTfHigh, 1) : na
secondLowTfLow = array.size(lowTfLow) == 3 ? array.get(lowTfLow, 1) : na
secondLowTfClose = array.size(lowTfClose) == 3 ? array.get(lowTfClose, 1) : na
secondLowTfVolume = array.size(lowTfVolume) == 3 ? array.get(lowTfVolume, 1) : na

nthLowTfLowest = array.size(lowTfOpen) > 10 ? array.min(lowTfLow) : na
nthLowTfHighest = array.size(lowTfOpen) > 10 ? array.max(lowTfHigh) : na
nthLowTfClose = array.size(lowTfOpen) > 10 ? array.last(lowTfClose) : na
initLowTfHighest = math.max(firstLowTfHigh, secondLowTfHigh)
lowTfLowHighDist = initLowTfHighest - nthLowTfLowest
lowTfBoCond = lowTfLowHighDist > gAtr / 3 and nthLowTfClose >= nthLowTfHighest and volume > volume[1]

firstCandleLowTfVolumeMa = ta.sma(firstLowTfVolume, iCalcLength)

isMarubozu(_open, _high, _low, _close, _fill) =>
    _close > _open and (_close - _open) / (_high - _low) > _fill

marubozuLowTf1stCande = isMarubozu(firstLowTfOpen, firstLowTfHigh, firstLowTfLow, firstLowTfClose, 0.85)
marubozuLowTf2Candle = isMarubozu(firstLowTfOpen, math.max(firstLowTfHigh, secondLowTfHigh), math.min(firstLowTfLow, secondLowTfLow), secondLowTfClose, 0.85)
volume1stCandleCond = firstLowTfVolume > iLowTfFirstCandleVolumeMultiple * firstCandleLowTfVolumeMa
gapCond = open > high[1]

generalConditions = gFilter and gapCond
firstCandleCond = iDo1stCandle and (marubozuLowTf1stCande or marubozuLowTf2Candle) and volume1stCandleCond
laterHighBoCond = iDoLaterHighBo and lowTfBoCond

eguauSig = generalConditions and (firstCandleCond or laterHighBoCond)

alertcondition(eguauSig, title = 'DRE eguau sig', message = 'eGUAU')
plotshape(eguauSig, title = 'Event Gap Up And Up', location = location.belowbar, color = color.new(color.green, 0), style = shape.triangleup, text = 'eGUAU', textcolor = color.new(color.green, 0))
