// This Pine Script™ code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © drebel

//@version=6
indicator(title = 'DRE parabolic top', overlay = true, max_bars_back = 2200, calc_bars_count = 12 * 252)

import drebel/DRELib/39 as drelib
import drebel/DREPerf/24 as dreperf

//general filters inputs
iTurnoverCond = input.bool(defval = true, title = 'Min. Turnover for signal [M]', display = display.none, group = 'General filter for signal', inline = 'trn')
iMinTurnover = input.float(defval = 0.15, title = '', minval = 0, display = display.none, group = 'General filter for signal', inline = 'trn')
iAdrCond = input.bool(defval = true, title = 'Min. ADR% for signal', display = display.none, group = 'General filter for signal', inline = 'adr')
iMinAdr = input.float(defval = 2.6, title = '', minval = 0, step = 0.2, display = display.none, group = 'General filter for signal', inline = 'adr')

//signals switches
iParabolicTop = input.bool(defval = false, title = 'Show parabolic top', display = display.none, group = 'Signals')
iJunior = input.bool(defval = false, title = 'Show junior', display = display.none, group = 'Signals', inline = 'junior')
iJunior2 = input.bool(defval = false, title = '2', display = display.none, group = 'Signals', inline = 'junior')
iJunior3 = input.bool(defval = false, title = 'late', display = display.none, group = 'Signals', inline = 'junior')
iCoil = input.bool(defval = false, title = 'Show coil', display = display.none, group = 'Signals', inline = 'coil')
iCoilStrech = input.bool(defval = false, title = 'strech', display = display.none, group = 'Signals', inline = 'coil')
iBullishStarter = input.bool(defval = false, title = 'Show starter', display = display.none, group = 'Signals', inline = 'starter')
iBearishStarter = input.bool(defval = false, title = 'bear', display = display.none, group = 'Signals', inline = 'starter')
iBullishFireStarter = input.bool(defval = false, title = 'fire', display = display.none, group = 'Signals', inline = 'starter')
iLonger = input.bool(defval = false, title = 'Show longer', display = display.none, group = 'Signals')
iBullishZscore = input.bool(defval = false, title = 'Show bubble', display = display.none, group = 'Signals', inline = 'bubble')
iBearishZscore = input.bool(defval = false, title = 'bear', display = display.none, group = 'Signals', inline = 'bubble')
iBullishHunter = input.bool(defval = false, title = 'Show hunter', display = display.none, group = 'Signals', inline = 'hunter')
iBearishHunter = input.bool(defval = false, title = 'bear', display = display.none, group = 'Signals', inline = 'hunter')
iBullishStepper = input.bool(defval = false, title = 'Show stepper', display = display.none, group = 'Signals', inline = 'stepper')
iBullishLongerStepper = input.bool(defval = false, title = 'longer', display = display.none, group = 'Signals', inline = 'stepper')
iBullishObv = input.bool(defval = false, title = 'Show obv', display = display.none, group = 'Signals', inline = 'obv')
iBearishObv = input.bool(defval = false, title = 'bear', display = display.none, group = 'Signals', inline = 'obv')
iBullishRmv = input.bool(defval = false, title = 'Show rmv', display = display.none, group = 'Signals', inline = 'rmv')
iBearishRmv = input.bool(defval = false, title = 'bear', display = display.none, group = 'Signals', inline = 'rmv')
iBullishRmvPb = input.bool(defval = false, title = 'bull pb', display = display.none, group = 'Signals', inline = 'rmvpb')
iBearishRmvPb = input.bool(defval = false, title = 'bear pb', display = display.none, group = 'Signals', inline = 'rmvpb')
iBullishMtb = input.bool(defval = false, title = 'Show mtb', display = display.none, group = 'Signals')
iTurnaroundGo = input.bool(defval = false, title = "Show O'Neail big index turnaround GO", display = display.none, group = 'Signals')
iFStarterGoSmaCrossover = input.bool(defval = false, title = 'Show F.starter - GO - sma200crossover', display = display.none, group = 'Signals')

iSigCheckTime = input.int(defval = 30, title = 'Signal check time [candles]', minval = 5, maxval = 200, display = display.none, group = 'Signals')
iMinSigSuccessRate = input.float(defval = 41.0, title = 'Min. sig success rate pct.', minval = 0.0, maxval = 100.0, step = 1.0, display = display.none, group = 'Signals')
iMinSigReturnAdrMultiple = input.float(defval = 0.9, title = 'Min. avg. return by ADR multiple', minval = -1.0, maxval = 5.0, step = 0.05, display = display.none, group = 'Signals')

//common parameters
iMainMaLength = input.int(defval = 200, title = 'Main MA length', minval = 50, maxval = 500, display = display.none, group = 'Common parameters')
iShortMaLength = input.int(defval = 50, title = 'Short MA length', minval = 10, maxval = 200, display = display.none, group = 'Common parameters')
iLongMaLength = input.int(defval = 750, title = 'Long MA length', minval = 200, maxval = 1000, display = display.none, group = 'Common parameters')
iVShortMaLength1 = input.int(defval = 10, title = 'Very short MA length', minval = 5, maxval = 50, display = display.none, group = 'Common parameters')
iVShortMaLength2 = input.int(defval = 21, title = 'Very short MA length2', minval = 8, maxval = 50, display = display.none, group = 'Common parameters')

//common calculations
mainAtr = ta.atr(iMainMaLength)
mainMa = ta.sma(close, iMainMaLength)
shortMa = ta.sma(close, iShortMaLength)
longMa = ta.sma(close, iLongMaLength)
gVShortMa1 = ta.ema(close, iVShortMaLength1)
gVShortMa2 = ta.ema(close, iVShortMaLength2)
gVolMa = ta.sma(volume, 30)
adrPct = 100.0 * (ta.sma(high / low, 30) - 1)

//filters calculations (min. iShortMaLength candles)
gTurnoverMa = ta.sma(close * volume, iShortMaLength) / 1000000.0
gTurnoverMedian = ta.median(close * volume, iShortMaLength) / 1000000.0
gTurnoverCond = not iTurnoverCond or iTurnoverCond and gTurnoverMa > iMinTurnover and gTurnoverMedian > iMinTurnover
gAdr = 100 * (ta.sma(high / low, iShortMaLength) - 1)
gAdrCond = not iAdrCond or iAdrCond and gAdr > iMinAdr
gFilter = gTurnoverCond and gAdrCond

//Signal: Parabolic top
iParTopAtrMulti = input.int(defval = 8, title = 'ATR Multiple Since Low', minval = 2, maxval = 30, display = display.none, group = 'Signal: Parabolic top')
iParTopGainDays = input.int(defval = 100, title = 'Number Of Days To top', minval = 5, maxval = 150, step = 5, display = display.none, group = 'Signal: Parabolic top')
iDownDays1 = input.bool(defval = true, title = 'Down Days After Top 1', display = display.none, group = 'Signal: Parabolic top', inline = 'top1')
iDownDaysAfterTop1 = input.int(defval = 2, title = '', minval = 1, maxval = 8, display = display.none, group = 'Signal: Parabolic top', inline = 'top1')
iDownDays2 = input.bool(defval = true, title = 'Down Days After Top 2', display = display.none, group = 'Signal: Parabolic top', inline = 'top2')
iDownDaysAfterTop2 = input.int(defval = 3, title = '', minval = 1, maxval = 8, display = display.none, group = 'Signal: Parabolic top', inline = 'top2')
iDownDays3 = input.bool(defval = true, title = 'Down Days After Top 3', display = display.none, group = 'Signal: Parabolic top', inline = 'top3')
iDownDaysAfterTop3 = input.int(defval = 4, title = '', minval = 1, maxval = 8, display = display.none, group = 'Signal: Parabolic top', inline = 'top3')

top1Sig = drelib.sigParabolicTop(gVolMa, iDownDaysAfterTop1, iParTopGainDays, iParTopAtrMulti, mainAtr) and iDownDays1
top2Sig = drelib.sigParabolicTop(gVolMa, iDownDaysAfterTop2, iParTopGainDays, iParTopAtrMulti, mainAtr) and iDownDays2
top3Sig = drelib.sigParabolicTop(gVolMa, iDownDaysAfterTop3, iParTopGainDays, iParTopAtrMulti, mainAtr) and iDownDays3
topSig = top1Sig or top2Sig or top3Sig

//Signal: Junior
func_init_vwap_excl_init_higher_volume() =>
    x = 0.5
    reset = bar_index == 0 or bar_index == 1 and volume < x * volume[1] or bar_index == 2 and volume < x * volume[1] and volume[1] < x * volume[2]
    ret = ta.vwap(ohlc4, reset)
    ret

func_sig_junior_late(_minAge) =>
    initVwap = func_init_vwap_excl_init_higher_volume()
    ret = bar_index >= _minAge and drelib.crossover(initVwap)
    ret

juniorSig = drelib.sigJunior(iLongMaLength)
juniorLateSig = func_sig_junior_late(iLongMaLength)

freshStock = bar_index < iLongMaLength
bars = int(math.min(bar_index > 1 ? bar_index * 0.8 : 1, iLongMaLength))
initialHigh = ta.highest(bars)
isHighestSinceIpo = high == initialHigh
initialHighBarsAgo = ta.barssince(isHighestSinceIpo)
initHighVwap = ta.vwap(ohlc4, freshStock and isHighestSinceIpo)
bars2 = bar_index > 15 ? bar_index - 7 : bar_index * 0.2
junior2Sig = initialHighBarsAgo > bars2 and drelib.candle_crossover(initHighVwap)

// junior3Sig = freshStock and initialHighBarsAgo > bars2 and drelib.candle_crossover(initialHigh[1])
// alertcondition(junior3Sig, title = 'DRE junior3 sig', message = 'junior3')
// plotshape(junior3Sig and iJunior3, title = 'junior3', location = location.belowbar, color = color.new(color.green, 0), style = shape.triangleup, text = 'junior3', textcolor = color.new(color.green, 0))

//Signal: Coil_n_strech
iCoilPercent = input.int(defval = 2, title = 'Percentile rank distance from MAs', minval = 1, maxval = 20, display = display.none, group = 'Signal: Coil_n_strech')

func_ma_distance(_shortMaLen, _mediumMaLen, _longMaLen) =>
    ma1 = ta.sma(close, _shortMaLen)
    ma2 = ta.sma(close, _mediumMaLen)
    ma3 = ta.sma(close, _longMaLen)
    zeroBarVwap = ta.vwap(ohlc4, bar_index == 0)
    usedLongMaLen = bar_index < _longMaLen ? bar_index : _longMaLen
    ma3used = bar_index < _longMaLen ? zeroBarVwap : ma3
    lenSum = _shortMaLen + _mediumMaLen + usedLongMaLen
    distance = math.sqrt((lenSum - _shortMaLen) * math.pow(ma1 - close, 2) + (lenSum - _mediumMaLen) * math.pow(ma2 - close, 2) + (lenSum - usedLongMaLen) * math.pow(ma3used - close, 2))
    distance

func_sig_coil(_dist, _longMaLen, _mediumMaLen, _distPercentRank) =>
    percentRankLen = bar_index < 1 ? 1 : math.min(bar_index, 3 * _longMaLen)
    mediumMa = ta.sma(close, _mediumMaLen)
    ret = ta.percentrank(_dist, percentRankLen) < _distPercentRank and drelib.crossover(mediumMa)
    ret

func_sig_strech(_dist, _longMaLen, _distPercentRank) =>
    percentRankLen = bar_index < 1 ? 1 : math.min(bar_index, 3 * _longMaLen)
    ret = ta.percentrank(_dist, percentRankLen) > 100 - _distPercentRank and close > close[_longMaLen] and close > close[1]
    ret

coilBullishSig = func_sig_coil(func_ma_distance(iShortMaLength, iMainMaLength, iLongMaLength), iLongMaLength, iMainMaLength, iCoilPercent)
strechBearishSig = func_sig_strech(func_ma_distance(iShortMaLength, iMainMaLength, iLongMaLength), iLongMaLength, iCoilPercent)

//Signal: Starter
iStarterMinDecliningDays = input.int(defval = 200, title = 'Number of SMA declining days', minval = 20, maxval = 1000, display = display.none, group = 'Signal: Starter')
iStarterMaxIncliningDays = input.int(defval = 200, title = 'Number of SMA inclining day', minval = 0, maxval = 300, display = display.none, group = 'Signal: Starter')
iStarterSmaSmoothing = input.int(defval = 3, title = 'SMA smoothing', minval = 0, maxval = 10, display = display.none, group = 'Signal: Starter')
iFireStarterMaDiffAtrMultiple = input.float(defval = 1, title = 'Fire starter MA difference ATR multiple', minval = 0.5, maxval = 10, step = 0.5, display = display.none, group = 'Signal: Starter')

bullishStarterSig = drelib.sigStarter(true, iMainMaLength, iStarterMinDecliningDays, iStarterMaxIncliningDays, iStarterSmaSmoothing)
bearishStarterSig = drelib.sigStarter(false, iMainMaLength, iStarterMinDecliningDays, iStarterMaxIncliningDays, iStarterSmaSmoothing)
bullishFireStarterSig = drelib.sigFireStarter(iMainMaLength, iStarterMinDecliningDays, iFireStarterMaDiffAtrMultiple, iStarterSmaSmoothing, mainAtr)

//Signal: Longer
iLongerOffset = input.float(defval = 0.1, title = 'Price offset (atr multiple)', minval = -2.0, maxval = 2.0, step = 0.5, display = display.none, group = 'Signal: Longer')

longerSig = drelib.sigLonger(mainMa, longMa, 0, mainAtr)
smallerLongerSig = drelib.sigLonger(shortMa, mainMa, 0, mainAtr)

//Signal: Bubble
iZScore2ndMaLength = input.int(21, 'Z-Score 2nd MA Length (short)', minval = 3, maxval = 21, display = display.none, group = 'Signal: Bubble')
iZScore2ndMaMinScore = input.float(2.3, 'Min. zScore', minval = 1.0, maxval = 14, step = 0.1, display = display.none, group = 'Signal: Bubble')

zscoreVolCond = ta.ema(drelib.z_score(volume, iMainMaLength), iZScore2ndMaLength) >= iZScore2ndMaMinScore
zscoreEma = ta.ema(close, 2 * iZScore2ndMaLength / 3)
zscoreBullishSig = zscoreVolCond and zscoreEma > zscoreEma[1]
zscoreBearishSig = zscoreVolCond and zscoreEma < zscoreEma[1]

//Signal: Hunter
iHunterGracePeriod = input.int(defval = 40, title = 'grace period', minval = 20, maxval = 200, display = display.none, group = 'Signal: Hunter')
iHunterShort = input.bool(defval = true, title = 'short', display = display.none, group = 'Signal: Hunter', inline = 'hunter2')
iHunterLookbackShort = input.int(defval = 250, title = 'lookback', minval = 50, maxval = 1000, display = display.none, group = 'Signal: Hunter', inline = 'hunter2')
iHunterMid = input.bool(defval = true, title = 'mid', display = display.none, group = 'Signal: Hunter', inline = 'hunter3')
iHunterLookbackMid = input.int(defval = 700, title = 'lookback', minval = 100, maxval = 1500, display = display.none, group = 'Signal: Hunter', inline = 'hunter3')
iHunterLong = input.bool(defval = true, title = 'long', display = display.none, group = 'Signal: Hunter', inline = 'hunter4')
iHunterLookbackLong = input.int(defval = 1300, title = 'lookback', minval = 200, maxval = 2000, display = display.none, group = 'Signal: Hunter', inline = 'hunter4')

bullishHunterShortSig = drelib.sigBullSLHunter(mainAtr, iHunterLookbackShort, iHunterGracePeriod) and iHunterShort
bullishHunterMidSig = drelib.sigBullSLHunter(mainAtr, iHunterLookbackMid, iHunterGracePeriod) and iHunterMid
bullishHunterLongSig = drelib.sigBullSLHunter(mainAtr, iHunterLookbackLong, iHunterGracePeriod) and iHunterLong
bullishHunterSig = bullishHunterShortSig or bullishHunterMidSig or bullishHunterLongSig

bearishHunterShortSig = drelib.sigBearSLHunter(mainAtr, iHunterLookbackShort, iHunterGracePeriod) and iHunterShort 
bearishHunterMidSig = drelib.sigBearSLHunter(mainAtr, iHunterLookbackMid, iHunterGracePeriod) and iHunterMid
bearishHunterLongSig = drelib.sigBearSLHunter(mainAtr, iHunterLookbackLong, iHunterGracePeriod) and iHunterLong
bearishHunterSig = bearishHunterShortSig or bearishHunterMidSig or bearishHunterLongSig

//Signal: Stepper
iStepperLookback = input.int(defval = 325, title = 'lookback', minval = 100, maxval = 750, step = 5, display = display.none, group = 'Signal: Stepper')
iStepperMaDist = input.float(defval = 1.25, title = 'max vwap-ma dist.', minval = 0.0, maxval = 5.0, step = 0.25, display = display.none, group = 'Signal: Stepper')
iLongerStepperDist = input.int(defval = 5, title = 'longer-stepper max. distance', minval = 0, maxval = 20, display = display.none, group = 'Signal: Stepper')

bullishStepperSig = drelib.sigBullStepper(mainAtr, mainMa, iStepperLookback, iStepperMaDist)
bullishLongerStepperSig = ta.barssince(longerSig) <= iLongerStepperDist and bullishStepperSig
bullishSLongerStepperSig = ta.barssince(smallerLongerSig) <= 3 and bullishStepperSig

//Signal: Obv
iObvMaLength = input.int(defval=100, title='Ma len.', minval=10, maxval=250, display = display.none, group='Signal: Obv')
iObvSource = input.source(close, title = 'Source', display = display.none, group = 'Signal: Obv')
iObvStdDevBand = input.float(defval = 0.35, title = 'StdDev.', minval = 0, maxval = 10.0, step = 0.05, display = display.none, group = 'Signal: Obv')

func_obv(_source) =>
    ta.cum(math.sign(ta.change(_source)) * volume)

var cumVol = 0.
cumVol += nz(volume)
if barstate.islast and cumVol == 0
    runtime.error("No volume is provided by the data vendor.")

obv = func_obv(iObvSource)
obcMa = ta.sma(obv, iObvMaLength)
obvStdDev = ta.stdev(obv, iObvMaLength)
bullishObvCross = drelib.crossover2(obv, obcMa + iObvStdDevBand * obvStdDev)
bearishObvCross = drelib.crossunder2(obv, obcMa - iObvStdDevBand * obvStdDev)
bullishObvCrossSince = ta.barssince(bullishObvCross)
bearishObvCrossSince = ta.barssince(bearishObvCross)
bullishObvSig = bullishObvCross and bullishObvCrossSince[1] > bearishObvCrossSince[1]
bearishObvSig = bearishObvCross and bullishObvCrossSince[1] < bearishObvCrossSince[1]

//Signal: Rmv
iRmvLookbackPeriod = input.int(30, minval = 1, title = 'Lookback Period', display = display.none, group = 'Signal: Rmv')
iRmvShortLookback1 = input.int(13, minval = 1, title = 'Short-term ATR Lookback 1', display = display.none, group = 'Signal: Rmv')
iRmvShortLookback2 = input.int(8, minval = 1, title = 'Short-term ATR Lookback 2', display = display.none, group = 'Signal: Rmv')
iRmvshortLookback3 = input.int(5, minval = 1, title = 'Short-term ATR Lookback 3', display = display.none, group = 'Signal: Rmv')
iRmvLowLevel = input.int(25, title = 'Low Level Threshold', display = display.none, group = 'Signal: Rmv')
iRmvPbLen = input.int(11, title = 'Pullback Len.', display = display.none, group = 'Signal: Rmv')

func_rmv(_artShortLen1, _artShortLen2, _artShortLen3, _MainLookback) =>
    shortAtrAvg = (ta.atr(_artShortLen1) + ta.atr(_artShortLen2) + ta.atr(_artShortLen3)) / 3
    highestShortAvg = ta.highest(shortAtrAvg, _MainLookback)
    lowestShortAvg = ta.lowest(shortAtrAvg, _MainLookback)
    result = (shortAtrAvg - lowestShortAvg) / math.max(highestShortAvg - lowestShortAvg, 0.001) * 100
    result

rmv = func_rmv(iRmvShortLookback1, iRmvShortLookback2, iRmvshortLookback3, iRmvLookbackPeriod)
lowRmv = rmv <= iRmvLowLevel
highRmv = rmv >= 100 - iRmvLowLevel / 2
earnings = request.earnings(ticker = syminfo.tickerid, field = earnings.actual)
earningsSig = earnings != earnings[1]

rmvCond = lowRmv[1] and not lowRmv or highRmv and lowRmv[2] or rmv == 100 and lowRmv[3]
bullishRmvSig = rmvCond and close > close[2] and volume > gVolMa and close > gVShortMa1 and close > gVShortMa2 and close > shortMa
bullishRmvPbAgo = ta.barssince(bullishRmvSig)
bullishRmvPbSig = not bullishRmvSig and bullishRmvPbAgo <= iRmvPbLen and drelib.crossover(low[bullishRmvPbAgo])
bearishRmvSig = rmvCond and close < close[2] and volume > gVolMa and close < gVShortMa1 and close < gVShortMa2 and close < shortMa
bearishRmvPbAgo = ta.barssince(bearishRmvSig)
bearishRmvPbSig = not bearishRmvSig and bearishRmvPbAgo <= iRmvPbLen and drelib.crossunder(high[bearishRmvPbAgo])

//plotshape(bullishRmvSig and iBullishRmv, title = 'bullish rmv', location = location.belowbar, color = color.new(color.green, 0), style = shape.triangleup, text = 'rmv', textcolor = color.new(color.green, 0))
//plotshape(bullishRmvPbSig and iBullishRmvPb, title = 'bullish rmv-pb', location = location.belowbar, color = color.new(color.green, 0), style = shape.triangleup, text = 'rmv-pb', textcolor = color.new(color.green, 0))
//plotshape(bullishRmvEarningsSig and iBullishRmvEarnings, title = 'bullish rmv-e', location = location.belowbar, color = color.new(color.green, 0), style = shape.triangleup, text = 'rmv-e', textcolor = color.new(color.green, 0))
//plotshape(bullishRmvEarningsPbSig and iBullishRmvEarningsPb, title = 'bullish rmv-e-pb', location = location.belowbar, color = color.new(color.green, 0), style = shape.triangleup, text = 'rmv-e-pb', textcolor = color.new(color.green, 0))
//plotshape(bearishRmvSig and iBearishRmv, title = 'bearish rmv', location=location.abovebar, color = color.new(color.red, 0), style = shape.triangledown, text = 'rmv', textcolor = color.new(color.red, 0))
//plotshape(bearishRmvPbSig and iBearishRmvPb, title = 'bearish rmv-pb', location=location.abovebar, color = color.new(color.red, 0), style = shape.triangledown, text = 'rmv-pb', textcolor = color.new(color.red, 0))
//plotshape(bearishRmvEarningsSig and iBearishRmvEarnings, title = 'bearish rmv-e', location=location.abovebar, color = color.new(color.red, 0), style = shape.triangledown, text = 'rmv-e', textcolor = color.new(color.red, 0))
//plotshape(bearishRmvEarningsPbSig and iBearishRmvEarningsPb, title = 'bearish rmv-e-pb', location=location.abovebar, color = color.new(color.red, 0), style = shape.triangledown, text = 'rmv-e-pb', textcolor = color.new(color.red, 0))

//Signal: Mtb (Minevrini + Trigger Bar / Shakeout Demand Tail / Gap Down Reversal)
iMaxDistFromMaPctRank = input.int(defval = 10, title = 'Max. distance from MA', minval = 1, maxval = 99, display = display.none, group = 'Signal: Mtb')
iTriggerBarMaxPercentile = input.int(defval = 30, title = 'Trigger Bar max. percentiles', minval = 1, maxval = 99, display = display.none, group = 'Signal: Mtb')

sma50 = ta.sma(close, 50)
sma150 = ta.sma(close, 150)
sma200 = ta.sma(close, 200)
yearlyHigh = ta.highest(252)
yearlyLow = ta.lowest(252)
// shares = request.financial(syminfo.tickerid, "TOTAL_SHARES_OUTSTANDING", "FQ") // max 30M shares

//Minevrini trend
sma200GoingUp_10 = sma200 > sma200[1] ? 1 : 0
sma200GoingUpCond = math.sum(sma200GoingUp_10, 60) > 30
maCond = close > sma150 and close > sma200 and sma50 > sma150 and sma150 > sma200 and sma200 > sma200[1]
loHiCond = close > 1.25 * yearlyLow and close > yearlyHigh / 1.25
sma50Cond = close > sma50 / 1.08
 // and RS Score > 70
benchmark = request.security("SPY", timeframe.period, close)
simpleRelativeStrengthCond = close / benchmark > close[126] / benchmark[126] and close / benchmark > close[63] / benchmark[63]
minevriniTrendCond = maCond and loHiCond and sma50Cond and sma200GoingUpCond and simpleRelativeStrengthCond

//Jack Corsellis - Trigger Bar
candleHeight = high - low
candleHeightPrctRank = ta.percentrank(candleHeight, 50)
latestHigh = math.max(nz(math.abs(ta.highestbars(50)), 1), 50)
volumePrctRank = ta.percentrank(volume, latestHigh)
shortMaDistPrctRank = ta.percentrank(math.abs(ohlc4 - shortMa), 50)
maDistCond = shortMaDistPrctRank < iMaxDistFromMaPctRank
triggerBarCond = candleHeightPrctRank < iTriggerBarMaxPercentile and volumePrctRank < iTriggerBarMaxPercentile and maDistCond
bodySize = math.abs((open - close) / (high - low))
lowerWickSize = math.abs((low - math.min(open, close)) / (high - low))
hammerCandle = bodySize < 0.2 and lowerWickSize > 0.7
shakeoutDemandTailCond = hammerCandle and candleHeightPrctRank > 50 and volumePrctRank > 50 and maDistCond
gapDownReversalCandle = close[1] < open[1] and open < close[1] and close > close[1] and bodySize > bodySize[1]
gapDownReversalCond = gapDownReversalCandle and candleHeightPrctRank > 50 and volumePrctRank > 50 and maDistCond

mtbSig = ta.barssince(minevriniTrendCond) < 15 and (triggerBarCond or shakeoutDemandTailCond and gapDownReversalCond)

//Signal: Price-vol. correlation
iPcvMinCorrelation = input.float(defval = 0.75, title = 'PCV - min. correlation', minval = -1.0, maxval = 1.0, step = 0.05, display = display.none, group = 'Signal: Price-vol. correlation')
priceMa = ta.ema(close, 50)
volumeMa = ta.ema(volume, 50)
pvCorrelation = ta.correlation(priceMa, volumeMa, 50)
pvc = priceMa > priceMa[1] and pvCorrelation > iPcvMinCorrelation
pvc2 = pvc and gVShortMa1 > gVShortMa2 and close > shortMa

//Signal: Breakout
iBoVolumeMultiple = input.float(defval = 2.0, title = 'Breakout volume multiple', minval = 0.0, maxval = 5.0, step = 0.1, display = display.none, group = 'Signal: Breakout')
iBoMaxRiskPct = input.float(defval = 7.0, title = 'Breakout max risk', minval = 0.0, maxval = 12.0, step = 0.5, display = display.none, group = 'Signal: Breakout')

currCandleRelativeVol(int _iMaLength) =>
    candleVolPart = volume / ta.sma(volume, _iMaLength)
    candleTimePart = (math.min(timenow, time_close) - time) / (time_close - time)
    relativeVol = candleVolPart / candleTimePart
    relativeVol

candleRelativeVol = currCandleRelativeVol(iShortMaLength)
bullishRisk = 100 * (close / low[1] - 1)
bearisjRisk = 100 * (close / high[1] - 1)
candleBullishBoOnVolumeCond = close > high[1] and candleRelativeVol > iBoVolumeMultiple and bullishRisk < iBoMaxRiskPct
candleBearishBoOnVolumeCond = close < low[1] and candleRelativeVol > iBoVolumeMultiple and bearisjRisk < iBoMaxRiskPct

//Signal: O'Neil turnaround and GO
iTurnaroundExtremeAgo = input.int(defval = 45, title = "max. peak/bottom ago", minval = 20, maxval = 60, step = 5, display = display.none, group = "Signal: O'Neil turnaround and GO")
iturnaroundGoDayMinRange = input.float(defval = 0.0, title = "min. day range", minval = 0.0, maxval = 10.0, step = 0.1, display = display.none, group = "Signal: O'Neil turnaround and GO", tooltip = "Use 0 for auto calculation based on adr. \nfor adr < 0.017 uses 0.017\nfor adr >= 0.017 uses 0.017 + (adr - 0.017) / 4")
iTurnaroundMinGoDays = input.int(defval = 3, title = "min. days", minval = 1, maxval = 10, display = display.none, group = "Signal: O'Neil turnaround and GO")

vol50sma = ta.sma(volume, 50)

adr = adrPct / 100
turnaroundGoDayMinRange = iturnaroundGoDayMinRange > 0.0 ? iturnaroundGoDayMinRange / 100 : (adr < 0.017 ? 0.017 : 0.017 + (adr - 0.017) / 4)

bullGoSig = drelib.sigWONTurnaroundUp(iTurnaroundExtremeAgo, iTurnaroundMinGoDays, turnaroundGoDayMinRange, mainMa, vol50sma)
bearGoSig = drelib.sigWONTurnaroundDn(iTurnaroundExtremeAgo, iTurnaroundMinGoDays, turnaroundGoDayMinRange, mainMa, vol50sma)

//Signal: F.starter - GO - sma200crossover
fstarterNotLongAgo = ta.barssince(bullishFireStarterSig) < 150
bollGoNotLongAgo = ta.barssince(bullGoSig) < 150
fstarterGoSmaCrossover = drelib.crossover(mainMa) and fstarterNotLongAgo and bollGoNotLongAgo
sma175 = ta.sma(close, 175)
fstarterGoSma175Crossover = drelib.crossover(sma175) and fstarterNotLongAgo and bollGoNotLongAgo

//signals aggregate
bullishRmvSigs = bullishRmvSig or bullishRmvPbSig
bearishRmvSigs = bearishRmvSig or bearishRmvPbSig
bullishSig = juniorSig or bullishStarterSig or bullishFireStarterSig or bullishHunterSig or longerSig or bullishStepperSig or bullishLongerStepperSig or bullishObvSig or bullishRmvSigs or mtbSig
bearishSig = topSig or bearishStarterSig or bearishHunterSig or bearishObvSig or bearishRmvSigs

//check performance
iShowSigPerfTable = input.bool(defval = false, title = 'show table', display = display.none, group = 'Sig. performance check')
iShowOnlyGoodSigs = input.bool(defval = true, title = 'show only good sigs.', display = display.none, group = 'Sig. performance check')
iGoSigsExtremeLen = input.int(defval = 2, title = 'lowest, highest len. for GO sigs.', display = display.none, group = 'Sig. performance check')
// iShowSigPerfPlots = input.bool(defval = false, title = 'show plots', display = display.none, group = 'Sig. performnce check')

showRow(_iShowOnlyGoodSigs, sigOk) =>
    _iShowOnlyGoodSigs and sigOk or not _iShowOnlyGoodSigs

showRow(_iShowOnlyGoodSigs, sigOk, _showThisSig) =>
    _showThisSig and (_iShowOnlyGoodSigs and sigOk or not _iShowOnlyGoodSigs)

lowestFew = ta.lowest(iGoSigsExtremeLen)
highestFew = ta.highest(iGoSigsExtremeLen)

adrCond = iMinSigReturnAdrMultiple * adrPct

[topSuccRate, topSuccCount, topSigCount, topAvgReturn, topSuccRateOk, topSuccRateStr, topScore] = dreperf.successRateAllTimeStatsFull(topSig, topSig ? high : na, false, iMinSigSuccessRate, adrCond, iSigCheckTime)
[juniorSuccRate, juniorSuccCount, juniorSigCount, juniorAvgReturn, juniorSuccRateOk, juniorSuccRateStr, juniorScore] = dreperf.successRateAllTimeStatsFull(juniorSig, juniorSig ? low : na, true, iMinSigSuccessRate, adrCond, iSigCheckTime)
[junior2SuccRate, junior2SuccCount, junior2SigCount, junior2AvgReturn, junior2SuccRateOk, junior2SuccRateStr, junior2Score] = dreperf.successRateAllTimeStatsFull(junior2Sig, junior2Sig ? low : na, true, iMinSigSuccessRate, adrCond, iSigCheckTime)
[juniorLateSuccRate, juniorLateSuccCount, juniorLateSigCount, juniorLateAvgReturn, juniorLateSuccRateOk, juniorLateSuccRateStr, juniorLateScore] = dreperf.successRateAllTimeStatsFull(juniorLateSig, juniorLateSig ? low : na, true, iMinSigSuccessRate, adrCond, iSigCheckTime)
[coilBullishSuccRate, coilBullishSuccCount, coilBullishSigCount, coilBullishAvgReturn, coilBullishSuccRateOk, coilBullishSuccRateStr, coilBullishScore] = dreperf.successRateAllTimeStatsFull(coilBullishSig, coilBullishSig ? low : na, true, iMinSigSuccessRate, adrCond, iSigCheckTime)
[strechBearishSuccRate, strechBearishSuccCount, strechBearishSigCount, strechBearishAvgReturn, strechBearishSuccRateOk, strechBearishSuccRateStr, strechBearishScore] = dreperf.successRateAllTimeStatsFull(strechBearishSig, strechBearishSig ? high : na, false, iMinSigSuccessRate, adrCond, iSigCheckTime)
[bullishStarterSuccRate, bullishStarterSuccCount, bullishStarterSigCount, bullishStarterAvgReturn, bullishStarterSuccRateOk, bullishStarterSuccRateStr, bullishStarterScore] = dreperf.successRateAllTimeStatsFull(bullishStarterSig, bullishStarterSig ? low : na, true, iMinSigSuccessRate, adrCond, iSigCheckTime)
[bearishStarterSuccRate, bearishStarterSuccCount, bearishStarterSigCount, bearishStarterAvgReturn, bearishStarterSuccRateOk, bearishStarterSuccRateStr, bearishStarterScore] = dreperf.successRateAllTimeStatsFull(bearishStarterSig, bearishStarterSig ? high : na, false, iMinSigSuccessRate, adrCond, iSigCheckTime)
[bullishFireStarterSuccRate, bullishFireStarterSuccCount, bullishFireStarterSigCount, bullishFireStarterAvgReturn, bullishFireStarterSuccRateOk, bullishFireStarterSuccRateStr, bullishFireStarterScore] = dreperf.successRateAllTimeStatsFull(bullishFireStarterSig, bullishFireStarterSig ? low : na, true, iMinSigSuccessRate, adrCond, iSigCheckTime)
[longerSuccRate, longerSuccCount, longerSigCount, longerAvgReturn, longerSuccRateOk, longerSuccRateStr, longerScore] = dreperf.successRateAllTimeStatsFull(longerSig, longerSig ? low : na, true, iMinSigSuccessRate, adrCond, iSigCheckTime)
[smallerLongerSuccRate, smallerLongerSuccCount, smallerLongerSigCount, smallerLongerAvgReturn, smallerLongerSuccRateOk, smallerLongerSuccRateStr, smallerLongerScore] = dreperf.successRateAllTimeStatsFull(smallerLongerSig, smallerLongerSig ? low : na, true, iMinSigSuccessRate, adrCond, iSigCheckTime)
[zscoreBullishSuccRate, zscoreBullishSuccCount, zscoreBullishSigCount, zscoreBullishAvgReturn, zscoreBullishSuccRateOk, zscoreBullishSuccRateStr, zscoreBullishScore] = dreperf.successRateAllTimeStatsFull(zscoreBullishSig, zscoreBullishSig ? low : na, true, iMinSigSuccessRate, adrCond, iSigCheckTime)
[zscoreBearishSuccRate, zscoreBearishSuccCount, zscoreBearishSigCount, zscoreBearishAvgReturn, zscoreBearishSuccRateOk, zscoreBearishSuccRateStr, zscoreBearishScore] = dreperf.successRateAllTimeStatsFull(zscoreBearishSig, zscoreBearishSig ? high : na, false, iMinSigSuccessRate, adrCond, iSigCheckTime)
[bullishHunterSuccRate, bullishHunterSuccCount, bullishHunterSigCount, bullishHunterAvgReturn, bullishHunterSuccRateOk, bullishHunterSuccRateStr, bullishHunterScore] = dreperf.successRateAllTimeStatsFull(bullishHunterSig, bullishHunterSig ? low : na, true, iMinSigSuccessRate, adrCond, iSigCheckTime)
[bearishHunterSuccRate, bearishHunterSuccCount, bearishHunterSigCount, bearishHunterAvgReturn, bearishHunterSuccRateOk, bearishHunterSuccRateStr, bearishHunterScore] = dreperf.successRateAllTimeStatsFull(bearishHunterSig, bearishHunterSig ? high : na, false, iMinSigSuccessRate, adrCond, iSigCheckTime)
[bullishStepperSuccRate, bullishStepperSuccCount, bullishStepperSigCount, bullishStepperAvgReturn, bullishStepperSuccRateOk, bullishStepperSuccRateStr, bullishStepperScore] = dreperf.successRateAllTimeStatsFull(bullishStepperSig, bullishStepperSig ? low : na, true, iMinSigSuccessRate, adrCond, iSigCheckTime)
[bullishLongerStepperSuccRate, bullishLongerStepperSuccCount, bullishLongerStepperSigCount, bullishLongerStepperAvgReturn, bullishLongerStepperSuccRateOk, bullishLongerStepperSuccRateStr, bullishLongerStepperScore] = dreperf.successRateAllTimeStatsFull(bullishLongerStepperSig, bullishLongerStepperSig ? low : na, true, iMinSigSuccessRate, adrCond, iSigCheckTime)
[bullishSLongerStepperSuccRate, bullishSLongerStepperSuccCount, bullishSLongerStepperSigCount, bullishSLongerStepperAvgReturn, bullishSLongerStepperSuccRateOk, bullishSLongerStepperSuccRateStr, bullishSLongerStepperScore] = dreperf.successRateAllTimeStatsFull(bullishSLongerStepperSig, bullishSLongerStepperSig ? low : na, true, iMinSigSuccessRate, adrCond, iSigCheckTime)
[bullishObvSuccRate, bullishObvSuccCount, bullishObvSigCount, bullishObvAvgReturn, bullishObvSuccRateOk, bullishObvSuccRateStr, bullishObvScore] = dreperf.successRateAllTimeStatsFull(bullishObvSig, bullishObvSig ? low : na, true, iMinSigSuccessRate, adrCond, iSigCheckTime)
[bearishObvSuccRate, bearishObvSuccCount, bearishObvSigCount, bearishObvAvgReturn, bearishObvSuccRateOk, bearishObvSuccRateStr, bearishObvScore] = dreperf.successRateAllTimeStatsFull(bearishObvSig, bearishObvSig ? high : na, false, iMinSigSuccessRate, adrCond, iSigCheckTime)
[bullGoSuccRate, bullGoSuccCount, bullGoSigCount, bullGoAvgReturn, bullGoSuccRateOk, bullGoSuccRateStr, bullGoScore] = dreperf.successRateAllTimeStatsFull(bullGoSig, bullGoSig ? lowestFew : na, true, iMinSigSuccessRate, adrCond, iSigCheckTime)
[bearGoSuccRate, bearGoSuccCount, bearGoSigCount, bearGoAvgReturn, bearGoSuccRateOk, bearGoSuccRateStr, bearGoScore] = dreperf.successRateAllTimeStatsFull(bearGoSig, bearGoSig ? highestFew : na, false, iMinSigSuccessRate, adrCond, iSigCheckTime)
[fstarterGoSmaCrossoverSuccRate, fstarterGoSmaCrossoverSuccCount, fstarterGoSmaCrossoverSigCount, fstarterGoSmaCrossoverAvgReturn, fstarterGoSmaCrossoverSuccRateOk, fstarterGoSmaCrossoverSuccRateStr, fstarterGoSmaCrossoverScore] = dreperf.successRateAllTimeStatsFull(fstarterGoSmaCrossover, fstarterGoSmaCrossover ? lowestFew : na, true, iMinSigSuccessRate, adrCond, iSigCheckTime)
[fstarterGoSma175CrossoverSuccRate, fstarterGoSma175CrossoverSuccCount, fstarterGoSma175CrossoverSigCount, fstarterGoSma175CrossoverAvgReturn, fstarterGoSma175CrossoverSuccRateOk, fstarterGoSma175CrossoverSuccRateStr, fstarterGoSma175CrossoverScore] = dreperf.successRateAllTimeStatsFull(fstarterGoSma175Crossover, fstarterGoSma175Crossover ? lowestFew : na, true, iMinSigSuccessRate, adrCond, iSigCheckTime)
[pvcSuccRate, pvcSuccCount, pvcSigCount, pvcAvgReturn, pvcSuccRateOk, pvcSuccRateStr, pvcScore] = dreperf.successRateAllTimeStatsFull(pvc, pvc ? low : na, true, iMinSigSuccessRate, adrCond, iSigCheckTime)
[pvc2SuccRate, pvc2SuccCount, pvc2SigCount, pvc2AvgReturn, pvc2SuccRateOk, pvc2SuccRateStr, pvc2Score] = dreperf.successRateAllTimeStatsFull(pvc2, pvc2 ? low : na, true, iMinSigSuccessRate, adrCond, iSigCheckTime)

//plot sig performance
topSigColor = color.new(color.red, 0)
juniorSigColor = color.new(color.green, 0)
junior2SigColor = color.new(color.green, 0)
juniorLateSigColor = color.new(color.green, 0)
coilBullishSigColor = color.new(color.gray, 0)
strechBearishSigColor = color.new(color.red, 0)
bullishStarterSigColor = color.new(color.green, 0)
bearishStarterSigColor = color.new(color.red, 0)
bullishFireStarterSigColor = color.new(color.green, 0)
longerSigColor = color.new(color.green, 0)
smallerLongerSigColor = color.new(color.green, 0)
zscoreBullishSigColor = color.new(color.gray, 0)
zscoreBearishSigColor = color.new(color.gray, 0)
bullishHunterSigColor = color.new(color.green, 0)
bearishHunterSigColor = color.new(color.red, 0)
bullishStepperSigColor = color.new(color.green, 0)
bullishLongerStepperSigColor = color.new(color.green, 0)
bullishSLongerStepperSigColor = color.new(color.green, 0)
bullishObvSigColor = color.new(color.green, 0)
bearishObvSigColor = color.new(color.red, 0)
bullGoSigColor = color.new(color.green, 0)
bearGoSigColor = color.new(color.red, 0)
fstarterGoSmaCrossoverSigColor = color.new(color.green, 0)
fstarterGoSma175CrossoverSigColor = color.new(color.green, 0)

//print sig performance table
if barstate.islast and iShowSigPerfTable
    var tbl = table.new(position = position.top_right, columns = 2, rows = 28)
    txtSize = size.small
    table.cell(table_id = tbl, column = 0, row = 0, text = '')
    table.cell(table_id = tbl, column = 1, row = 0, text = '')
    table.cell(table_id = tbl, column = 0, row = 1, text = "sig", text_size = txtSize)
    table.cell(table_id = tbl, column = 1, row = 1, text = str.format("perf {0,number,#.#} {1,number,#.#}", iMinSigSuccessRate, adrCond), text_size = txtSize)

    if showRow(iShowOnlyGoodSigs, topSuccRateOk, iParabolicTop)
        table.cell(table_id = tbl, column = 0, row = 2, text = "parabolic top", text_color = topSigColor, text_size = txtSize)
        table.cell(table_id = tbl, column = 1, row = 2, text = topSuccRateStr, text_size = txtSize)
    if showRow(iShowOnlyGoodSigs, juniorSuccRateOk, iJunior)
        table.cell(table_id = tbl, column = 0, row = 3, text = "junior", text_color = juniorSigColor, text_size = txtSize)
        table.cell(table_id = tbl, column = 1, row = 3, text = juniorSuccRateStr, text_size = txtSize)
    if showRow(iShowOnlyGoodSigs, junior2SuccRateOk, iJunior2)
        table.cell(table_id = tbl, column = 0, row = 4, text = "junior2", text_color = junior2SigColor, text_size = txtSize)
        table.cell(table_id = tbl, column = 1, row = 4, text = junior2SuccRateStr, text_size = txtSize)
    if showRow(iShowOnlyGoodSigs, juniorLateSuccRateOk, iJunior3)
        table.cell(table_id = tbl, column = 0, row = 5, text = "late-junior", text_color = juniorLateSigColor, text_size = txtSize)
        table.cell(table_id = tbl, column = 1, row = 5, text = juniorLateSuccRateStr, text_size = txtSize)
    if showRow(iShowOnlyGoodSigs, coilBullishSuccRateOk, iCoil)
        table.cell(table_id = tbl, column = 0, row = 6, text = "coil", text_color = coilBullishSigColor, text_size = txtSize)
        table.cell(table_id = tbl, column = 1, row = 6, text = coilBullishSuccRateStr, text_size = txtSize)
    if showRow(iShowOnlyGoodSigs, strechBearishSuccRateOk, iCoilStrech)
        table.cell(table_id = tbl, column = 0, row = 7, text = "strech", text_color = strechBearishSigColor, text_size = txtSize)
        table.cell(table_id = tbl, column = 1, row = 7, text = strechBearishSuccRateStr, text_size = txtSize)
    if showRow(iShowOnlyGoodSigs, bullishStarterSuccRateOk, iBullishStarter)
        table.cell(table_id = tbl, column = 0, row = 8, text = "Starter", text_color = bullishStarterSigColor, text_size = txtSize)
        table.cell(table_id = tbl, column = 1, row = 8, text = bullishStarterSuccRateStr, text_size = txtSize)
    if showRow(iShowOnlyGoodSigs, bearishStarterSuccRateOk, iBearishStarter)
        table.cell(table_id = tbl, column = 0, row = 9, text = "bear Starter", text_color = bearishStarterSigColor, text_size = txtSize)
        table.cell(table_id = tbl, column = 1, row = 9, text = bearishStarterSuccRateStr, text_size = txtSize)
    if showRow(iShowOnlyGoodSigs, bullishFireStarterSuccRateOk, iBullishFireStarter)
        table.cell(table_id = tbl, column = 0, row = 10, text = "FireStarter", text_color = bullishFireStarterSigColor, text_size = txtSize)
        table.cell(table_id = tbl, column = 1, row = 10, text = bullishFireStarterSuccRateStr, text_size = txtSize)
    if showRow(iShowOnlyGoodSigs, longerSuccRateOk, iLonger)
        table.cell(table_id = tbl, column = 0, row = 11, text = "longer", text_color = longerSigColor, text_size = txtSize)
        table.cell(table_id = tbl, column = 1, row = 11, text = longerSuccRateStr, text_size = txtSize)
    if showRow(iShowOnlyGoodSigs, smallerLongerSuccRateOk, iLonger)
        table.cell(table_id = tbl, column = 0, row = 12, text = "s-longer", text_color = smallerLongerSigColor, text_size = txtSize)
        table.cell(table_id = tbl, column = 1, row = 12, text = smallerLongerSuccRateStr, text_size = txtSize)
    if showRow(iShowOnlyGoodSigs, zscoreBullishSuccRateOk, iBullishZscore)
        table.cell(table_id = tbl, column = 0, row = 13, text = "bubble up", text_color = zscoreBullishSigColor, text_size = txtSize)
        table.cell(table_id = tbl, column = 1, row = 13, text = zscoreBullishSuccRateStr, text_size = txtSize)
    if showRow(iShowOnlyGoodSigs, zscoreBearishSuccRateOk, iBearishZscore)
        table.cell(table_id = tbl, column = 0, row = 14, text = "bubble dn", text_color = zscoreBearishSigColor, text_size = txtSize)
        table.cell(table_id = tbl, column = 1, row = 14, text = zscoreBearishSuccRateStr, text_size = txtSize)
    if showRow(iShowOnlyGoodSigs, bullishHunterSuccRateOk, iBullishHunter)
        table.cell(table_id = tbl, column = 0, row = 15, text = "bullishHunter", text_color = bullishHunterSigColor, text_size = txtSize)
        table.cell(table_id = tbl, column = 1, row = 15, text = bullishHunterSuccRateStr, text_size = txtSize)
    if showRow(iShowOnlyGoodSigs, bearishHunterSuccRateOk, iBearishHunter)
        table.cell(table_id = tbl, column = 0, row = 16, text = "bearishHunter", text_color = bearishHunterSigColor, text_size = txtSize)
        table.cell(table_id = tbl, column = 1, row = 16, text = bearishHunterSuccRateStr, text_size = txtSize)
    if showRow(iShowOnlyGoodSigs, bullishStepperSuccRateOk, iBullishStepper)
        table.cell(table_id = tbl, column = 0, row = 17, text = "Stepper", text_color = bullishStepperSigColor, text_size = txtSize)
        table.cell(table_id = tbl, column = 1, row = 17, text = bullishStepperSuccRateStr, text_size = txtSize)
    if showRow(iShowOnlyGoodSigs, bullishLongerStepperSuccRateOk, iBullishLongerStepper)
        table.cell(table_id = tbl, column = 0, row = 18, text = "LongerStepper", text_color = bullishLongerStepperSigColor, text_size = txtSize)
        table.cell(table_id = tbl, column = 1, row = 18, text = bullishLongerStepperSuccRateStr, text_size = txtSize)
    if showRow(iShowOnlyGoodSigs, bullishSLongerStepperSuccRateOk, iBullishLongerStepper)
        table.cell(table_id = tbl, column = 0, row = 19, text = "s-LongerStepper", text_color = bullishSLongerStepperSigColor, text_size = txtSize)
        table.cell(table_id = tbl, column = 1, row = 19, text = bullishSLongerStepperSuccRateStr, text_size = txtSize)
    if showRow(iShowOnlyGoodSigs, bullishObvSuccRateOk, iBullishObv)
        table.cell(table_id = tbl, column = 0, row = 20, text = "obv", text_color = bullishObvSigColor, text_size = txtSize)
        table.cell(table_id = tbl, column = 1, row = 20, text = bullishObvSuccRateStr, text_size = txtSize)
    if showRow(iShowOnlyGoodSigs, bearishObvSuccRateOk, iBearishObv)
        table.cell(table_id = tbl, column = 0, row = 21, text = "bear obv", text_color = bearishObvSigColor, text_size = txtSize)
        table.cell(table_id = tbl, column = 1, row = 21, text = bearishObvSuccRateStr, text_size = txtSize)
    if showRow(iShowOnlyGoodSigs, bullGoSuccRateOk, iTurnaroundGo)
        table.cell(table_id = tbl, column = 0, row = 22, text = "WON-bullGO", text_color = bullGoSigColor, text_size = txtSize)
        table.cell(table_id = tbl, column = 1, row = 22, text = bullGoSuccRateStr, text_size = txtSize)
    if showRow(iShowOnlyGoodSigs, bearGoSuccRateOk, iTurnaroundGo)
        table.cell(table_id = tbl, column = 0, row = 23, text = "WON-bearGO", text_color = bearGoSigColor, text_size = txtSize)
        table.cell(table_id = tbl, column = 1, row = 23, text = bearGoSuccRateStr, text_size = txtSize)
    if showRow(iShowOnlyGoodSigs, fstarterGoSmaCrossoverSuccRateOk, iFStarterGoSmaCrossover)
        table.cell(table_id = tbl, column = 0, row = 24, text = "FS-GO-CO", text_color = fstarterGoSmaCrossoverSigColor, text_size = txtSize)
        table.cell(table_id = tbl, column = 1, row = 24, text = fstarterGoSmaCrossoverSuccRateStr, text_size = txtSize)
    if showRow(iShowOnlyGoodSigs, fstarterGoSma175CrossoverSuccRateOk, iFStarterGoSmaCrossover)
        table.cell(table_id = tbl, column = 0, row = 25, text = "FS-GO-CO2", text_color = fstarterGoSma175CrossoverSigColor, text_size = txtSize)
        table.cell(table_id = tbl, column = 1, row = 25, text = fstarterGoSma175CrossoverSuccRateStr, text_size = txtSize)
    if showRow(iShowOnlyGoodSigs, pvcSuccRateOk)
        table.cell(table_id = tbl, column = 0, row = 26, text = "pvc", text_size = txtSize)
        table.cell(table_id = tbl, column = 1, row = 26, text = pvcSuccRateStr, text_size = txtSize)
    if showRow(iShowOnlyGoodSigs, pvc2SuccRateOk)
        table.cell(table_id = tbl, column = 0, row = 27, text = "pvc2", text_size = txtSize)
        table.cell(table_id = tbl, column = 1, row = 27, text = pvc2SuccRateStr, text_size = txtSize)

//plot signals on price chart
plotshape(topSig and showRow(iShowOnlyGoodSigs, topSuccRateOk, iParabolicTop), title = 'parabolic top', location = location.abovebar, color = topSigColor, style = shape.triangledown, text = 'top', textcolor = topSigColor)
plotshape(juniorSig and showRow(iShowOnlyGoodSigs, juniorSuccRateOk, iJunior), title = 'junior', location = location.belowbar, color = juniorSigColor, style = shape.triangleup, text = 'junior', textcolor = juniorSigColor)
plotshape(junior2Sig and showRow(iShowOnlyGoodSigs, junior2SuccRateOk, iJunior2), title = 'junior2', location = location.belowbar, color = junior2SigColor, style = shape.triangleup, text = 'junior2', textcolor = junior2SigColor)
plotshape(juniorLateSig and showRow(iShowOnlyGoodSigs, juniorLateSuccRateOk, iJunior3), title = 'late-junior', location = location.belowbar, color = juniorLateSigColor, style = shape.triangleup, text = 'late-junior', textcolor = juniorLateSigColor)
plotshape(coilBullishSig and showRow(iShowOnlyGoodSigs, coilBullishSuccRateOk, iCoil), title = 'coil', location = location.belowbar, color = coilBullishSigColor, style = shape.xcross, text = 'coil', textcolor = coilBullishSigColor)
plotshape(strechBearishSig and showRow(iShowOnlyGoodSigs, strechBearishSuccRateOk, iCoilStrech), title = 'strech', location = location.abovebar, color = strechBearishSigColor, style = shape.triangledown, text = 'strech', textcolor = strechBearishSigColor)
plotshape(bullishStarterSig and showRow(iShowOnlyGoodSigs, bullishStarterSuccRateOk, iBullishStarter), title = 'bullish starter', location = location.belowbar, color = bullishStarterSigColor, style = shape.triangleup, text = 'starter', textcolor = bullishStarterSigColor)
plotshape(bearishStarterSig and showRow(iShowOnlyGoodSigs, bearishStarterSuccRateOk, iBearishStarter), title = 'bearish starter', location = location.abovebar, color = bearishStarterSigColor, style = shape.triangledown, text = 'starter', textcolor = bearishStarterSigColor)
plotshape(bullishFireStarterSig and showRow(iShowOnlyGoodSigs, bullishFireStarterSuccRateOk, iBullishFireStarter), title = 'bullish fire starter', location = location.belowbar, color = bullishFireStarterSigColor, style = shape.triangleup, text = 'f.starter', textcolor = bullishFireStarterSigColor)
plotshape(longerSig and showRow(iShowOnlyGoodSigs, longerSuccRateOk, iLonger), title = 'longer', location = location.belowbar, color = longerSigColor, style = shape.triangleup, text = 'longer', textcolor = longerSigColor)
plotshape(smallerLongerSig and showRow(iShowOnlyGoodSigs, smallerLongerSuccRateOk, iLonger), title = 's-longer', location = location.belowbar, color = smallerLongerSigColor, style = shape.triangleup, text = 's-longer', textcolor = smallerLongerSigColor)
plotshape(zscoreBullishSig and showRow(iShowOnlyGoodSigs, zscoreBullishSuccRateOk, iBullishZscore), title = 'bubble up', location = location.belowbar, color = zscoreBullishSigColor, style = shape.xcross, text = 'bubble up', textcolor = zscoreBullishSigColor)
plotshape(zscoreBearishSig and showRow(iShowOnlyGoodSigs, zscoreBearishSuccRateOk, iBearishZscore), title = 'bubble dn', location = location.belowbar, color = zscoreBearishSigColor, style = shape.xcross, text = 'bubble dn', textcolor = zscoreBearishSigColor)
plotshape(bullishHunterSig and showRow(iShowOnlyGoodSigs, bullishHunterSuccRateOk, iBullishHunter), title = 'bullish hunter', location = location.belowbar, color = bullishHunterSigColor, style = shape.triangleup, text = 'hunter', textcolor = bullishHunterSigColor)
plotshape(bearishHunterSig and showRow(iShowOnlyGoodSigs, bearishHunterSuccRateOk, iBearishHunter), title = 'bearish hunter', location = location.abovebar, color = bearishHunterSigColor, style = shape.triangledown, text = 'hunter', textcolor = bearishHunterSigColor)
plotshape(bullishStepperSig and not bullishLongerStepperSig and showRow(iShowOnlyGoodSigs, bullishStepperSuccRateOk, iBullishStepper), title = 'bullish stepper', location = location.belowbar, color = bullishStepperSigColor, style = shape.triangleup, text = 'stepper', textcolor = bullishStepperSigColor)
plotshape(bullishLongerStepperSig and showRow(iShowOnlyGoodSigs, bullishLongerStepperSuccRateOk, iBullishLongerStepper), title = 'bullish l.stepper', location = location.belowbar, color = bullishLongerStepperSigColor, style = shape.triangleup, text = 'l.stepper', textcolor = bullishLongerStepperSigColor)
plotshape(bullishSLongerStepperSig and showRow(iShowOnlyGoodSigs, bullishSLongerStepperSuccRateOk, iBullishLongerStepper), title = 'bullish s-l.stepper', location = location.belowbar, color = bullishSLongerStepperSigColor, style = shape.triangleup, text = 's-l.stepper', textcolor = bullishSLongerStepperSigColor)
plotshape(bullishObvSig and showRow(iShowOnlyGoodSigs, bullishObvSuccRateOk, iBullishObv), title = 'bullish obv', location = location.belowbar, color = bullishObvSigColor, style = shape.triangleup, text = 'obv', textcolor = bullishObvSigColor)
plotshape(bearishObvSig and showRow(iShowOnlyGoodSigs, bearishObvSuccRateOk, iBearishObv), title = 'bearish obv', location = location.abovebar, color = bearishObvSigColor, style = shape.triangledown, text = 'obv', textcolor = bearishObvSigColor)
plotshape(bullGoSig and showRow(iShowOnlyGoodSigs, bullGoSuccRateOk, iTurnaroundGo), title = 'bullish GO', location = location.belowbar, color = bullGoSigColor, style = shape.triangleup, text = 'GO', textcolor = bullGoSigColor)
plotshape(bearGoSig and showRow(iShowOnlyGoodSigs, bearGoSuccRateOk, iTurnaroundGo), title = 'bearish GO', location = location.abovebar, color = bearGoSigColor, style = shape.triangledown, text = 'GO', textcolor = bearGoSigColor)
plotshape(fstarterGoSmaCrossover and showRow(iShowOnlyGoodSigs, fstarterGoSmaCrossoverSuccRateOk, iFStarterGoSmaCrossover), title = 'bullish fstarter-GO-CO', location = location.belowbar, color = fstarterGoSmaCrossoverSigColor, style = shape.triangleup, text = 'FS-GO-CO', textcolor = fstarterGoSmaCrossoverSigColor)
plotshape(fstarterGoSma175Crossover and showRow(iShowOnlyGoodSigs, fstarterGoSma175CrossoverSuccRateOk, iFStarterGoSmaCrossover), title = 'bullish fstarter-GO-CO175', location = location.belowbar, color = fstarterGoSma175CrossoverSigColor, style = shape.triangleup, text = 'FS-GO-CO2', textcolor = fstarterGoSma175CrossoverSigColor)

//issuing alerts
alertcondition(gFilter and topSig, title = 'DRE Parabolic TOP sig', message = 'parabolic TOP')
alertcondition(juniorSig, title = 'DRE junior sig', message = 'junior')
alertcondition(juniorLateSig, title = 'DRE late-junior', message = 'late-junior')
alertcondition(junior2Sig, title = 'DRE junior2 sig', message = 'junior2')
alertcondition(gFilter and coilBullishSig, title = 'DRE coil sig', message = 'coil')
alertcondition(gFilter and strechBearishSig, title = 'DRE strech sig', message = 'strech')
alertcondition(gFilter and bullishStarterSig, title = 'DRE bullish starter sig', message = 'bullish starter')
alertcondition(gFilter and bearishStarterSig, title = 'DRE bearish starter sig', message = 'bearish starter')
alertcondition(gFilter and bullishFireStarterSig, title = 'DRE bullish fire starter sig', message = 'bullish fire starter')
alertcondition(gFilter and longerSig, title = 'DRE longer sig', message = 'longer')
alertcondition(gFilter and smallerLongerSig, title = 'DRE sLonger sig', message = 's-longer')
alertcondition(gFilter and zscoreBullishSig, title = 'DRE bubble up', message = 'bubble up')
alertcondition(gFilter and zscoreBearishSig, title = 'DRE bubble dn', message = 'bubble dn')
alertcondition(gFilter and bullishHunterSig, title = 'DRE Bullish hunter', message = 'hunter')
alertcondition(gFilter and bearishHunterSig, title = 'DRE Bearish hunter', message = 'hunter')
alertcondition(gFilter and bullishStepperSig, title = 'DRE Bullish stepper', message = 'stepper')
alertcondition(gFilter and bullishLongerStepperSig, title = 'DRE Bullish longer-stepper', message = 'l.stepper')
alertcondition(gFilter and bullishSLongerStepperSig, title = 'DRE Bullish s-longer-stepper', message = 's-l.stepper')
alertcondition(gFilter and bullishObvSig, title = 'DRE Bullish obv', message = 'obv')
alertcondition(gFilter and bearishObvSig, title = 'DRE Bearish obv', message = 'obv')
alertcondition(gFilter and bullishRmvSig, title = 'DRE Bullish rmv', message = 'rmv')
alertcondition(gFilter and bullishRmvPbSig, title = 'DRE Bullish rmv-pb', message = 'rmv-pb')
alertcondition(gFilter and bearishRmvSig, title = 'DRE Bearish rmv', message = 'rmv')
alertcondition(gFilter and bearishRmvPbSig, title = 'DRE Bearish rmv-pb', message = 'rmv-pb')
alertcondition(gFilter and mtbSig, title = 'DRE Bullish mtb', message = 'mtb')

alertcondition(gFilter and bullishSig, title = 'DRE Bullish pattern sig', message = 'bullish pattern')
alertcondition(gFilter and bearishSig, title = 'DRE Bearish pattern sig', message = 'bearish pattern')
alertcondition(gFilter and (bullishSig or bearishSig), title = 'DRE ALL pattern sig', message = 'all patterns')

alertcondition(candleBullishBoOnVolumeCond and gFilter and mtbSig[1], title = 'DRE Bullish mtb BO sig', message = 'bullish mtb BO')
alertcondition(candleBullishBoOnVolumeCond and gFilter and bullishSig[1], title = 'DRE Bullish pattern BO sig', message = 'bullish pattern BO')
alertcondition(candleBearishBoOnVolumeCond and gFilter and bearishSig[1], title = 'DRE Bearish pattern BO sig', message = 'bearish pattern BO')
alertcondition(gFilter and (candleBullishBoOnVolumeCond and bullishSig[1] or candleBearishBoOnVolumeCond and bearishSig[1]), title = 'DRE ALL pattern BO sig', message = 'all patterns BO')
