// This Pine Script® code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © drebel

//@version=6
indicator(title = 'DRE When-Sell', overlay = true, calc_bars_count = 12 * 252)

import drebel/DRELib/39 as drelib
import drebel/DREPerf/23 as dreperf

iShowCloseBelowSma1 = input.bool(defval = false, title = 'Show close below sma1', group = 'Signals', inline = 'sma')
iShowCloseBelowSma2 = input.bool(defval = false, title = 'sma2', group = 'Signals', inline = 'sma')
iShowCloseBelowSma3 = input.bool(defval = false, title = 'sma3', group = 'Signals', inline = 'sma')
iShowParabolicTop = input.bool(defval = true, title = 'Show parabolic top', group = 'Signals')
iShowParabolicTipTop = input.bool(defval = true, title = 'Show Parabolic tip-top (by @Braczyy)', group = 'Signals')
iShowParabolicRiseStop = input.bool(defval = true, title = 'Show Parabolic rise LOD break', group = 'Signals')
iShowWONTurnaroundGo = input.bool(defval = true, title = "Show W. O'Neail (WON) turnaround GO", group = "Signals")
iShowCombiSig1 = input.bool(defval = true, title = "Show ParaLodBreak + WON turnaround GO", group = "Signals")
iShowCombiSig2 = input.bool(defval = true, title = "Show ParaLodBreak + sma1", group = "Signals")
iShowCombiSig3 = input.bool(defval = true, title = "Show ParaLodBreak + sma2", group = "Signals")

iSmaLen1 = input.int(defval = 10, title = 'SMA1 len', minval = 1, display = display.none, group = 'Moving averages')
iSmaLen2 = input.int(defval = 20, title = 'SMA2 len', minval = 1, display = display.none, group = 'Moving averages')
iSmaLen3 = input.int(defval = 50, title = 'SMA3 len', minval = 1, display = display.none, group = 'Moving averages')

iParabolicRisePercentile = input.int(defval = 97, title = 'Percentile above sma 1/2/3', minval = 0, maxval = 100, display = display.none, group = 'Parabolic rise - LOD break')
iParabolicRiseBigRedCandle = input.float(defval = 2.1, title = 'Min. ATR multiple', minval = 0, maxval = 5.0, step = 0.1, display = display.none, group = 'Parabolic rise - LOD break')
iParabolicRiseVolumeCond = input.bool(defval = true, title = 'Highest volume of last 10 days within last 3 days', display = display.none, group = 'Parabolic rise - LOD break')

iParabolicTipTopConditions = input.int(defval = 5, title = 'Min. conditions', minval = 3, maxval = 8, display = display.none, group = 'Parabolic tip-top (by @Braczyy)')

sma1 = ta.sma(close, iSmaLen1)
sma2 = ta.sma(close, iSmaLen2)
sma3 = ta.sma(close, iSmaLen3)
sma200 = ta.sma(close, 200)
atr50 = ta.sma(high - low, 50)
volHighest10 = ta.highest(volume, 10)
volMa = ta.sma(volume, 30)
vol50Ma = ta.sma(volume, 50)
atr200 = ta.atr(200)
adrPct = 100.0 * (ta.sma(high / low, 100) - 1)

//candle parameters
candleBody = high != low ? (math.max(open, close) - math.min(open, close)) / (high-low) : 0
candleColor = close > open ? 1 : close < open ? -1 : 0
isMarubozuGreen = candleBody > 0.75 and candleColor == 1

//parabolic top by @Braczyy (https://x.com/Braczyy/status/1978067812527571223)
move12week = high / ta.lowest(12 * 5)
over200sma = close / sma200
consecutiveDaysUp = ta.barssince(close <= close[1])
rng = (high-low) / close
consecutiveRangeUp = ta.barssince(rng <= rng[1])
consecutiveVolumeUp = ta.barssince(volume <= volume[1])
gain = (close - close[1]) / close[1]
highestGain = ta.highest(gain, 12 * 5)
unfilledGapUp = low > close[1]
consecutiveUnfilledGapUp = ta.barssince(not unfilledGapUp)
gapSize = open - close[1]
highestGapSize = ta.highest(gapSize, 12 * 5)
//parabolicTipTip = move12week >= 10 and over200sma >= 5 and consecutiveDaysUp >= 7 and consecutiveRangeUp >= 3 and consecutiveVolumeUp >= 3 and gain == highestGain and consecutiveUnfilledGapUp >= 6 and gapSize == highestGapSize
parabolicTipTipMandatoryConditions = move12week >= 5 and over200sma >= 2.5
parabolicTipTipOptionalConditionsMet = (move12week >= 10 ? 1 : 0) + (over200sma >= 5 ? 1 : 0) + (consecutiveDaysUp >= 7 ? 1 : 0) + (consecutiveRangeUp >= 3 ? 1 : 0) + (consecutiveVolumeUp >= 3 ? 1 : 0 ) + (gain == highestGain ? 1 : 0) + (consecutiveUnfilledGapUp[1] >= 5 ? 1 : 0) + (gapSize == highestGapSize ? 1 : 0)
orbd = drelib.openingRangeBreakdown(60, true, true)
parabolicTipTopCond = parabolicTipTipMandatoryConditions and parabolicTipTipOptionalConditionsMet >= iParabolicTipTopConditions
parabolicTipTopCond2 = (orbd or close < close[1]) and (parabolicTipTopCond or parabolicTipTopCond[1] or parabolicTipTopCond[2])
parabolicTipTop = parabolicTipTopCond2 and not parabolicTipTopCond2[1]

parabolicTipTop4Cond = parabolicTipTipMandatoryConditions and parabolicTipTipOptionalConditionsMet >= 4
parabolicTipTop4Cond2 = (orbd or close < close[1]) and (parabolicTipTop4Cond or parabolicTipTop4Cond[1] or parabolicTipTop4Cond[2])
parabolic4TipTop = parabolicTipTop4Cond2 and not parabolicTipTop4Cond2[1]

parabolicTipTop5Cond = parabolicTipTipMandatoryConditions and parabolicTipTipOptionalConditionsMet >= 5
parabolicTipTop5Cond2 = (orbd or close < close[1]) and (parabolicTipTop5Cond or parabolicTipTop5Cond[1] or parabolicTipTop5Cond[2])
parabolic5TipTop = parabolicTipTop5Cond2 and not parabolicTipTop5Cond2[1]

parabolicTipTop6Cond = parabolicTipTipMandatoryConditions and parabolicTipTipOptionalConditionsMet >= 6
parabolicTipTop6Cond2 = (orbd or close < close[1]) and (parabolicTipTop6Cond or parabolicTipTop6Cond[1] or parabolicTipTop6Cond[2])
parabolic6TipTop = parabolicTipTop6Cond2 and not parabolicTipTop6Cond2[1]

//parabolic rise LOD break
aboveSma1PctCond = ta.percentrank(high - sma1, 500) >= iParabolicRisePercentile
aboveSma2PctCond = ta.percentrank(high - sma2, 500) >= iParabolicRisePercentile
aboveSma3PctCond = ta.percentrank(high - sma3, 500) >= iParabolicRisePercentile
volumeCond = iParabolicRiseVolumeCond and (volume == volHighest10 or volume[1] == volHighest10[1] or volume[2] == volHighest10[2]) or not iParabolicRiseVolumeCond

parabolicRiseCond = aboveSma1PctCond and aboveSma2PctCond and aboveSma3PctCond and close > 1.7 * close[100]
veryBigCandle = (high - low) > atr50 * iParabolicRiseBigRedCandle
parabolicRiseLodBreak = (parabolicRiseCond[1] or parabolicRiseCond) and low < low[1] and (veryBigCandle or veryBigCandle[1]) and not isMarubozuGreen
parabolicRiseLodBreakCond = parabolicRiseLodBreak and not parabolicRiseLodBreak[1] and not parabolicRiseLodBreak[2] and not parabolicRiseLodBreak[3] and volumeCond

//parabolic top
top1Sig = drelib.sigParabolicTop(volMa, 2, 100, 8, atr200)
top2Sig = drelib.sigParabolicTop(volMa, 3, 100, 8, atr200)
top3Sig = drelib.sigParabolicTop(volMa, 4, 100, 8, atr200)
topSig = top1Sig or top2Sig or top3Sig

//William O'Neil (WON) turnaround GO - created to signal general market early turnarounds
iWONTurnaroundExtremeAgo = input.int(defval = 45, title = "max. peak/bottom ago", minval = 20, maxval = 60, step = 5, display = display.none, group = "WON: turnaround and GO")
iWONTurnaroundGoDayMinRange = input.float(defval = 0.0, title = "min. day range", minval = 0.0, maxval = 10.0, step = 0.1, display = display.none, group = "WON: turnaround and GO", tooltip = "Use 0 for auto calculation based on adr. \nfor adr < 0.017 uses 0.017\nfor adr >= 0.017 uses 0.017 + (adr - 0.017) / 4")
iWONTurnaroundMinGoDays = input.int(defval = 3, title = "min. days", minval = 1, maxval = 10, display = display.none, group = "WON: turnaround and GO")

adr = adrPct / 100
turnaroundGoDayMinRange = iWONTurnaroundGoDayMinRange > 0.0 ? iWONTurnaroundGoDayMinRange / 100 : (adr < 0.017 ? 0.017 : 0.017 + (adr - 0.017) / 4)
wonBearGoSig = drelib.sigWONTurnaroundDn(iWONTurnaroundExtremeAgo, iWONTurnaroundMinGoDays, turnaroundGoDayMinRange, sma200, vol50Ma)

//time combination of above signals
iParabolicRiseLodBreak2WonBearGoTimeSpread = input.int(defval = 13, title = "parabolic rise LOD break -> WON Bear GO: time spread", minval = 5, maxval = 20, display = display.none, group = "Combination Signals")
parabolicRiseLodBreakAgo = ta.barssince(parabolicRiseLodBreakCond)
combiSig1 = wonBearGoSig and parabolicRiseLodBreakAgo < iParabolicRiseLodBreak2WonBearGoTimeSpread

belowSma1 = close < sma1
newBelowSma1 = belowSma1 and not belowSma1[1]
alertcondition(newBelowSma1, title = 'close below sma1', message = 'close < sma1')
if iShowCloseBelowSma1 and newBelowSma1
    label.new(bar_index, close, tooltip = 'close < sma1', color = color.new(color.orange, 70), style = label.style_circle, size = size.tiny)
//plotshape(iShowCloseBelowSma1 and newBelowSma1, title = 'close below sma1', location = location.absolute, color = color.new(color.red, 0), style = shape.triangledown, text = 'close < sma1', textcolor = color.new(color.red, 0))

belowSma2 = close < sma2
newBelowSma2 = belowSma2 and not belowSma2[1]
alertcondition(newBelowSma2, title = 'close below sma2', message = 'close < sma2')
if iShowCloseBelowSma2 and newBelowSma2
    label.new(bar_index, close, tooltip = 'close < sma2', color = color.new(color.red, 70), style = label.style_circle, size = size.tiny)
//plotshape(iShowCloseBelowSma2 and newBelowSma2, title = 'close below sma2', location = location.absolute, color = color.new(color.red, 0), style = shape.triangledown, text = 'close < sma2', textcolor = color.new(color.red, 0))

belowSma3 = close < sma3
newBelowSma3 = belowSma3 and not belowSma3[1]
alertcondition(newBelowSma3, title = 'close below sma3', message = 'close < sma3')
if iShowCloseBelowSma3 and newBelowSma3
    label.new(bar_index, close, tooltip = 'close < sma3', color = color.new(color.red, 70), style = label.style_circle, size = size.tiny)
//plotshape(iShowCloseBelowSma3 and newBelowSma3, title = 'close below sma3', location = location.absolute, color = color.new(color.red, 0), style = shape.triangledown, text = 'close < sma3', textcolor = color.new(color.red, 0))

combiSig2 = newBelowSma1 and parabolicRiseLodBreakAgo < iParabolicRiseLodBreak2WonBearGoTimeSpread
combiSig3 = newBelowSma2 and parabolicRiseLodBreakAgo < iParabolicRiseLodBreak2WonBearGoTimeSpread

alertcondition(topSig, title = 'parabolic top', message = 'top')
if iShowParabolicTop and topSig
    label.new(bar_index, open, tooltip = 'top', color = color.new(color.red, 70), style = label.style_triangledown, size = size.tiny)
//plotshape(iShowParabolicTop and topSig ? close : na, title = 'parabolic top', location = location.absolute, color = color.new(color.red, 0), style = shape.triangledown, text = 'top', textcolor = color.new(color.red, 0))

alertcondition(parabolicRiseLodBreakCond, title = 'parabolic rise lod - break', message = 'LOD break')
if iShowParabolicRiseStop and parabolicRiseLodBreakCond
    label.new(bar_index, math.min(low[1], open), tooltip = 'parabolic rise lod - break', color = color.new(color.red, 70), style = label.style_diamond, size = size.tiny)
//plotshape(iShowParabolicRiseStop and parabolicRiseLodBreakCond, title = 'parabolic rise lod - break', location = location.absolute, color = color.new(color.red, 0), style = shape.triangledown, text = 'par. rise LOD break', textcolor = color.new(color.red, 0))

alertcondition(parabolicTipTop, title = 'parabolic tip top', message = 'parabolic tip tip')
if iShowParabolicTipTop and parabolicTipTop
    label.new(bar_index, close[1], tooltip = 'parabolic tip tip', color = color.new(color.red, 35), style = label.style_xcross, size = size.tiny)

alertcondition(wonBearGoSig, title = 'WON: turnaround GO down', message = 'WON: GO down')
if iShowWONTurnaroundGo and wonBearGoSig
    label.new(bar_index, close[1], tooltip = 'WON: turnaround GO down', color = color.new(color.red, 70), style = label.style_flag, size = size.tiny)

alertcondition(combiSig1, title = 'combi sig1 (paraLodBreak + WON turnaround GO)', message = 'combi sig1')
if iShowCombiSig1 and combiSig1
    label.new(bar_index, close[1], tooltip = 'combi sig1', color = color.new(color.red, 35), style = label.style_flag, size = size.tiny)

alertcondition(combiSig2, title = 'combi sig2 (paraLodBreak + sma1)', message = 'combi sig2')
if iShowCombiSig2 and combiSig2
    label.new(bar_index, close[1], tooltip = 'combi sig2', color = color.new(color.orange, 35), style = label.style_circle, size = size.tiny)

alertcondition(combiSig3, title = 'combi sig3 (paraLodBreak + sma2)', message = 'combi sig3')
if iShowCombiSig3 and combiSig3
    label.new(bar_index, close[1], tooltip = 'combi sig3', color = color.new(color.red, 35), style = label.style_circle, size = size.tiny)

tipTopAndCombiCond = parabolicTipTop or combiSig1 or combiSig2 or combiSig3
alertcondition(tipTopAndCombiCond, title = 'when-sell - tipTop and combi', message = 'when-sell - tipTop and combi')

dttTimePct = drelib.dttTimePct()
onSessionCloseConditions = dttTimePct == 1 and (newBelowSma1 or newBelowSma2 or newBelowSma3)
allCond = parabolicTipTop or parabolicRiseLodBreakCond or topSig or onSessionCloseConditions or wonBearGoSig
alertcondition(allCond, title = 'when-sell - all sigs', message = 'when-sell')


//check performance
adrCond = 0.8 * adrPct

iShowSigPerfTable = input.bool(defval = false, title = 'show table', group = 'Sig. performnce check')
iShowOnlyGoodSigs = input.bool(defval = false, title = 'show only good sigs.', group = 'Sig. performnce check')

showRow(_iShowOnlyGoodSigs, sigOk) =>
    _iShowOnlyGoodSigs and sigOk or not _iShowOnlyGoodSigs

topSigColor = color.new(color.fuchsia, 0)
parabolicRiseLodBreakSigColor = color.new(color.maroon, 0)
tiptopSigColor = color.new(color.red, 0)

//sig stats table
float minSuccRate = 41.0
[topSuccRate, topSuccCount, topSigCount, topAvgReturn, topSuccRateOk, topSuccRateStr, topScore] = dreperf.successRateAllTimeStatsFull(topSig, topSig ? high : na, false, minSuccRate, adrCond)
[parabolicRiseLodBreakSuccRate, parabolicRiseLodBreakSuccCount, parabolicRiseLodBreakSigCount, parabolicRiseLodBreakAvgReturn, parabolicRiseLodBreakSuccRateOk, parabolicRiseLodBreakSuccRateStr, parabolicRiseLodBreakScore] = dreperf.successRateAllTimeStatsFull(parabolicRiseLodBreakCond, parabolicRiseLodBreakCond ? high : na, false, minSuccRate, adrCond)
[tiptop4SuccRate, tiptop4SuccCount, tiptop4SigCount, tiptop4AvgReturn, tiptop4SuccRateOk, tiptop4SuccRateStr, tiptop4Score] = dreperf.successRateAllTimeStatsFull(parabolic4TipTop, parabolic4TipTop ? high : na, false, minSuccRate, adrCond)
[tiptop5SuccRate, tiptop5SuccCount, tiptop5SigCount, tiptop5AvgReturn, tiptop5SuccRateOk, tiptop5SuccRateStr, tiptop5Score] = dreperf.successRateAllTimeStatsFull(parabolic5TipTop, parabolic5TipTop ? high : na, false, minSuccRate, adrCond)
[tiptop6SuccRate, tiptop6SuccCount, tiptop6SigCount, tiptop6AvgReturn, tiptop6SuccRateOk, tiptop6SuccRateStr, tiptop6Score] = dreperf.successRateAllTimeStatsFull(parabolic6TipTop, parabolic6TipTop ? high : na, false, minSuccRate, adrCond)
[sma1SuccRate, sma1SuccCount, sma1SigCount, sma1AvgReturn, sma1SuccRateOk, sma1SuccRateStr, sma1Score] = dreperf.successRateAllTimeStatsFull(belowSma1, belowSma1 ? high : na, false, minSuccRate, adrCond)
[sma2SuccRate, sma2SuccCount, sma2SigCount, sma2AvgReturn, sma2SuccRateOk, sma2SuccRateStr, sma2Score] = dreperf.successRateAllTimeStatsFull(belowSma2, belowSma2 ? high : na, false, minSuccRate, adrCond)
[sma3SuccRate, sma3SuccCount, sma3SigCount, sma3AvgReturn, sma3SuccRateOk, sma3SuccRateStr, sma3Score] = dreperf.successRateAllTimeStatsFull(belowSma3, belowSma3 ? high : na, false, minSuccRate, adrCond)
[wonGoDnSuccRate, wonGoDnSuccCount, wonGoDnSigCount, wonGoDnAvgReturn, wonGoDnSuccRateOk, wonGoDnSuccRateStr, wonGoDnScore] = dreperf.successRateAllTimeStatsFull(wonBearGoSig, wonBearGoSig ? high : na, false, minSuccRate, adrCond)
[combiSig1SuccRate, combiSig1SuccCount, combiSig1Count, combiSig1AvgReturn, combiSig1SuccRateOk, combiSig1SuccRateStr, combiSig1Score] = dreperf.successRateAllTimeStatsFull(combiSig1, combiSig1 ? high : na, false, minSuccRate, adrCond)
[combiSig2SuccRate, combiSig2SuccCount, combiSig2Count, combiSig2AvgReturn, combiSig2SuccRateOk, combiSig2SuccRateStr, combiSig2Score] = dreperf.successRateAllTimeStatsFull(combiSig2, combiSig2 ? high : na, false, minSuccRate, adrCond)
[combiSig3SuccRate, combiSig3SuccCount, combiSig3Count, combiSig3AvgReturn, combiSig3SuccRateOk, combiSig3SuccRateStr, combiSig3Score] = dreperf.successRateAllTimeStatsFull(combiSig3, combiSig3 ? high : na, false, minSuccRate, adrCond)
if barstate.islast and iShowSigPerfTable
    var tbl = table.new(position = position.top_right, columns = 2, rows = 14)
    txtSize = size.small
    table.cell(table_id = tbl, column = 0, row = 0, text = '')
    table.cell(table_id = tbl, column = 1, row = 0, text = '')
    table.cell(table_id = tbl, column = 0, row = 1, text = "sig", text_size = txtSize)
    table.cell(table_id = tbl, column = 1, row = 1, text = "perf " + str.tostring(minSuccRate, "#.# ") + str.tostring(adrCond, "#.#"), text_size = txtSize)

    if showRow(iShowOnlyGoodSigs, topSuccRateOk)
        table.cell(table_id = tbl, column = 0, row = 2, text = "top", text_color = topSigColor, text_size = txtSize)
        table.cell(table_id = tbl, column = 1, row = 2, text = topSuccRateStr, text_size = txtSize)
    if showRow(iShowOnlyGoodSigs, parabolicRiseLodBreakSuccRateOk)
        table.cell(table_id = tbl, column = 0, row = 3, text = "paraRiseLodBreak", text_color = parabolicRiseLodBreakSigColor, text_size = txtSize)
        table.cell(table_id = tbl, column = 1, row = 3, text = parabolicRiseLodBreakSuccRateStr, text_size = txtSize)
    if showRow(iShowOnlyGoodSigs, tiptop4SuccRateOk)
        table.cell(table_id = tbl, column = 0, row = 4, text = "tip-top4", text_color = tiptopSigColor, text_size = txtSize)
        table.cell(table_id = tbl, column = 1, row = 4, text = tiptop4SuccRateStr, text_size = txtSize)
    if showRow(iShowOnlyGoodSigs, tiptop5SuccRateOk)
        table.cell(table_id = tbl, column = 0, row = 5, text = "tip-top5", text_color = tiptopSigColor, text_size = txtSize)
        table.cell(table_id = tbl, column = 1, row = 5, text = tiptop5SuccRateStr, text_size = txtSize)
    if showRow(iShowOnlyGoodSigs, tiptop6SuccRateOk)
        table.cell(table_id = tbl, column = 0, row = 6, text = "tip-top6", text_color = tiptopSigColor, text_size = txtSize)
        table.cell(table_id = tbl, column = 1, row = 6, text = tiptop6SuccRateStr, text_size = txtSize)
    if showRow(iShowOnlyGoodSigs, sma1SuccRateOk)
        table.cell(table_id = tbl, column = 0, row = 7, text = "sma10", text_color = color.orange, text_size = txtSize)
        table.cell(table_id = tbl, column = 1, row = 7, text = sma1SuccRateStr, text_size = txtSize)
    if showRow(iShowOnlyGoodSigs, sma2SuccRateOk)
        table.cell(table_id = tbl, column = 0, row = 8, text = "sma20", text_color = color.red, text_size = txtSize)
        table.cell(table_id = tbl, column = 1, row = 8, text = sma2SuccRateStr, text_size = txtSize)
    if showRow(iShowOnlyGoodSigs, sma3SuccRateOk)
        table.cell(table_id = tbl, column = 0, row = 9, text = "sma50", text_color = color.red, text_size = txtSize)
        table.cell(table_id = tbl, column = 1, row = 9, text = sma3SuccRateStr, text_size = txtSize)
    if showRow(iShowOnlyGoodSigs, wonGoDnSuccRateOk)
        table.cell(table_id = tbl, column = 0, row = 10, text = "WON GO dn", text_color = color.purple, text_size = txtSize)
        table.cell(table_id = tbl, column = 1, row = 10, text = wonGoDnSuccRateStr, text_size = txtSize)
    if showRow(iShowOnlyGoodSigs, combiSig1SuccRateOk)
        table.cell(table_id = tbl, column = 0, row = 11, text = "combi sig1", text_color = tiptopSigColor, text_size = txtSize)
        table.cell(table_id = tbl, column = 1, row = 11, text = combiSig1SuccRateStr, text_size = txtSize)
    if showRow(iShowOnlyGoodSigs, combiSig2SuccRateOk)
        table.cell(table_id = tbl, column = 0, row = 12, text = "combi sig2", text_color = color.orange, text_size = txtSize)
        table.cell(table_id = tbl, column = 1, row = 12, text = combiSig2SuccRateStr, text_size = txtSize)
    if showRow(iShowOnlyGoodSigs, combiSig3SuccRateOk)
        table.cell(table_id = tbl, column = 0, row = 13, text = "combi sig3", text_color = color.red, text_size = txtSize)
        table.cell(table_id = tbl, column = 1, row = 13, text = combiSig3SuccRateStr, text_size = txtSize)