// This Pine Script™ code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © drebel

//@version=6
indicator(title = 'DRE parabolic top', overlay = true, max_bars_back = 2200, calc_bars_count = 12 * 252)

import drebel/DRELib/39 as drelib
import drebel/DREPerf/27 as dreperf

//general filters inputs
iTurnoverCond = input.bool(defval = true, title = 'Min. Turnover for signal [M]', display = display.none, group = 'General filter for signal', inline = 'trn')
iMinTurnover = input.float(defval = 0.15, title = '', minval = 0, display = display.none, group = 'General filter for signal', inline = 'trn')
iAdrCond = input.bool(defval = true, title = 'Min. ADR% for signal', display = display.none, group = 'General filter for signal', inline = 'adr')
iMinAdr = input.float(defval = 2.6, title = '', minval = 0, step = 0.2, display = display.none, group = 'General filter for signal', inline = 'adr')

//signals switches
iParabolicTop = input.bool(defval = true, title = 'Show parabolic top', display = display.none, group = 'Signals')
iJunior = input.bool(defval = true, title = 'Show junior', display = display.none, group = 'Signals', inline = 'junior')
iJunior2 = input.bool(defval = true, title = '2', display = display.none, group = 'Signals', inline = 'junior')
iJunior3 = input.bool(defval = true, title = 'late', display = display.none, group = 'Signals', inline = 'junior')
iCoil = input.bool(defval = true, title = 'Show coil', display = display.none, group = 'Signals', inline = 'coil')
iCoilStrech = input.bool(defval = true, title = 'strech', display = display.none, group = 'Signals', inline = 'coil')
iBullishStarter = input.bool(defval = true, title = 'Show starter', display = display.none, group = 'Signals', inline = 'starter')
iBearishStarter = input.bool(defval = true, title = 'bear', display = display.none, group = 'Signals', inline = 'starter')
iBullishFireStarter = input.bool(defval = true, title = 'fire', display = display.none, group = 'Signals', inline = 'starter')
iLonger = input.bool(defval = true, title = 'Show longer', display = display.none, group = 'Signals')
iBullishZscore = input.bool(defval = true, title = 'Show bubble', display = display.none, group = 'Signals', inline = 'bubble')
iBearishZscore = input.bool(defval = true, title = 'bear', display = display.none, group = 'Signals', inline = 'bubble')
iBullishHunter = input.bool(defval = true, title = 'Show hunter', display = display.none, group = 'Signals', inline = 'hunter')
iBearishHunter = input.bool(defval = true, title = 'bear', display = display.none, group = 'Signals', inline = 'hunter')
iBullishStepper = input.bool(defval = true, title = 'Show stepper', display = display.none, group = 'Signals', inline = 'stepper')
iBullishLongerStepper = input.bool(defval = true, title = 'longer', display = display.none, group = 'Signals', inline = 'stepper')
iBullishObv = input.bool(defval = true, title = 'Show obv', display = display.none, group = 'Signals', inline = 'obv')
iBearishObv = input.bool(defval = true, title = 'bear', display = display.none, group = 'Signals', inline = 'obv')
iBullishRmv = input.bool(defval = true, title = 'Show rmv', display = display.none, group = 'Signals', inline = 'rmv')
iBearishRmv = input.bool(defval = true, title = 'bear', display = display.none, group = 'Signals', inline = 'rmv')
iBullishRmvPb = input.bool(defval = true, title = 'bull pb', display = display.none, group = 'Signals', inline = 'rmvpb')
iBearishRmvPb = input.bool(defval = true, title = 'bear pb', display = display.none, group = 'Signals', inline = 'rmvpb')
iBullishMtb = input.bool(defval = true, title = 'Show mtb', display = display.none, group = 'Signals')
iTurnaroundGo = input.bool(defval = true, title = "Show O'Neail big index turnaround GO", display = display.none, group = 'Signals')

iSigCheckTime = input.int(defval = 30, title = 'Signal check time [candles]', minval = 5, maxval = 200, display = display.none, group = 'Signals')
iMinSigSuccessRate = input.float(defval = 46.0, title = 'Min. sig success rate pct.', minval = 0.0, maxval = 100.0, step = 1.0, display = display.none, group = 'Signals')
iMinSigReturnAdrMultiple = input.float(defval = 1.2, title = 'Min. avg. return by ADR multiple', minval = -1.0, maxval = 5.0, step = 0.05, display = display.none, group = 'Signals')

//common parameters
iMainMaLength = input.int(defval = 200, title = 'Main MA length', minval = 50, maxval = 500, display = display.none, group = 'Common parameters')
iShortMaLength = input.int(defval = 50, title = 'Short MA length', minval = 10, maxval = 200, display = display.none, group = 'Common parameters')
iLongMaLength = input.int(defval = 750, title = 'Long MA length', minval = 200, maxval = 1000, display = display.none, group = 'Common parameters')
iVShortMaLength1 = input.int(defval = 10, title = 'Very short MA length', minval = 5, maxval = 50, display = display.none, group = 'Common parameters')
iVShortMaLength2 = input.int(defval = 21, title = 'Very short MA length2', minval = 8, maxval = 50, display = display.none, group = 'Common parameters')

//common calculations
mainAtr = ta.atr(iMainMaLength)
mainMa = ta.sma(close, iMainMaLength)
shortMa = ta.sma(close, iShortMaLength)
longMa = ta.sma(close, iLongMaLength)
gVShortMa1 = ta.ema(close, iVShortMaLength1)
gVShortMa2 = ta.ema(close, iVShortMaLength2)
gVolMa = ta.sma(volume, 30)
adrPct = 100.0 * (ta.sma(high / low, 30) - 1)

//filters calculations (min. iShortMaLength candles)
gTurnoverMa = ta.sma(close * volume, iShortMaLength) / 1000000.0
gTurnoverMedian = ta.median(close * volume, iShortMaLength) / 1000000.0
gTurnoverCond = not iTurnoverCond or iTurnoverCond and gTurnoverMa > iMinTurnover and gTurnoverMedian > iMinTurnover
gAdr = 100 * (ta.sma(high / low, iShortMaLength) - 1)
gAdrCond = not iAdrCond or iAdrCond and gAdr > iMinAdr
gFilter = gTurnoverCond and gAdrCond

//Signal: Parabolic top
iParTopAtrMulti = input.int(defval = 8, title = 'ATR Multiple Since Low', minval = 2, maxval = 30, display = display.none, group = 'Signal: Parabolic top')
iParTopGainDays = input.int(defval = 100, title = 'Number Of Days To top', minval = 5, maxval = 150, step = 5, display = display.none, group = 'Signal: Parabolic top')
iDownDays1 = input.bool(defval = true, title = 'Down Days After Top 1', display = display.none, group = 'Signal: Parabolic top', inline = 'top1')
iDownDaysAfterTop1 = input.int(defval = 2, title = '', minval = 1, maxval = 8, display = display.none, group = 'Signal: Parabolic top', inline = 'top1')
iDownDays2 = input.bool(defval = true, title = 'Down Days After Top 2', display = display.none, group = 'Signal: Parabolic top', inline = 'top2')
iDownDaysAfterTop2 = input.int(defval = 3, title = '', minval = 1, maxval = 8, display = display.none, group = 'Signal: Parabolic top', inline = 'top2')
iDownDays3 = input.bool(defval = true, title = 'Down Days After Top 3', display = display.none, group = 'Signal: Parabolic top', inline = 'top3')
iDownDaysAfterTop3 = input.int(defval = 4, title = '', minval = 1, maxval = 8, display = display.none, group = 'Signal: Parabolic top', inline = 'top3')

top1Sig = drelib.sigParabolicTop(gVolMa, iDownDaysAfterTop1, iParTopGainDays, iParTopAtrMulti, mainAtr) and iDownDays1
top2Sig = drelib.sigParabolicTop(gVolMa, iDownDaysAfterTop2, iParTopGainDays, iParTopAtrMulti, mainAtr) and iDownDays2
top3Sig = drelib.sigParabolicTop(gVolMa, iDownDaysAfterTop3, iParTopGainDays, iParTopAtrMulti, mainAtr) and iDownDays3

//Signal: Junior
func_init_vwap_excl_init_higher_volume() =>
    x = 0.5
    reset = bar_index == 0 or bar_index == 1 and volume < x * volume[1] or bar_index == 2 and volume < x * volume[1] and volume[1] < x * volume[2]
    ret = ta.vwap(ohlc4, reset)
    ret

func_sig_junior_late(_minAge) =>
    initVwap = func_init_vwap_excl_init_higher_volume()
    ret = bar_index >= _minAge and drelib.crossover(initVwap)
    ret

juniorSig = drelib.sigJunior(iLongMaLength)
juniorLateSig = func_sig_junior_late(iLongMaLength)

freshStock = bar_index < iLongMaLength
bars = int(math.min(bar_index > 1 ? bar_index * 0.8 : 1, iLongMaLength))
initialHigh = ta.highest(bars)
isHighestSinceIpo = high == initialHigh
initialHighBarsAgo = ta.barssince(isHighestSinceIpo)
initHighVwap = ta.vwap(ohlc4, freshStock and isHighestSinceIpo)
bars2 = bar_index > 15 ? bar_index - 7 : bar_index * 0.2
junior2Sig = initialHighBarsAgo > bars2 and drelib.candle_crossover(initHighVwap)

// junior3Sig = freshStock and initialHighBarsAgo > bars2 and drelib.candle_crossover(initialHigh[1])
// alertcondition(junior3Sig, title = 'DRE junior3 sig', message = 'junior3')
// plotshape(junior3Sig and iJunior3, title = 'junior3', location = location.belowbar, color = color.new(color.green, 0), style = shape.triangleup, text = 'junior3', textcolor = color.new(color.green, 0))

//Signal: Coil_n_strech
iCoilPercent = input.int(defval = 2, title = 'Percentile rank distance from MAs', minval = 1, maxval = 20, display = display.none, group = 'Signal: Coil_n_strech')

func_ma_distance(_shortMaLen, _mediumMaLen, _longMaLen) =>
    ma1 = ta.sma(close, _shortMaLen)
    ma2 = ta.sma(close, _mediumMaLen)
    ma3 = ta.sma(close, _longMaLen)
    zeroBarVwap = ta.vwap(ohlc4, bar_index == 0)
    usedLongMaLen = bar_index < _longMaLen ? bar_index : _longMaLen
    ma3used = bar_index < _longMaLen ? zeroBarVwap : ma3
    lenSum = _shortMaLen + _mediumMaLen + usedLongMaLen
    distance = math.sqrt((lenSum - _shortMaLen) * math.pow(ma1 - close, 2) + (lenSum - _mediumMaLen) * math.pow(ma2 - close, 2) + (lenSum - usedLongMaLen) * math.pow(ma3used - close, 2))
    distance

func_sig_coil(_dist, _longMaLen, _mediumMaLen, _distPercentRank) =>
    percentRankLen = bar_index < 1 ? 1 : math.min(bar_index, 3 * _longMaLen)
    mediumMa = ta.sma(close, _mediumMaLen)
    ret = ta.percentrank(_dist, percentRankLen) < _distPercentRank and drelib.crossover(mediumMa)
    ret

func_sig_strech(_dist, _longMaLen, _distPercentRank) =>
    percentRankLen = bar_index < 1 ? 1 : math.min(bar_index, 3 * _longMaLen)
    ret = ta.percentrank(_dist, percentRankLen) > 100 - _distPercentRank and close > close[_longMaLen] and close > close[1]
    ret

coilBullishSig = func_sig_coil(func_ma_distance(iShortMaLength, iMainMaLength, iLongMaLength), iLongMaLength, iMainMaLength, iCoilPercent)
strechBearishSig = func_sig_strech(func_ma_distance(iShortMaLength, iMainMaLength, iLongMaLength), iLongMaLength, iCoilPercent)

//Signal: Starter
iStarterMinDecliningDays = input.int(defval = 200, title = 'Number of SMA declining days', minval = 20, maxval = 1000, display = display.none, group = 'Signal: Starter')
iStarterMaxIncliningDays = input.int(defval = 200, title = 'Number of SMA inclining day', minval = 0, maxval = 300, display = display.none, group = 'Signal: Starter')
iStarterSmaSmoothing = input.int(defval = 3, title = 'SMA smoothing', minval = 0, maxval = 10, display = display.none, group = 'Signal: Starter')
iFireStarterMaDiffAtrMultiple = input.float(defval = 1, title = 'Fire starter MA difference ATR multiple', minval = 0.5, maxval = 10, step = 0.5, display = display.none, group = 'Signal: Starter')

bullishStarterSig = drelib.sigStarter(true, iMainMaLength, iStarterMinDecliningDays, iStarterMaxIncliningDays, iStarterSmaSmoothing)
bearishStarterSig = drelib.sigStarter(false, iMainMaLength, iStarterMinDecliningDays, iStarterMaxIncliningDays, iStarterSmaSmoothing)
bullishFireStarterSig = drelib.sigFireStarter(iMainMaLength, iStarterMinDecliningDays, iFireStarterMaDiffAtrMultiple, iStarterSmaSmoothing, mainAtr)

//Signal: Longer
iLongerOffset = input.float(defval = 0.1, title = 'Price offset (atr multiple)', minval = -2.0, maxval = 2.0, step = 0.5, display = display.none, group = 'Signal: Longer')

longerSig = drelib.sigLonger(mainMa, longMa, 0, mainAtr)
smallerLongerSig = drelib.sigLonger(shortMa, mainMa, 0, mainAtr)

//Signal: Bubble
iZScore2ndMaLength = input.int(21, 'Z-Score 2nd MA Length (short)', minval = 3, maxval = 21, display = display.none, group = 'Signal: Bubble')
iZScore2ndMaMinScore = input.float(2.3, 'Min. zScore', minval = 1.0, maxval = 14, step = 0.1, display = display.none, group = 'Signal: Bubble')

zscoreVolCond = ta.ema(drelib.z_score(volume, iMainMaLength), iZScore2ndMaLength) >= iZScore2ndMaMinScore
zscoreEma = ta.ema(close, 2 * iZScore2ndMaLength / 3)
zscoreBullishSig = zscoreVolCond and zscoreEma > zscoreEma[1]
zscoreBearishSig = zscoreVolCond and zscoreEma < zscoreEma[1]

//Signal: Hunter
iHunterGracePeriod = input.int(defval = 40, title = 'grace period', minval = 20, maxval = 200, display = display.none, group = 'Signal: Hunter')
iHunterShort = input.bool(defval = true, title = 'short', display = display.none, group = 'Signal: Hunter', inline = 'hunter2')
iHunterLookbackShort = input.int(defval = 250, title = 'lookback', minval = 50, maxval = 1000, display = display.none, group = 'Signal: Hunter', inline = 'hunter2')
iHunterMid = input.bool(defval = true, title = 'mid', display = display.none, group = 'Signal: Hunter', inline = 'hunter3')
iHunterLookbackMid = input.int(defval = 700, title = 'lookback', minval = 100, maxval = 1500, display = display.none, group = 'Signal: Hunter', inline = 'hunter3')
iHunterLong = input.bool(defval = true, title = 'long', display = display.none, group = 'Signal: Hunter', inline = 'hunter4')
iHunterLookbackLong = input.int(defval = 1300, title = 'lookback', minval = 200, maxval = 2000, display = display.none, group = 'Signal: Hunter', inline = 'hunter4')

bullishHunterShortSig = drelib.sigBullSLHunter(mainAtr, iHunterLookbackShort, iHunterGracePeriod) and iHunterShort
bullishHunterMidSig = drelib.sigBullSLHunter(mainAtr, iHunterLookbackMid, iHunterGracePeriod) and iHunterMid
bullishHunterLongSig = drelib.sigBullSLHunter(mainAtr, iHunterLookbackLong, iHunterGracePeriod) and iHunterLong
bullishHunterSig = bullishHunterShortSig or bullishHunterMidSig or bullishHunterLongSig

bearishHunterShortSig = drelib.sigBearSLHunter(mainAtr, iHunterLookbackShort, iHunterGracePeriod) and iHunterShort 
bearishHunterMidSig = drelib.sigBearSLHunter(mainAtr, iHunterLookbackMid, iHunterGracePeriod) and iHunterMid
bearishHunterLongSig = drelib.sigBearSLHunter(mainAtr, iHunterLookbackLong, iHunterGracePeriod) and iHunterLong
bearishHunterSig = bearishHunterShortSig or bearishHunterMidSig or bearishHunterLongSig

//Signal: Stepper
iStepperLookback = input.int(defval = 325, title = 'lookback', minval = 100, maxval = 750, step = 5, display = display.none, group = 'Signal: Stepper')
iStepperMaDist = input.float(defval = 1.25, title = 'max vwap-ma dist.', minval = 0.0, maxval = 5.0, step = 0.25, display = display.none, group = 'Signal: Stepper')
iLongerStepperDist = input.int(defval = 5, title = 'longer-stepper max. distance', minval = 0, maxval = 20, display = display.none, group = 'Signal: Stepper')

bullishStepperSig = drelib.sigBullStepper(mainAtr, mainMa, iStepperLookback, iStepperMaDist)
bullishLongerStepperSig = ta.barssince(longerSig) <= iLongerStepperDist and bullishStepperSig
bullishSLongerStepperSig = ta.barssince(smallerLongerSig) <= 3 and bullishStepperSig

//Signal: Obv
iObvMaLength = input.int(defval=100, title='Ma len.', minval=10, maxval=250, display = display.none, group='Signal: Obv')
iObvSource = input.source(close, title = 'Source', display = display.none, group = 'Signal: Obv')
iObvStdDevBand = input.float(defval = 0.35, title = 'StdDev.', minval = 0, maxval = 10.0, step = 0.05, display = display.none, group = 'Signal: Obv')

func_obv(_source) =>
    ta.cum(math.sign(ta.change(_source)) * volume)

var cumVol = 0.
cumVol += nz(volume)
if barstate.islast and cumVol == 0
    runtime.error("No volume is provided by the data vendor.")

obv = func_obv(iObvSource)
obcMa = ta.sma(obv, iObvMaLength)
obvStdDev = ta.stdev(obv, iObvMaLength)
bullishObvCross = drelib.crossover2(obv, obcMa + iObvStdDevBand * obvStdDev)
bearishObvCross = drelib.crossunder2(obv, obcMa - iObvStdDevBand * obvStdDev)
bullishObvCrossSince = ta.barssince(bullishObvCross)
bearishObvCrossSince = ta.barssince(bearishObvCross)
bullishObvSig = bullishObvCross and bullishObvCrossSince[1] > bearishObvCrossSince[1]
bearishObvSig = bearishObvCross and bullishObvCrossSince[1] < bearishObvCrossSince[1]

//Signal: Rmv
iRmvLookbackPeriod = input.int(30, minval = 1, title = 'Lookback Period', display = display.none, group = 'Signal: Rmv')
iRmvShortLookback1 = input.int(13, minval = 1, title = 'Short-term ATR Lookback 1', display = display.none, group = 'Signal: Rmv')
iRmvShortLookback2 = input.int(8, minval = 1, title = 'Short-term ATR Lookback 2', display = display.none, group = 'Signal: Rmv')
iRmvshortLookback3 = input.int(5, minval = 1, title = 'Short-term ATR Lookback 3', display = display.none, group = 'Signal: Rmv')
iRmvLowLevel = input.int(25, title = 'Low Level Threshold', display = display.none, group = 'Signal: Rmv')
iRmvPbLen = input.int(11, title = 'Pullback Len.', display = display.none, group = 'Signal: Rmv')

func_rmv(_artShortLen1, _artShortLen2, _artShortLen3, _MainLookback) =>
    shortAtrAvg = (ta.atr(_artShortLen1) + ta.atr(_artShortLen2) + ta.atr(_artShortLen3)) / 3
    highestShortAvg = ta.highest(shortAtrAvg, _MainLookback)
    lowestShortAvg = ta.lowest(shortAtrAvg, _MainLookback)
    result = (shortAtrAvg - lowestShortAvg) / math.max(highestShortAvg - lowestShortAvg, 0.001) * 100
    result

rmv = func_rmv(iRmvShortLookback1, iRmvShortLookback2, iRmvshortLookback3, iRmvLookbackPeriod)
lowRmv = rmv <= iRmvLowLevel
highRmv = rmv >= 100 - iRmvLowLevel / 2
earnings = request.earnings(ticker = syminfo.tickerid, field = earnings.actual)
earningsSig = earnings != earnings[1]

rmvCond = lowRmv[1] and not lowRmv or highRmv and lowRmv[2] or rmv == 100 and lowRmv[3]
bullishRmvSig = rmvCond and close > close[2] and volume > gVolMa and close > gVShortMa1 and close > gVShortMa2 and close > shortMa
bullishRmvPbAgo = ta.barssince(bullishRmvSig)
bullishRmvPbSig = not bullishRmvSig and bullishRmvPbAgo <= iRmvPbLen and drelib.crossover(low[bullishRmvPbAgo])
bearishRmvSig = rmvCond and close < close[2] and volume > gVolMa and close < gVShortMa1 and close < gVShortMa2 and close < shortMa
bearishRmvPbAgo = ta.barssince(bearishRmvSig)
bearishRmvPbSig = not bearishRmvSig and bearishRmvPbAgo <= iRmvPbLen and drelib.crossunder(high[bearishRmvPbAgo])

//plotshape(bullishRmvSig and iBullishRmv, title = 'bullish rmv', location = location.belowbar, color = color.new(color.green, 0), style = shape.triangleup, text = 'rmv', textcolor = color.new(color.green, 0))
//plotshape(bullishRmvPbSig and iBullishRmvPb, title = 'bullish rmv-pb', location = location.belowbar, color = color.new(color.green, 0), style = shape.triangleup, text = 'rmv-pb', textcolor = color.new(color.green, 0))
//plotshape(bullishRmvEarningsSig and iBullishRmvEarnings, title = 'bullish rmv-e', location = location.belowbar, color = color.new(color.green, 0), style = shape.triangleup, text = 'rmv-e', textcolor = color.new(color.green, 0))
//plotshape(bullishRmvEarningsPbSig and iBullishRmvEarningsPb, title = 'bullish rmv-e-pb', location = location.belowbar, color = color.new(color.green, 0), style = shape.triangleup, text = 'rmv-e-pb', textcolor = color.new(color.green, 0))
//plotshape(bearishRmvSig and iBearishRmv, title = 'bearish rmv', location=location.abovebar, color = color.new(color.red, 0), style = shape.triangledown, text = 'rmv', textcolor = color.new(color.red, 0))
//plotshape(bearishRmvPbSig and iBearishRmvPb, title = 'bearish rmv-pb', location=location.abovebar, color = color.new(color.red, 0), style = shape.triangledown, text = 'rmv-pb', textcolor = color.new(color.red, 0))
//plotshape(bearishRmvEarningsSig and iBearishRmvEarnings, title = 'bearish rmv-e', location=location.abovebar, color = color.new(color.red, 0), style = shape.triangledown, text = 'rmv-e', textcolor = color.new(color.red, 0))
//plotshape(bearishRmvEarningsPbSig and iBearishRmvEarningsPb, title = 'bearish rmv-e-pb', location=location.abovebar, color = color.new(color.red, 0), style = shape.triangledown, text = 'rmv-e-pb', textcolor = color.new(color.red, 0))

//Signal: Mtb (Minevrini + Trigger Bar / Shakeout Demand Tail / Gap Down Reversal)
iMaxDistFromMaPctRank = input.int(defval = 10, title = 'Max. distance from MA', minval = 1, maxval = 99, display = display.none, group = 'Signal: Mtb')
iTriggerBarMaxPercentile = input.int(defval = 30, title = 'Trigger Bar max. percentiles', minval = 1, maxval = 99, display = display.none, group = 'Signal: Mtb')

sma50 = ta.sma(close, 50)
sma150 = ta.sma(close, 150)
sma200 = ta.sma(close, 200)
yearlyHigh = ta.highest(252)
yearlyLow = ta.lowest(252)
// shares = request.financial(syminfo.tickerid, "TOTAL_SHARES_OUTSTANDING", "FQ") // max 30M shares

//Minevrini trend
sma200GoingUp_10 = sma200 > sma200[1] ? 1 : 0
sma200GoingUpCond = math.sum(sma200GoingUp_10, 60) > 30
maCond = close > sma150 and close > sma200 and sma50 > sma150 and sma150 > sma200 and sma200 > sma200[1]
loHiCond = close > 1.25 * yearlyLow and close > yearlyHigh / 1.25
sma50Cond = close > sma50 / 1.08
 // and RS Score > 70
benchmark = request.security("SPY", timeframe.period, close)
simpleRelativeStrengthCond = close / benchmark > close[126] / benchmark[126] and close / benchmark > close[63] / benchmark[63]
minevriniTrendCond = maCond and loHiCond and sma50Cond and sma200GoingUpCond and simpleRelativeStrengthCond

//Jack Corsellis - Trigger Bar
candleHeight = high - low
candleHeightPrctRank = ta.percentrank(candleHeight, 50)
latestHigh = math.max(nz(math.abs(ta.highestbars(50)), 1), 50)
volumePrctRank = ta.percentrank(volume, latestHigh)
shortMaDistPrctRank = ta.percentrank(math.abs(ohlc4 - shortMa), 50)
maDistCond = shortMaDistPrctRank < iMaxDistFromMaPctRank
triggerBarCond = candleHeightPrctRank < iTriggerBarMaxPercentile and volumePrctRank < iTriggerBarMaxPercentile and maDistCond
bodySize = math.abs((open - close) / (high - low))
lowerWickSize = math.abs((low - math.min(open, close)) / (high - low))
hammerCandle = bodySize < 0.2 and lowerWickSize > 0.7
shakeoutDemandTailCond = hammerCandle and candleHeightPrctRank > 50 and volumePrctRank > 50 and maDistCond
gapDownReversalCandle = close[1] < open[1] and open < close[1] and close > close[1] and bodySize > bodySize[1]
gapDownReversalCond = gapDownReversalCandle and candleHeightPrctRank > 50 and volumePrctRank > 50 and maDistCond

mtbSig = ta.barssince(minevriniTrendCond) < 15 and (triggerBarCond or shakeoutDemandTailCond and gapDownReversalCond)

//Signal: Price-vol. correlation
iPcvMinCorrelation = input.float(defval = 0.75, title = 'PCV - min. correlation', minval = -1.0, maxval = 1.0, step = 0.05, display = display.none, group = 'Signal: Price-vol. correlation')
priceMa = ta.ema(close, 50)
volumeMa = ta.ema(volume, 50)
pvCorrelation = ta.correlation(priceMa, volumeMa, 50)
pvc = priceMa > priceMa[1] and pvCorrelation > iPcvMinCorrelation
pvc2 = pvc and gVShortMa1 > gVShortMa2 and close > shortMa

//Signal: Breakout
iBoVolumeMultiple = input.float(defval = 2.0, title = 'Breakout volume multiple', minval = 0.0, maxval = 5.0, step = 0.1, display = display.none, group = 'Signal: Breakout')
iBoMaxRiskPct = input.float(defval = 7.0, title = 'Breakout max risk', minval = 0.0, maxval = 12.0, step = 0.5, display = display.none, group = 'Signal: Breakout')

currCandleRelativeVol(int _iMaLength) =>
    candleVolPart = volume / ta.sma(volume, _iMaLength)
    candleTimePart = (math.min(timenow, time_close) - time) / (time_close - time)
    relativeVol = candleVolPart / candleTimePart
    relativeVol

candleRelativeVol = currCandleRelativeVol(iShortMaLength)
bullishRisk = 100 * (close / low[1] - 1)
bearisjRisk = 100 * (close / high[1] - 1)
candleBullishBoOnVolumeCond = close > high[1] and candleRelativeVol > iBoVolumeMultiple and bullishRisk < iBoMaxRiskPct
candleBearishBoOnVolumeCond = close < low[1] and candleRelativeVol > iBoVolumeMultiple and bearisjRisk < iBoMaxRiskPct

//Signal: O'Neil turnaround and GO
iTurnaroundExtremeAgo = input.int(defval = 45, title = "max. peak/bottom ago", minval = 20, maxval = 60, step = 5, display = display.none, group = "Signal: O'Neil turnaround and GO")
iturnaroundGoDayMinRange = input.float(defval = 0.0, title = "min. day range", minval = 0.0, maxval = 10.0, step = 0.1, display = display.none, group = "Signal: O'Neil turnaround and GO", tooltip = "Use 0 for auto calculation based on adr. \nfor adr < 0.017 uses 0.017\nfor adr >= 0.017 uses 0.017 + (adr - 0.017) / 4")
iTurnaroundMinGoDays = input.int(defval = 3, title = "min. days", minval = 1, maxval = 10, display = display.none, group = "Signal: O'Neil turnaround and GO")

vol50sma = ta.sma(volume, 50)

adr = adrPct / 100
turnaroundGoDayMinRange = iturnaroundGoDayMinRange > 0.0 ? iturnaroundGoDayMinRange / 100 : (adr < 0.017 ? 0.017 : 0.017 + (adr - 0.017) / 4)

//signals aggregate
bullishRmvSigs = bullishRmvSig or bullishRmvPbSig
bearishRmvSigs = bearishRmvSig or bearishRmvPbSig
bullishSig = juniorSig or bullishStarterSig or bullishFireStarterSig or bullishHunterSig or longerSig or bullishStepperSig or bullishLongerStepperSig or bullishObvSig or bullishRmvSigs or mtbSig
bearishSig = bearishStarterSig or bearishHunterSig or bearishObvSig or bearishRmvSigs

//check performance
iShowSigPerfTable = input.bool(defval = false, title = 'show table', display = display.none, group = 'Sig. performance check')
iShowOnlyGoodSigs = input.bool(defval = true, title = 'show only good sigs.', display = display.none, group = 'Sig. performance check')
iUseQualityGate = input.bool(defval = false, title = 'use extended quality gate', display = display.none, group = 'Sig. performance check')
iMinSigCount = input.int(defval = 30, title = 'min. signals count', minval = 0, display = display.none, group = 'Sig. performance check')
iMinSigWilsonLb = input.float(defval = 30.0, title = 'min. win-rate lower bound (Wilson) [pct]', minval = 0.0, maxval = 100.0, step = 1.0, display = display.none, group = 'Sig. performance check')
iGoSigsExtremeLen = input.int(defval = 2, title = 'lowest, highest len. for GO sigs.', display = display.none, group = 'Sig. performance check')
// iShowSigPerfPlots = input.bool(defval = false, title = 'show plots', display = display.none, group = 'Sig. performnce check')

showRow(_iShowOnlyGoodSigs, sigOk) =>
    _iShowOnlyGoodSigs and sigOk or not _iShowOnlyGoodSigs

showRow(_iShowOnlyGoodSigs, sigOk, _showThisSig) =>
    _showThisSig and (_iShowOnlyGoodSigs and sigOk or not _iShowOnlyGoodSigs)

highestFew = ta.highest(iGoSigsExtremeLen)

adrCond = iMinSigReturnAdrMultiple * adrPct

[juniorSuccRate, juniorSuccCount, juniorSigCount, juniorAvgReturn, juniorSuccRateOk, juniorSuccRateStr, juniorWinRate, juniorWinCount, juniorAvgR, juniorMedR, juniorStdR, juniorPf, juniorWilsonLb, juniorAvgMfe, juniorAvgMae, juniorMaxDd, juniorMaxLossStreak, juniorScore, juniorQualityOk, juniorSumWinR, juniorSumLossR] = dreperf.signalQualityFull(juniorSig, juniorSig ? low : na, true, iMinSigSuccessRate, adrCond, iSigCheckTime, iMinSigCount, iMinSigWilsonLb)
[junior2SuccRate, junior2SuccCount, junior2SigCount, junior2AvgReturn, junior2SuccRateOk, junior2SuccRateStr, junior2WinRate, junior2WinCount, junior2AvgR, junior2MedR, junior2StdR, junior2Pf, junior2WilsonLb, junior2AvgMfe, junior2AvgMae, junior2MaxDd, junior2MaxLossStreak, junior2Score, junior2QualityOk, junior2SumWinR, junior2SumLossR] = dreperf.signalQualityFull(junior2Sig, junior2Sig ? low : na, true, iMinSigSuccessRate, adrCond, iSigCheckTime, iMinSigCount, iMinSigWilsonLb)
[juniorLateSuccRate, juniorLateSuccCount, juniorLateSigCount, juniorLateAvgReturn, juniorLateSuccRateOk, juniorLateSuccRateStr, juniorLateWinRate, juniorLateWinCount, juniorLateAvgR, juniorLateMedR, juniorLateStdR, juniorLatePf, juniorLateWilsonLb, juniorLateAvgMfe, juniorLateAvgMae, juniorLateMaxDd, juniorLateMaxLossStreak, juniorLateScore, juniorLateQualityOk, juniorLateSumWinR, juniorLateSumLossR] = dreperf.signalQualityFull(juniorLateSig, juniorLateSig ? low : na, true, iMinSigSuccessRate, adrCond, iSigCheckTime, iMinSigCount, iMinSigWilsonLb)
[coilBullishSuccRate, coilBullishSuccCount, coilBullishSigCount, coilBullishAvgReturn, coilBullishSuccRateOk, coilBullishSuccRateStr, coilBullishWinRate, coilBullishWinCount, coilBullishAvgR, coilBullishMedR, coilBullishStdR, coilBullishPf, coilBullishWilsonLb, coilBullishAvgMfe, coilBullishAvgMae, coilBullishMaxDd, coilBullishMaxLossStreak, coilBullishScore, coilBullishQualityOk, coilBullishSumWinR, coilBullishSumLossR] = dreperf.signalQualityFull(coilBullishSig, coilBullishSig ? low : na, true, iMinSigSuccessRate, adrCond, iSigCheckTime, iMinSigCount, iMinSigWilsonLb)
[strechBearishSuccRate, strechBearishSuccCount, strechBearishSigCount, strechBearishAvgReturn, strechBearishSuccRateOk, strechBearishSuccRateStr, strechBearishWinRate, strechBearishWinCount, strechBearishAvgR, strechBearishMedR, strechBearishStdR, strechBearishPf, strechBearishWilsonLb, strechBearishAvgMfe, strechBearishAvgMae, strechBearishMaxDd, strechBearishMaxLossStreak, strechBearishScore, strechBearishQualityOk, strechBearishSumWinR, strechBearishSumLossR] = dreperf.signalQualityFull(strechBearishSig, strechBearishSig ? high : na, false, iMinSigSuccessRate, adrCond, iSigCheckTime, iMinSigCount, iMinSigWilsonLb)
[bullishStarterSuccRate, bullishStarterSuccCount, bullishStarterSigCount, bullishStarterAvgReturn, bullishStarterSuccRateOk, bullishStarterSuccRateStr, bullishStarterWinRate, bullishStarterWinCount, bullishStarterAvgR, bullishStarterMedR, bullishStarterStdR, bullishStarterPf, bullishStarterWilsonLb, bullishStarterAvgMfe, bullishStarterAvgMae, bullishStarterMaxDd, bullishStarterMaxLossStreak, bullishStarterScore, bullishStarterQualityOk, bullishStarterSumWinR, bullishStarterSumLossR] = dreperf.signalQualityFull(bullishStarterSig, bullishStarterSig ? low : na, true, iMinSigSuccessRate, adrCond, iSigCheckTime, iMinSigCount, iMinSigWilsonLb)
[bearishStarterSuccRate, bearishStarterSuccCount, bearishStarterSigCount, bearishStarterAvgReturn, bearishStarterSuccRateOk, bearishStarterSuccRateStr, bearishStarterWinRate, bearishStarterWinCount, bearishStarterAvgR, bearishStarterMedR, bearishStarterStdR, bearishStarterPf, bearishStarterWilsonLb, bearishStarterAvgMfe, bearishStarterAvgMae, bearishStarterMaxDd, bearishStarterMaxLossStreak, bearishStarterScore, bearishStarterQualityOk, bearishStarterSumWinR, bearishStarterSumLossR] = dreperf.signalQualityFull(bearishStarterSig, bearishStarterSig ? high : na, false, iMinSigSuccessRate, adrCond, iSigCheckTime, iMinSigCount, iMinSigWilsonLb)
[bullishFireStarterSuccRate, bullishFireStarterSuccCount, bullishFireStarterSigCount, bullishFireStarterAvgReturn, bullishFireStarterSuccRateOk, bullishFireStarterSuccRateStr, bullishFireStarterWinRate, bullishFireStarterWinCount, bullishFireStarterAvgR, bullishFireStarterMedR, bullishFireStarterStdR, bullishFireStarterPf, bullishFireStarterWilsonLb, bullishFireStarterAvgMfe, bullishFireStarterAvgMae, bullishFireStarterMaxDd, bullishFireStarterMaxLossStreak, bullishFireStarterScore, bullishFireStarterQualityOk, bullishFireStarterSumWinR, bullishFireStarterSumLossR] = dreperf.signalQualityFull(bullishFireStarterSig, bullishFireStarterSig ? low : na, true, iMinSigSuccessRate, adrCond, iSigCheckTime, iMinSigCount, iMinSigWilsonLb)
[longerSuccRate, longerSuccCount, longerSigCount, longerAvgReturn, longerSuccRateOk, longerSuccRateStr, longerWinRate, longerWinCount, longerAvgR, longerMedR, longerStdR, longerPf, longerWilsonLb, longerAvgMfe, longerAvgMae, longerMaxDd, longerMaxLossStreak, longerScore, longerQualityOk, longerSumWinR, longerSumLossR] = dreperf.signalQualityFull(longerSig, longerSig ? low : na, true, iMinSigSuccessRate, adrCond, iSigCheckTime, iMinSigCount, iMinSigWilsonLb)
[smallerLongerSuccRate, smallerLongerSuccCount, smallerLongerSigCount, smallerLongerAvgReturn, smallerLongerSuccRateOk, smallerLongerSuccRateStr, smallerLongerWinRate, smallerLongerWinCount, smallerLongerAvgR, smallerLongerMedR, smallerLongerStdR, smallerLongerPf, smallerLongerWilsonLb, smallerLongerAvgMfe, smallerLongerAvgMae, smallerLongerMaxDd, smallerLongerMaxLossStreak, smallerLongerScore, smallerLongerQualityOk, smallerLongerSumWinR, smallerLongerSumLossR] = dreperf.signalQualityFull(smallerLongerSig, smallerLongerSig ? low : na, true, iMinSigSuccessRate, adrCond, iSigCheckTime, iMinSigCount, iMinSigWilsonLb)
[zscoreBullishSuccRate, zscoreBullishSuccCount, zscoreBullishSigCount, zscoreBullishAvgReturn, zscoreBullishSuccRateOk, zscoreBullishSuccRateStr, zscoreBullishWinRate, zscoreBullishWinCount, zscoreBullishAvgR, zscoreBullishMedR, zscoreBullishStdR, zscoreBullishPf, zscoreBullishWilsonLb, zscoreBullishAvgMfe, zscoreBullishAvgMae, zscoreBullishMaxDd, zscoreBullishMaxLossStreak, zscoreBullishScore, zscoreBullishQualityOk, zscoreBullishSumWinR, zscoreBullishSumLossR] = dreperf.signalQualityFull(zscoreBullishSig, zscoreBullishSig ? low : na, true, iMinSigSuccessRate, adrCond, iSigCheckTime, iMinSigCount, iMinSigWilsonLb)
[zscoreBearishSuccRate, zscoreBearishSuccCount, zscoreBearishSigCount, zscoreBearishAvgReturn, zscoreBearishSuccRateOk, zscoreBearishSuccRateStr, zscoreBearishWinRate, zscoreBearishWinCount, zscoreBearishAvgR, zscoreBearishMedR, zscoreBearishStdR, zscoreBearishPf, zscoreBearishWilsonLb, zscoreBearishAvgMfe, zscoreBearishAvgMae, zscoreBearishMaxDd, zscoreBearishMaxLossStreak, zscoreBearishScore, zscoreBearishQualityOk, zscoreBearishSumWinR, zscoreBearishSumLossR] = dreperf.signalQualityFull(zscoreBearishSig, zscoreBearishSig ? high : na, false, iMinSigSuccessRate, adrCond, iSigCheckTime, iMinSigCount, iMinSigWilsonLb)
[bullishHunterSuccRate, bullishHunterSuccCount, bullishHunterSigCount, bullishHunterAvgReturn, bullishHunterSuccRateOk, bullishHunterSuccRateStr, bullishHunterWinRate, bullishHunterWinCount, bullishHunterAvgR, bullishHunterMedR, bullishHunterStdR, bullishHunterPf, bullishHunterWilsonLb, bullishHunterAvgMfe, bullishHunterAvgMae, bullishHunterMaxDd, bullishHunterMaxLossStreak, bullishHunterScore, bullishHunterQualityOk, bullishHunterSumWinR, bullishHunterSumLossR] = dreperf.signalQualityFull(bullishHunterSig, bullishHunterSig ? low : na, true, iMinSigSuccessRate, adrCond, iSigCheckTime, iMinSigCount, iMinSigWilsonLb)
[bearishHunterSuccRate, bearishHunterSuccCount, bearishHunterSigCount, bearishHunterAvgReturn, bearishHunterSuccRateOk, bearishHunterSuccRateStr, bearishHunterWinRate, bearishHunterWinCount, bearishHunterAvgR, bearishHunterMedR, bearishHunterStdR, bearishHunterPf, bearishHunterWilsonLb, bearishHunterAvgMfe, bearishHunterAvgMae, bearishHunterMaxDd, bearishHunterMaxLossStreak, bearishHunterScore, bearishHunterQualityOk, bearishHunterSumWinR, bearishHunterSumLossR] = dreperf.signalQualityFull(bearishHunterSig, bearishHunterSig ? high : na, false, iMinSigSuccessRate, adrCond, iSigCheckTime, iMinSigCount, iMinSigWilsonLb)
[bullishStepperSuccRate, bullishStepperSuccCount, bullishStepperSigCount, bullishStepperAvgReturn, bullishStepperSuccRateOk, bullishStepperSuccRateStr, bullishStepperWinRate, bullishStepperWinCount, bullishStepperAvgR, bullishStepperMedR, bullishStepperStdR, bullishStepperPf, bullishStepperWilsonLb, bullishStepperAvgMfe, bullishStepperAvgMae, bullishStepperMaxDd, bullishStepperMaxLossStreak, bullishStepperScore, bullishStepperQualityOk, bullishStepperSumWinR, bullishStepperSumLossR] = dreperf.signalQualityFull(bullishStepperSig, bullishStepperSig ? low : na, true, iMinSigSuccessRate, adrCond, iSigCheckTime, iMinSigCount, iMinSigWilsonLb)
[bullishLongerStepperSuccRate, bullishLongerStepperSuccCount, bullishLongerStepperSigCount, bullishLongerStepperAvgReturn, bullishLongerStepperSuccRateOk, bullishLongerStepperSuccRateStr, bullishLongerStepperWinRate, bullishLongerStepperWinCount, bullishLongerStepperAvgR, bullishLongerStepperMedR, bullishLongerStepperStdR, bullishLongerStepperPf, bullishLongerStepperWilsonLb, bullishLongerStepperAvgMfe, bullishLongerStepperAvgMae, bullishLongerStepperMaxDd, bullishLongerStepperMaxLossStreak, bullishLongerStepperScore, bullishLongerStepperQualityOk, bullishLongerStepperSumWinR, bullishLongerStepperSumLossR] = dreperf.signalQualityFull(bullishLongerStepperSig, bullishLongerStepperSig ? low : na, true, iMinSigSuccessRate, adrCond, iSigCheckTime, iMinSigCount, iMinSigWilsonLb)
[bullishSLongerStepperSuccRate, bullishSLongerStepperSuccCount, bullishSLongerStepperSigCount, bullishSLongerStepperAvgReturn, bullishSLongerStepperSuccRateOk, bullishSLongerStepperSuccRateStr, bullishSLongerStepperWinRate, bullishSLongerStepperWinCount, bullishSLongerStepperAvgR, bullishSLongerStepperMedR, bullishSLongerStepperStdR, bullishSLongerStepperPf, bullishSLongerStepperWilsonLb, bullishSLongerStepperAvgMfe, bullishSLongerStepperAvgMae, bullishSLongerStepperMaxDd, bullishSLongerStepperMaxLossStreak, bullishSLongerStepperScore, bullishSLongerStepperQualityOk, bullishSLongerStepperSumWinR, bullishSLongerStepperSumLossR] = dreperf.signalQualityFull(bullishSLongerStepperSig, bullishSLongerStepperSig ? low : na, true, iMinSigSuccessRate, adrCond, iSigCheckTime, iMinSigCount, iMinSigWilsonLb)
[bullishObvSuccRate, bullishObvSuccCount, bullishObvSigCount, bullishObvAvgReturn, bullishObvSuccRateOk, bullishObvSuccRateStr, bullishObvWinRate, bullishObvWinCount, bullishObvAvgR, bullishObvMedR, bullishObvStdR, bullishObvPf, bullishObvWilsonLb, bullishObvAvgMfe, bullishObvAvgMae, bullishObvMaxDd, bullishObvMaxLossStreak, bullishObvScore, bullishObvQualityOk, bullishObvSumWinR, bullishObvSumLossR] = dreperf.signalQualityFull(bullishObvSig, bullishObvSig ? low : na, true, iMinSigSuccessRate, adrCond, iSigCheckTime, iMinSigCount, iMinSigWilsonLb)
[bearishObvSuccRate, bearishObvSuccCount, bearishObvSigCount, bearishObvAvgReturn, bearishObvSuccRateOk, bearishObvSuccRateStr, bearishObvWinRate, bearishObvWinCount, bearishObvAvgR, bearishObvMedR, bearishObvStdR, bearishObvPf, bearishObvWilsonLb, bearishObvAvgMfe, bearishObvAvgMae, bearishObvMaxDd, bearishObvMaxLossStreak, bearishObvScore, bearishObvQualityOk, bearishObvSumWinR, bearishObvSumLossR] = dreperf.signalQualityFull(bearishObvSig, bearishObvSig ? high : na, false, iMinSigSuccessRate, adrCond, iSigCheckTime, iMinSigCount, iMinSigWilsonLb)
[pvcSuccRate, pvcSuccCount, pvcSigCount, pvcAvgReturn, pvcSuccRateOk, pvcSuccRateStr, pvcWinRate, pvcWinCount, pvcAvgR, pvcMedR, pvcStdR, pvcPf, pvcWilsonLb, pvcAvgMfe, pvcAvgMae, pvcMaxDd, pvcMaxLossStreak, pvcScore, pvcQualityOk, pvcSumWinR, pvcSumLossR] = dreperf.signalQualityFull(pvc, pvc ? low : na, true, iMinSigSuccessRate, adrCond, iSigCheckTime, iMinSigCount, iMinSigWilsonLb)
[pvc2SuccRate, pvc2SuccCount, pvc2SigCount, pvc2AvgReturn, pvc2SuccRateOk, pvc2SuccRateStr, pvc2WinRate, pvc2WinCount, pvc2AvgR, pvc2MedR, pvc2StdR, pvc2Pf, pvc2WilsonLb, pvc2AvgMfe, pvc2AvgMae, pvc2MaxDd, pvc2MaxLossStreak, pvc2Score, pvc2QualityOk, pvc2SumWinR, pvc2SumLossR] = dreperf.signalQualityFull(pvc2, pvc2 ? low : na, true, iMinSigSuccessRate, adrCond, iSigCheckTime, iMinSigCount, iMinSigWilsonLb)

juniorEffOk = iUseQualityGate ? juniorQualityOk : juniorSuccRateOk
junior2EffOk = iUseQualityGate ? junior2QualityOk : junior2SuccRateOk
juniorLateEffOk = iUseQualityGate ? juniorLateQualityOk : juniorLateSuccRateOk
coilBullishEffOk = iUseQualityGate ? coilBullishQualityOk : coilBullishSuccRateOk
strechBearishEffOk = iUseQualityGate ? strechBearishQualityOk : strechBearishSuccRateOk
bullishStarterEffOk = iUseQualityGate ? bullishStarterQualityOk : bullishStarterSuccRateOk
bearishStarterEffOk = iUseQualityGate ? bearishStarterQualityOk : bearishStarterSuccRateOk
bullishFireStarterEffOk = iUseQualityGate ? bullishFireStarterQualityOk : bullishFireStarterSuccRateOk
longerEffOk = iUseQualityGate ? longerQualityOk : longerSuccRateOk
smallerLongerEffOk = iUseQualityGate ? smallerLongerQualityOk : smallerLongerSuccRateOk
zscoreBullishEffOk = iUseQualityGate ? zscoreBullishQualityOk : zscoreBullishSuccRateOk
zscoreBearishEffOk = iUseQualityGate ? zscoreBearishQualityOk : zscoreBearishSuccRateOk
bullishHunterEffOk = iUseQualityGate ? bullishHunterQualityOk : bullishHunterSuccRateOk
bearishHunterEffOk = iUseQualityGate ? bearishHunterQualityOk : bearishHunterSuccRateOk
bullishStepperEffOk = iUseQualityGate ? bullishStepperQualityOk : bullishStepperSuccRateOk
bullishLongerStepperEffOk = iUseQualityGate ? bullishLongerStepperQualityOk : bullishLongerStepperSuccRateOk
bullishSLongerStepperEffOk = iUseQualityGate ? bullishSLongerStepperQualityOk : bullishSLongerStepperSuccRateOk
bullishObvEffOk = iUseQualityGate ? bullishObvQualityOk : bullishObvSuccRateOk
bearishObvEffOk = iUseQualityGate ? bearishObvQualityOk : bearishObvSuccRateOk
pvcEffOk = iUseQualityGate ? pvcQualityOk : pvcSuccRateOk
pvc2EffOk = iUseQualityGate ? pvc2QualityOk : pvc2SuccRateOk

//plot sig performance
juniorSigColor = color.new(color.green, 0)
junior2SigColor = color.new(color.green, 0)
juniorLateSigColor = color.new(color.green, 0)
coilBullishSigColor = color.new(color.gray, 0)
strechBearishSigColor = color.new(color.red, 0)
bullishStarterSigColor = color.new(color.green, 0)
bearishStarterSigColor = color.new(color.red, 0)
bullishFireStarterSigColor = color.new(color.green, 0)
longerSigColor = color.new(color.green, 0)
smallerLongerSigColor = color.new(color.green, 0)
zscoreBullishSigColor = color.new(color.gray, 0)
zscoreBearishSigColor = color.new(color.gray, 0)
bullishHunterSigColor = color.new(color.green, 0)
bearishHunterSigColor = color.new(color.red, 0)
bullishStepperSigColor = color.new(color.green, 0)
bullishLongerStepperSigColor = color.new(color.green, 0)
bullishSLongerStepperSigColor = color.new(color.green, 0)
bullishObvSigColor = color.new(color.green, 0)
bearishObvSigColor = color.new(color.red, 0)

//print sig performance table
renderQualityRow(table _tbl, int _row, string _name, color _color, bool _sigOk, bool _showThisSig, string _perfStr, float _winRatePct, int _sigCnt, float _avgR, float _pf, float _maxDdR, float _score, float _sumWinR, float _sumLossR) =>
    if showRow(iShowOnlyGoodSigs, _sigOk, _showThisSig)
        table.cell(table_id = _tbl, column = 0, row = _row, text = _name, text_color = _color, text_size = size.small)
        table.cell(table_id = _tbl, column = 1, row = _row, text = _perfStr, text_size = size.small)
        table.cell(table_id = _tbl, column = 2, row = _row, text = str.tostring(_winRatePct, "#.#"), text_size = size.small)
        table.cell(table_id = _tbl, column = 3, row = _row, text = str.tostring(_sigCnt), text_size = size.small)
        table.cell(table_id = _tbl, column = 4, row = _row, text = str.tostring(_avgR, "#.##"), text_size = size.small)
        table.cell(table_id = _tbl, column = 5, row = _row, text = na(_pf) ? "∞" : str.tostring(_pf, "#.##"), text_size = size.small)
        table.cell(table_id = _tbl, column = 6, row = _row, text = str.tostring(_maxDdR, "#.##"), text_size = size.small)
        table.cell(table_id = _tbl, column = 7, row = _row, text = str.tostring(_score, "#.#"), text_size = size.small)
        table.cell(table_id = _tbl, column = 8, row = _row, text = str.tostring(_sumWinR, "#.#"), text_size = size.small)
        table.cell(table_id = _tbl, column = 9, row = _row, text = str.tostring(_sumLossR, "#.#"), text_size = size.small)

if barstate.islast and iShowSigPerfTable
    var tbl = table.new(position = position.top_right, columns = 10, rows = 23)
    txtSize = size.small
    table.cell(table_id = tbl, column = 0, row = 1, text = "sig", text_size = txtSize)
    table.cell(table_id = tbl, column = 1, row = 1, text = str.format("perf {0,number,#.#} {1,number,#.#}", iMinSigSuccessRate, adrCond), text_size = txtSize)
    table.cell(table_id = tbl, column = 2, row = 1, text = "win%", text_size = txtSize)
    table.cell(table_id = tbl, column = 3, row = 1, text = "N", text_size = txtSize)
    table.cell(table_id = tbl, column = 4, row = 1, text = "avgR", text_size = txtSize)
    table.cell(table_id = tbl, column = 5, row = 1, text = "PF", text_size = txtSize)
    table.cell(table_id = tbl, column = 6, row = 1, text = "maxDD", text_size = txtSize)
    table.cell(table_id = tbl, column = 7, row = 1, text = "score", text_size = txtSize)
    table.cell(table_id = tbl, column = 8, row = 1, text = "winR", text_size = txtSize)
    table.cell(table_id = tbl, column = 9, row = 1, text = "lossR", text_size = txtSize)

    renderQualityRow(tbl, 2, "junior", juniorSigColor, juniorEffOk, iJunior, juniorSuccRateStr, juniorWinRate, juniorSigCount, juniorAvgR, juniorPf, juniorMaxDd, juniorScore, juniorSumWinR, juniorSumLossR)
    renderQualityRow(tbl, 3, "junior2", junior2SigColor, junior2EffOk, iJunior2, junior2SuccRateStr, junior2WinRate, junior2SigCount, junior2AvgR, junior2Pf, junior2MaxDd, junior2Score, junior2SumWinR, junior2SumLossR)
    renderQualityRow(tbl, 4, "late-junior", juniorLateSigColor, juniorLateEffOk, iJunior3, juniorLateSuccRateStr, juniorLateWinRate, juniorLateSigCount, juniorLateAvgR, juniorLatePf, juniorLateMaxDd, juniorLateScore, juniorLateSumWinR, juniorLateSumLossR)
    renderQualityRow(tbl, 5, "coil", coilBullishSigColor, coilBullishEffOk, iCoil, coilBullishSuccRateStr, coilBullishWinRate, coilBullishSigCount, coilBullishAvgR, coilBullishPf, coilBullishMaxDd, coilBullishScore, coilBullishSumWinR, coilBullishSumLossR)
    renderQualityRow(tbl, 6, "strech", strechBearishSigColor, strechBearishEffOk, iCoilStrech, strechBearishSuccRateStr, strechBearishWinRate, strechBearishSigCount, strechBearishAvgR, strechBearishPf, strechBearishMaxDd, strechBearishScore, strechBearishSumWinR, strechBearishSumLossR)
    renderQualityRow(tbl, 7, "Starter", bullishStarterSigColor, bullishStarterEffOk, iBullishStarter, bullishStarterSuccRateStr, bullishStarterWinRate, bullishStarterSigCount, bullishStarterAvgR, bullishStarterPf, bullishStarterMaxDd, bullishStarterScore, bullishStarterSumWinR, bullishStarterSumLossR)
    renderQualityRow(tbl, 8, "bear Starter", bearishStarterSigColor, bearishStarterEffOk, iBearishStarter, bearishStarterSuccRateStr, bearishStarterWinRate, bearishStarterSigCount, bearishStarterAvgR, bearishStarterPf, bearishStarterMaxDd, bearishStarterScore, bearishStarterSumWinR, bearishStarterSumLossR)
    renderQualityRow(tbl, 9, "FireStarter", bullishFireStarterSigColor, bullishFireStarterEffOk, iBullishFireStarter, bullishFireStarterSuccRateStr, bullishFireStarterWinRate, bullishFireStarterSigCount, bullishFireStarterAvgR, bullishFireStarterPf, bullishFireStarterMaxDd, bullishFireStarterScore, bullishFireStarterSumWinR, bullishFireStarterSumLossR)
    renderQualityRow(tbl, 10, "longer", longerSigColor, longerEffOk, iLonger, longerSuccRateStr, longerWinRate, longerSigCount, longerAvgR, longerPf, longerMaxDd, longerScore, longerSumWinR, longerSumLossR)
    renderQualityRow(tbl, 11, "s-longer", smallerLongerSigColor, smallerLongerEffOk, iLonger, smallerLongerSuccRateStr, smallerLongerWinRate, smallerLongerSigCount, smallerLongerAvgR, smallerLongerPf, smallerLongerMaxDd, smallerLongerScore, smallerLongerSumWinR, smallerLongerSumLossR)
    renderQualityRow(tbl, 12, "bubble up", zscoreBullishSigColor, zscoreBullishEffOk, iBullishZscore, zscoreBullishSuccRateStr, zscoreBullishWinRate, zscoreBullishSigCount, zscoreBullishAvgR, zscoreBullishPf, zscoreBullishMaxDd, zscoreBullishScore, zscoreBullishSumWinR, zscoreBullishSumLossR)
    renderQualityRow(tbl, 13, "bubble dn", zscoreBearishSigColor, zscoreBearishEffOk, iBearishZscore, zscoreBearishSuccRateStr, zscoreBearishWinRate, zscoreBearishSigCount, zscoreBearishAvgR, zscoreBearishPf, zscoreBearishMaxDd, zscoreBearishScore, zscoreBearishSumWinR, zscoreBearishSumLossR)
    renderQualityRow(tbl, 14, "bullishHunter", bullishHunterSigColor, bullishHunterEffOk, iBullishHunter, bullishHunterSuccRateStr, bullishHunterWinRate, bullishHunterSigCount, bullishHunterAvgR, bullishHunterPf, bullishHunterMaxDd, bullishHunterScore, bullishHunterSumWinR, bullishHunterSumLossR)
    renderQualityRow(tbl, 15, "bearishHunter", bearishHunterSigColor, bearishHunterEffOk, iBearishHunter, bearishHunterSuccRateStr, bearishHunterWinRate, bearishHunterSigCount, bearishHunterAvgR, bearishHunterPf, bearishHunterMaxDd, bearishHunterScore, bearishHunterSumWinR, bearishHunterSumLossR)
    renderQualityRow(tbl, 16, "Stepper", bullishStepperSigColor, bullishStepperEffOk, iBullishStepper, bullishStepperSuccRateStr, bullishStepperWinRate, bullishStepperSigCount, bullishStepperAvgR, bullishStepperPf, bullishStepperMaxDd, bullishStepperScore, bullishStepperSumWinR, bullishStepperSumLossR)
    renderQualityRow(tbl, 17, "LongerStepper", bullishLongerStepperSigColor, bullishLongerStepperEffOk, iBullishLongerStepper, bullishLongerStepperSuccRateStr, bullishLongerStepperWinRate, bullishLongerStepperSigCount, bullishLongerStepperAvgR, bullishLongerStepperPf, bullishLongerStepperMaxDd, bullishLongerStepperScore, bullishLongerStepperSumWinR, bullishLongerStepperSumLossR)
    renderQualityRow(tbl, 18, "s-LongerStepper", bullishSLongerStepperSigColor, bullishSLongerStepperEffOk, iBullishLongerStepper, bullishSLongerStepperSuccRateStr, bullishSLongerStepperWinRate, bullishSLongerStepperSigCount, bullishSLongerStepperAvgR, bullishSLongerStepperPf, bullishSLongerStepperMaxDd, bullishSLongerStepperScore, bullishSLongerStepperSumWinR, bullishSLongerStepperSumLossR)
    renderQualityRow(tbl, 19, "obv", bullishObvSigColor, bullishObvEffOk, iBullishObv, bullishObvSuccRateStr, bullishObvWinRate, bullishObvSigCount, bullishObvAvgR, bullishObvPf, bullishObvMaxDd, bullishObvScore, bullishObvSumWinR, bullishObvSumLossR)
    renderQualityRow(tbl, 20, "bear obv", bearishObvSigColor, bearishObvEffOk, iBearishObv, bearishObvSuccRateStr, bearishObvWinRate, bearishObvSigCount, bearishObvAvgR, bearishObvPf, bearishObvMaxDd, bearishObvScore, bearishObvSumWinR, bearishObvSumLossR)
    renderQualityRow(tbl, 21, "pvc", color.new(color.gray, 0), pvcEffOk, true, pvcSuccRateStr, pvcWinRate, pvcSigCount, pvcAvgR, pvcPf, pvcMaxDd, pvcScore, pvcSumWinR, pvcSumLossR)
    renderQualityRow(tbl, 22, "pvc2", color.new(color.gray, 0), pvc2EffOk, true, pvc2SuccRateStr, pvc2WinRate, pvc2SigCount, pvc2AvgR, pvc2Pf, pvc2MaxDd, pvc2Score, pvc2SumWinR, pvc2SumLossR)

//plot signals on price chart
plotshape(juniorSig and showRow(iShowOnlyGoodSigs, juniorEffOk, iJunior), title = 'junior', location = location.belowbar, color = juniorSigColor, style = shape.triangleup, text = 'junior', textcolor = juniorSigColor)
plotshape(junior2Sig and showRow(iShowOnlyGoodSigs, junior2EffOk, iJunior2), title = 'junior2', location = location.belowbar, color = junior2SigColor, style = shape.triangleup, text = 'junior2', textcolor = junior2SigColor)
plotshape(juniorLateSig and showRow(iShowOnlyGoodSigs, juniorLateEffOk, iJunior3), title = 'late-junior', location = location.belowbar, color = juniorLateSigColor, style = shape.triangleup, text = 'late-junior', textcolor = juniorLateSigColor)
plotshape(coilBullishSig and showRow(iShowOnlyGoodSigs, coilBullishEffOk, iCoil), title = 'coil', location = location.belowbar, color = coilBullishSigColor, style = shape.xcross, text = 'coil', textcolor = coilBullishSigColor)
plotshape(strechBearishSig and showRow(iShowOnlyGoodSigs, strechBearishEffOk, iCoilStrech), title = 'strech', location = location.abovebar, color = strechBearishSigColor, style = shape.triangledown, text = 'strech', textcolor = strechBearishSigColor)
plotshape(bullishStarterSig and showRow(iShowOnlyGoodSigs, bullishStarterEffOk, iBullishStarter), title = 'bullish starter', location = location.belowbar, color = bullishStarterSigColor, style = shape.triangleup, text = 'starter', textcolor = bullishStarterSigColor)
plotshape(bearishStarterSig and showRow(iShowOnlyGoodSigs, bearishStarterEffOk, iBearishStarter), title = 'bearish starter', location = location.abovebar, color = bearishStarterSigColor, style = shape.triangledown, text = 'starter', textcolor = bearishStarterSigColor)
plotshape(bullishFireStarterSig and showRow(iShowOnlyGoodSigs, bullishFireStarterEffOk, iBullishFireStarter), title = 'bullish fire starter', location = location.belowbar, color = bullishFireStarterSigColor, style = shape.triangleup, text = 'f.starter', textcolor = bullishFireStarterSigColor)
plotshape(longerSig and showRow(iShowOnlyGoodSigs, longerEffOk, iLonger), title = 'longer', location = location.belowbar, color = longerSigColor, style = shape.triangleup, text = 'longer', textcolor = longerSigColor)
plotshape(smallerLongerSig and showRow(iShowOnlyGoodSigs, smallerLongerEffOk, iLonger), title = 's-longer', location = location.belowbar, color = smallerLongerSigColor, style = shape.triangleup, text = 's-longer', textcolor = smallerLongerSigColor)
plotshape(zscoreBullishSig and showRow(iShowOnlyGoodSigs, zscoreBullishEffOk, iBullishZscore), title = 'bubble up', location = location.belowbar, color = zscoreBullishSigColor, style = shape.xcross, text = 'bubble up', textcolor = zscoreBullishSigColor)
plotshape(zscoreBearishSig and showRow(iShowOnlyGoodSigs, zscoreBearishEffOk, iBearishZscore), title = 'bubble dn', location = location.belowbar, color = zscoreBearishSigColor, style = shape.xcross, text = 'bubble dn', textcolor = zscoreBearishSigColor)
plotshape(bullishHunterSig and showRow(iShowOnlyGoodSigs, bullishHunterEffOk, iBullishHunter), title = 'bullish hunter', location = location.belowbar, color = bullishHunterSigColor, style = shape.triangleup, text = 'hunter', textcolor = bullishHunterSigColor)
plotshape(bearishHunterSig and showRow(iShowOnlyGoodSigs, bearishHunterEffOk, iBearishHunter), title = 'bearish hunter', location = location.abovebar, color = bearishHunterSigColor, style = shape.triangledown, text = 'hunter', textcolor = bearishHunterSigColor)
plotshape(bullishStepperSig and not bullishLongerStepperSig and showRow(iShowOnlyGoodSigs, bullishStepperEffOk, iBullishStepper), title = 'bullish stepper', location = location.belowbar, color = bullishStepperSigColor, style = shape.triangleup, text = 'stepper', textcolor = bullishStepperSigColor)
plotshape(bullishLongerStepperSig and showRow(iShowOnlyGoodSigs, bullishLongerStepperEffOk, iBullishLongerStepper), title = 'bullish l.stepper', location = location.belowbar, color = bullishLongerStepperSigColor, style = shape.triangleup, text = 'l.stepper', textcolor = bullishLongerStepperSigColor)
plotshape(bullishSLongerStepperSig and showRow(iShowOnlyGoodSigs, bullishSLongerStepperEffOk, iBullishLongerStepper), title = 'bullish s-l.stepper', location = location.belowbar, color = bullishSLongerStepperSigColor, style = shape.triangleup, text = 's-l.stepper', textcolor = bullishSLongerStepperSigColor)
plotshape(bullishObvSig and showRow(iShowOnlyGoodSigs, bullishObvEffOk, iBullishObv), title = 'bullish obv', location = location.belowbar, color = bullishObvSigColor, style = shape.triangleup, text = 'obv', textcolor = bullishObvSigColor)
plotshape(bearishObvSig and showRow(iShowOnlyGoodSigs, bearishObvEffOk, iBearishObv), title = 'bearish obv', location = location.abovebar, color = bearishObvSigColor, style = shape.triangledown, text = 'obv', textcolor = bearishObvSigColor)

//issuing alerts
alertcondition(juniorSig, title = 'DRE junior sig', message = 'junior')
alertcondition(juniorLateSig, title = 'DRE late-junior', message = 'late-junior')
alertcondition(junior2Sig, title = 'DRE junior2 sig', message = 'junior2')
alertcondition(gFilter and coilBullishSig, title = 'DRE coil sig', message = 'coil')
alertcondition(gFilter and strechBearishSig, title = 'DRE strech sig', message = 'strech')
alertcondition(gFilter and bullishStarterSig, title = 'DRE bullish starter sig', message = 'bullish starter')
alertcondition(gFilter and bearishStarterSig, title = 'DRE bearish starter sig', message = 'bearish starter')
alertcondition(gFilter and bullishFireStarterSig, title = 'DRE bullish fire starter sig', message = 'bullish fire starter')
alertcondition(gFilter and longerSig, title = 'DRE longer sig', message = 'longer')
alertcondition(gFilter and smallerLongerSig, title = 'DRE sLonger sig', message = 's-longer')
alertcondition(gFilter and zscoreBullishSig, title = 'DRE bubble up', message = 'bubble up')
alertcondition(gFilter and zscoreBearishSig, title = 'DRE bubble dn', message = 'bubble dn')
alertcondition(gFilter and bullishHunterSig, title = 'DRE Bullish hunter', message = 'hunter')
alertcondition(gFilter and bearishHunterSig, title = 'DRE Bearish hunter', message = 'hunter')
alertcondition(gFilter and bullishStepperSig, title = 'DRE Bullish stepper', message = 'stepper')
alertcondition(gFilter and bullishLongerStepperSig, title = 'DRE Bullish longer-stepper', message = 'l.stepper')
alertcondition(gFilter and bullishSLongerStepperSig, title = 'DRE Bullish s-longer-stepper', message = 's-l.stepper')
alertcondition(gFilter and bullishObvSig, title = 'DRE Bullish obv', message = 'obv')
alertcondition(gFilter and bearishObvSig, title = 'DRE Bearish obv', message = 'obv')
alertcondition(gFilter and bullishRmvSig, title = 'DRE Bullish rmv', message = 'rmv')
alertcondition(gFilter and bullishRmvPbSig, title = 'DRE Bullish rmv-pb', message = 'rmv-pb')
alertcondition(gFilter and bearishRmvSig, title = 'DRE Bearish rmv', message = 'rmv')
alertcondition(gFilter and bearishRmvPbSig, title = 'DRE Bearish rmv-pb', message = 'rmv-pb')
alertcondition(gFilter and mtbSig, title = 'DRE Bullish mtb', message = 'mtb')

alertcondition(gFilter and bullishSig, title = 'DRE Bullish pattern sig', message = 'bullish pattern')
alertcondition(gFilter and bearishSig, title = 'DRE Bearish pattern sig', message = 'bearish pattern')
alertcondition(gFilter and (bullishSig or bearishSig), title = 'DRE ALL pattern sig', message = 'all patterns')

alertcondition(candleBullishBoOnVolumeCond and gFilter and mtbSig[1], title = 'DRE Bullish mtb BO sig', message = 'bullish mtb BO')
alertcondition(candleBullishBoOnVolumeCond and gFilter and bullishSig[1], title = 'DRE Bullish pattern BO sig', message = 'bullish pattern BO')
alertcondition(candleBearishBoOnVolumeCond and gFilter and bearishSig[1], title = 'DRE Bearish pattern BO sig', message = 'bearish pattern BO')
alertcondition(gFilter and (candleBullishBoOnVolumeCond and bullishSig[1] or candleBearishBoOnVolumeCond and bearishSig[1]), title = 'DRE ALL pattern BO sig', message = 'all patterns BO')
