//@version=5
indicator(title='DRE Seasonality-Buschi', shorttitle='DRE Seasonality-Buschi', precision=2, max_bars_back=5000)

repeat_period_millis = 365 * 24 * 60 * 60 * 1000

is_in_last_period = time >= timenow - repeat_period_millis

fast_search_n(xs, x) =>  // xs - sorted, ascending
    len = 4096
    size = math.floor(len / 2)
    k = size
    for i = 0 to 15 by 1
        size := math.floor(size / 2)
        if (x <= xs[k] ? 1 : 0) * (x > xs[k + 1] ? 1 : 0) > 0
            break
        if (xs[k] < x ? 1 : 0) + (na(xs[k]) ? 1 : 0) > 0
            k -= size
            k
        else
            k += size
            k
        if size == 0
            if na(xs[k]) ? 1 : 0 + 1 - (x <= xs[k] ? 1 : 0) * (x > xs[k + 1] ? 1 : 0) > 0
                k := na
                k
            break
    k

find_n_periods_ago(i) =>
    fast_search_n(time, time - repeat_period_millis * i)

n_1y = find_n_periods_ago(1)
n_2y = find_n_periods_ago(2)
n_3y = find_n_periods_ago(3)
n_4y = find_n_periods_ago(4)
n_5y = find_n_periods_ago(5)
n_6y = find_n_periods_ago(6)
n_7y = find_n_periods_ago(7)
n_8y = find_n_periods_ago(8)
n_9y = find_n_periods_ago(9)
n_10y = find_n_periods_ago(10)
n_11y = find_n_periods_ago(11)

close_last3y0 = (close + close[n_1y] + close[n_2y]) / 3
close_last6y3 = (close[n_3y] + close[n_4y] + close[n_5y]) / 3
close_last9y6 = (close[n_6y] + close[n_7y] + close[n_8y]) / 3
close_last12y9 = (close[n_9y] + close[n_10y] + close[n_11y]) / 3
close_last12y = (close_last3y0 + close_last6y3 + close_last9y6 + close_last12y9) / 4

// vol_last12y_sma20 = ta.sma(((volume + volume[n_1y] + volume[n_2y] + volume[n_3y] + volume[n_4y] + volume[n_5y] + volume[n_6y] + volume[n_7y] + volume[n_8y] + volume[n_9y] + volume[n_10y] + volume[n_11y]) / 12), 20)

plot(is_in_last_period ? close : na, color=color.new(color.black, 0), linewidth=2, title='current year')
plot(is_in_last_period ? close_last3y0 : na, color=color.new(#88FF00, 0), linewidth=1, title='last 3 years')
plot(is_in_last_period ? close_last6y3 : na, color=color.new(#FF8800, 0), linewidth=1, title='6-3 years back')
plot(is_in_last_period ? close_last9y6 : na, color=color.new(#FF4400, 0), linewidth=1, title='9-6 years back')
plot(is_in_last_period ? close_last12y9 : na, color=color.new(#FF0000, 0), linewidth=1, title='12-9 years back')
plot(is_in_last_period ? close_last12y : na, color=color.new(color.purple, 0), linewidth=2, title='all 12 years back')

// plot(is_in_last_period ? vol_last12y_sma20 : na, color=color.new(color.purple, 0), style = plot.style_histogram, linewidth=1, title='volume all 12 years back')
