// This Pine Script™ code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © drebel

//@version=6
indicator(title = 'DRE parabolic top', overlay = true, max_bars_back = 2200, calc_bars_count = 12 * 252)

import drebel/DRELib/39 as drelib
import drebel/DREPerf/23 as dreperf

//common filters
iTurnoverCond = input.bool(defval = true, title = 'Min. Turnover for signal [M]', display = display.none, group = 'Common signal filters', inline = 'trn')
iMinTurnover = input.float(defval = 0.15, title = '', minval = 0, display = display.none, group = 'Common signal filters', inline = 'trn')
iAdrCond = input.bool(defval = true, title = 'Min. ADR% for signal', display = display.none, group = 'Common signal filters', inline = 'adr')
iMinAdr = input.float(defval = 2.6, title = '', minval = 0, step = 0.2, display = display.none, group = 'Common signal filters', inline = 'adr')

//common inputs
iMainMaLength = input.int(defval = 200, title = 'Main MA length', minval = 50, maxval = 500, display = display.none, group = 'Common parameters')
iShortMaLength = input.int(defval = 50, title = 'Short MA length', minval = 10, maxval = 200, display = display.none, group = 'Common parameters')
iLongMaLength = input.int(defval = 750, title = 'Long MA length', minval = 200, maxval = 1000, display = display.none, group = 'Common parameters')
iVShortMaLength1 = input.int(defval = 10, title = 'Very short MA length', minval = 5, maxval = 50, display = display.none, group = 'Common parameters')
iVShortMaLength2 = input.int(defval = 21, title = 'Very short MA length2', minval = 8, maxval = 50, display = display.none, group = 'Common parameters')

//common calculations
mainAtr = ta.atr(iMainMaLength)
mainMa = ta.sma(close, iMainMaLength)
shortMa = ta.sma(close, iShortMaLength)
longMa = ta.sma(close, iLongMaLength)
gVShortMa1 = ta.ema(close, iVShortMaLength1)
gVShortMa2 = ta.ema(close, iVShortMaLength2)
gVolMa = ta.sma(volume, 30)
adrPct = 100.0 * (ta.sma(high / low, 30) - 1)

//filters (min. iShortMaLength candles)
gTurnoverMa = ta.sma(close * volume, iShortMaLength) / 1000000.0
gTurnoverMedian = ta.median(close * volume, iShortMaLength) / 1000000.0
gTurnoverCond = not iTurnoverCond or iTurnoverCond and gTurnoverMa > iMinTurnover and gTurnoverMedian > iMinTurnover
gAdr = 100 * (ta.sma(high / low, iShortMaLength) - 1)
gAdrCond = not iAdrCond or iAdrCond and gAdr > iMinAdr
gFilter = gTurnoverCond and gAdrCond

//parabolic top sig
iParabolicTop = input.bool(defval = false, title = 'Parabolic top', display = display.none, group = 'parabolic top')
iParTopAtrMulti = input.int(defval = 8, title = 'ATR Multiple Since Low', minval = 2, maxval = 30, display = display.none, group = 'parabolic top')
iParTopGainDays = input.int(defval = 100, title = 'Number Of Days To top', minval = 5, maxval = 150, step = 5, display = display.none, group = 'parabolic top')
iDownDays1 = input.bool(defval = true, title = 'Down Days After Top 1', display = display.none, group = 'parabolic top', inline = 'top1')
iDownDaysAfterTop1 = input.int(defval = 2, title = '', minval = 1, maxval = 8, display = display.none, group = 'parabolic top', inline = 'top1')
iDownDays2 = input.bool(defval = true, title = 'Down Days After Top 2', display = display.none, group = 'parabolic top', inline = 'top2')
iDownDaysAfterTop2 = input.int(defval = 3, title = '', minval = 1, maxval = 8, display = display.none, group = 'parabolic top', inline = 'top2')
iDownDays3 = input.bool(defval = true, title = 'Down Days After Top 3', display = display.none, group = 'parabolic top', inline = 'top3')
iDownDaysAfterTop3 = input.int(defval = 4, title = '', minval = 1, maxval = 8, display = display.none, group = 'parabolic top', inline = 'top3')

top1Sig = drelib.sigParabolicTop(gVolMa, iDownDaysAfterTop1, iParTopGainDays, iParTopAtrMulti, mainAtr) and iDownDays1
top2Sig = drelib.sigParabolicTop(gVolMa, iDownDaysAfterTop2, iParTopGainDays, iParTopAtrMulti, mainAtr) and iDownDays2
top3Sig = drelib.sigParabolicTop(gVolMa, iDownDaysAfterTop3, iParTopGainDays, iParTopAtrMulti, mainAtr) and iDownDays3
topSig = top1Sig or top2Sig or top3Sig

alertcondition(gFilter and topSig, title = 'DRE Parabolic TOP sig', message = 'parabolic TOP')
plotshape(topSig and iParabolicTop, title = 'parabolic top', location = location.abovebar, color = color.new(color.red, 0), style = shape.triangledown, text = 'top', textcolor = color.new(color.red, 0))


//junior sig
iJunior = input.bool(defval = false, title = 'bullish junior', display = display.none, group = 'junior')
iJunior2 = input.bool(defval = false, title = 'bullish junior2', display = display.none, group = 'junior')
iJunior3 = input.bool(defval = false, title = 'bullish late-junior', display = display.none, group = 'junior')

func_init_vwap_excl_init_higher_volume() =>
    x = 0.5
    reset = bar_index == 0 or bar_index == 1 and volume < x * volume[1] or bar_index == 2 and volume < x * volume[1] and volume[1] < x * volume[2]
    ret = ta.vwap(ohlc4, reset)
    ret

func_sig_junior_late(_minAge) =>
    initVwap = func_init_vwap_excl_init_higher_volume()
    ret = bar_index >= _minAge and drelib.crossover(initVwap)
    ret

juniorSig = drelib.sigJunior(iLongMaLength)
juniorLateSig = func_sig_junior_late(iLongMaLength)

alertcondition(juniorSig, title = 'DRE junior sig', message = 'junior')
alertcondition(juniorLateSig, title = 'DRE late-junior', message = 'late-junior')
plotshape(juniorSig and iJunior, title = 'junior', location = location.belowbar, color = color.new(color.green, 0), style = shape.triangleup, text = 'junior', textcolor = color.new(color.green, 0))
plotshape(juniorLateSig and iJunior3, title = 'late-junior', location = location.belowbar, color = color.new(color.green, 0), style = shape.triangleup, text = 'late-junior', textcolor = color.new(color.green, 0))



freshStock = bar_index < iLongMaLength
bars = int(math.min(bar_index > 1 ? bar_index * 0.8 : 1, iLongMaLength))
initialHigh = ta.highest(bars)
isHighestSinceIpo = high == initialHigh
initialHighBarsAgo = ta.barssince(isHighestSinceIpo)
initHighVwap = ta.vwap(ohlc4, freshStock and isHighestSinceIpo)
bars2 = bar_index > 15 ? bar_index - 7 : bar_index * 0.2
junior2Sig = initialHighBarsAgo > bars2 and drelib.candle_crossover(initHighVwap)
alertcondition(junior2Sig, title = 'DRE junior2 sig', message = 'junior2')
plotshape(junior2Sig and iJunior2, title = 'junior2', location = location.belowbar, color = color.new(color.green, 0), style = shape.triangleup, text = 'junior2', textcolor = color.new(color.green, 0))

// junior3Sig = freshStock and initialHighBarsAgo > bars2 and drelib.candle_crossover(initialHigh[1])
// alertcondition(junior3Sig, title = 'DRE junior3 sig', message = 'junior3')
// plotshape(junior3Sig and iJunior3, title = 'junior3', location = location.belowbar, color = color.new(color.green, 0), style = shape.triangleup, text = 'junior3', textcolor = color.new(color.green, 0))


//coil and strech sig
iCoil = input.bool(defval = false, title = 'bullish', display = display.none, group = 'coil_n_strech', inline = 'coil1')
iCoilStrech = input.bool(defval = false, title = 'bearish', display = display.none, group = 'coil_n_strech', inline = 'coil1')
iCoilPercent = input.int(defval = 2, title = 'Percentile rank distance from MAs', minval = 1, maxval = 20, display = display.none, group = 'coil_n_strech')

func_ma_distance(_shortMaLen, _mediumMaLen, _longMaLen) =>
    ma1 = ta.sma(close, _shortMaLen)
    ma2 = ta.sma(close, _mediumMaLen)
    ma3 = ta.sma(close, _longMaLen)
    zeroBarVwap = ta.vwap(ohlc4, bar_index == 0)
    usedLongMaLen = bar_index < _longMaLen ? bar_index : _longMaLen
    ma3used = bar_index < _longMaLen ? zeroBarVwap : ma3
    lenSum = _shortMaLen + _mediumMaLen + usedLongMaLen
    distance = math.sqrt((lenSum - _shortMaLen) * math.pow(ma1 - close, 2) + (lenSum - _mediumMaLen) * math.pow(ma2 - close, 2) + (lenSum - usedLongMaLen) * math.pow(ma3used - close, 2))
    distance

func_sig_coil(_dist, _longMaLen, _mediumMaLen, _distPercentRank) =>
    percentRankLen = bar_index < 1 ? 1 : math.min(bar_index, 3 * _longMaLen)
    mediumMa = ta.sma(close, _mediumMaLen)
    ret = ta.percentrank(_dist, percentRankLen) < _distPercentRank and drelib.crossover(mediumMa)
    ret

func_sig_strech(_dist, _longMaLen, _distPercentRank) =>
    percentRankLen = bar_index < 1 ? 1 : math.min(bar_index, 3 * _longMaLen)
    ret = ta.percentrank(_dist, percentRankLen) > 100 - _distPercentRank and close > close[_longMaLen] and close > close[1]
    ret

coilBullishSig = func_sig_coil(func_ma_distance(iShortMaLength, iMainMaLength, iLongMaLength), iLongMaLength, iMainMaLength, iCoilPercent)
strechBearishSig = func_sig_strech(func_ma_distance(iShortMaLength, iMainMaLength, iLongMaLength), iLongMaLength, iCoilPercent)

alertcondition(gFilter and coilBullishSig, title = 'DRE coil sig', message = 'coil')
alertcondition(gFilter and strechBearishSig, title = 'DRE strech sig', message = 'strech')
plotshape(coilBullishSig and iCoil, title = 'coil', location = location.belowbar, color = color.new(color.gray, 0), style = shape.xcross, text = 'coil', textcolor = color.new(color.gray, 0))
plotshape(strechBearishSig and iCoilStrech, title = 'strech', location = location.abovebar, color = color.new(color.red, 0), style = shape.triangledown, text = 'strech', textcolor = color.new(color.red, 0))


//starter sig
iBullishStarter = input.bool(defval = false, title = 'bullish', display = display.none, group = 'starter', inline = 'starter1')
iBearishStarter = input.bool(defval = false, title = 'bearish', display = display.none, group = 'starter', inline = 'starter1')
iBullishFireStarter = input.bool(defval = false, title = 'bullish fire starter', display = display.none, group = 'starter')
iStarterMinDecliningDays = input.int(defval = 200, title = 'Number of SMA declining days', minval = 20, maxval = 1000, display = display.none, group = 'starter')
iStarterMaxIncliningDays = input.int(defval = 200, title = 'Number of SMA inclining day', minval = 0, maxval = 300, display = display.none, group = 'starter')
iStarterSmaSmoothing = input.int(defval = 3, title = 'SMA smoothing', minval = 0, maxval = 10, display = display.none, group = 'starter')
iFireStarterMaDiffAtrMultiple = input.float(defval = 1, title = 'Fire starter MA difference ATR multiple', minval = 0.5, maxval = 10, step = 0.5, display = display.none, group = 'starter')

bullishStarterSig = drelib.sigStarter(true, iMainMaLength, iStarterMinDecliningDays, iStarterMaxIncliningDays, iStarterSmaSmoothing)
bearishStarterSig = drelib.sigStarter(false, iMainMaLength, iStarterMinDecliningDays, iStarterMaxIncliningDays, iStarterSmaSmoothing)
bullishFireStarterSig = drelib.sigFireStarter(iMainMaLength, iStarterMinDecliningDays, iFireStarterMaDiffAtrMultiple, iStarterSmaSmoothing, mainAtr)

alertcondition(gFilter and bullishStarterSig, title = 'DRE bullish starter sig', message = 'bullish starter')
alertcondition(gFilter and bearishStarterSig, title = 'DRE bearish starter sig', message = 'bearish starter')
alertcondition(gFilter and bullishFireStarterSig, title = 'DRE bullish fire starter sig', message = 'bullish fire starter')
plotshape(bullishStarterSig and iBullishStarter, title = 'bullish starter', location = location.belowbar, color = color.new(color.green, 0), style = shape.triangleup, text = 'starter', textcolor = color.new(color.green, 0))
plotshape(bearishStarterSig and iBearishStarter, title = 'bearish starter', location = location.abovebar, color = color.new(color.red, 0), style = shape.triangledown, text = 'starter', textcolor = color.new(color.red, 0))
plotshape(bullishFireStarterSig and iBullishFireStarter, title = 'bullish fire starter', location = location.belowbar, color = color.new(color.green, 0), style = shape.triangleup, text = 'f.starter', textcolor = color.new(color.green, 0))


//longer sig
iLonger = input.bool(defval = false, title = 'bullish', display = display.none, group = 'longer', inline = 'longer1')
iLongerOffset = input.float(defval = 0.1, title = 'Price offset (atr multiple)', minval = -2.0, maxval = 2.0, step = 0.5, display = display.none, group = 'longer')

longerSig = drelib.sigLonger(mainMa, longMa, 0, mainAtr)
smallerLongerSig = drelib.sigLonger(shortMa, mainMa, 0, mainAtr)

alertcondition(gFilter and longerSig, title = 'DRE longer sig', message = 'longer')
alertcondition(gFilter and smallerLongerSig, title = 'DRE sLonger sig', message = 's-longer')
plotshape(longerSig and iLonger, title = 'longer', location = location.belowbar, color = color.new(color.green, 0), style = shape.triangleup, text = 'longer', textcolor = color.new(color.green, 0))
plotshape(smallerLongerSig and iLonger, title = 's-longer', location = location.belowbar, color = color.new(color.green, 0), style = shape.triangleup, text = 's-longer', textcolor = color.new(color.green, 0))


//bubble sig
iBullishZscore = input.bool(defval = false, title = 'bullish', display = display.none, group = 'bubble', inline = 'bubble1')
iBearishZscore = input.bool(defval = false, title = 'bearish', display = display.none, group = 'bubble', inline = 'bubble1')
iZScore2ndMaLength = input.int(21, 'Z-Score 2nd MA Length (short)', minval = 3, maxval = 21, display = display.none, group = 'bubble')
iZScore2ndMaMinScore = input.float(2.3, 'Min. zScore', minval = 1.0, maxval = 14, step = 0.1, display = display.none, group = 'bubble')

zscoreVolCond = ta.ema(drelib.z_score(volume, iMainMaLength), iZScore2ndMaLength) >= iZScore2ndMaMinScore
zscoreEma = ta.ema(close, 2 * iZScore2ndMaLength / 3)
zscoreBullishSig = zscoreVolCond and zscoreEma > zscoreEma[1]
zscoreBearishSig = zscoreVolCond and zscoreEma < zscoreEma[1]

alertcondition(gFilter and zscoreBullishSig, title = 'DRE bubble up', message = 'bubble up')
alertcondition(gFilter and zscoreBearishSig, title = 'DRE bubble dn', message = 'bubble dn')
plotshape(zscoreBullishSig and iBullishZscore, title = 'bubble up', location = location.belowbar, color = color.new(color.gray, 0), style = shape.xcross, text = 'bubble up', textcolor = color.new(color.gray, 0))
plotshape(zscoreBearishSig and iBearishZscore, title = 'bubble dn', location = location.belowbar, color = color.new(color.gray, 0), style = shape.xcross, text = 'bubble dn', textcolor = color.new(color.gray, 0))


//hunter sig
iBullishHunter = input.bool(defval = false, title = 'bullish', display = display.none, group = 'hunter', inline = 'hunter1')
iBearishHunter = input.bool(defval = false, title = 'bearish', display = display.none, group = 'hunter', inline = 'hunter1')
iHunterGracePeriod = input.int(defval = 40, title = 'grace period', minval = 20, maxval = 200, display = display.none, group = 'hunter')
iHunterShort = input.bool(defval = true, title = 'short', display = display.none, group = 'hunter', inline = 'hunter2')
iHunterLookbackShort = input.int(defval = 250, title = 'lookback', minval = 50, maxval = 1000, display = display.none, group = 'hunter', inline = 'hunter2')
iHunterMid = input.bool(defval = true, title = 'mid', display = display.none, group = 'hunter', inline = 'hunter3')
iHunterLookbackMid = input.int(defval = 700, title = 'lookback', minval = 100, maxval = 1500, display = display.none, group = 'hunter', inline = 'hunter3')
iHunterLong = input.bool(defval = true, title = 'long', display = display.none, group = 'hunter', inline = 'hunter4')
iHunterLookbackLong = input.int(defval = 1300, title = 'lookback', minval = 200, maxval = 2000, display = display.none, group = 'hunter', inline = 'hunter4')

bullishHunterShortSig = drelib.sigBullSLHunter(mainAtr, iHunterLookbackShort, iHunterGracePeriod) and iHunterShort
bullishHunterMidSig = drelib.sigBullSLHunter(mainAtr, iHunterLookbackMid, iHunterGracePeriod) and iHunterMid
bullishHunterLongSig = drelib.sigBullSLHunter(mainAtr, iHunterLookbackLong, iHunterGracePeriod) and iHunterLong
bullishHunterSig = bullishHunterShortSig or bullishHunterMidSig or bullishHunterLongSig

bearishHunterShortSig = drelib.sigBearSLHunter(mainAtr, iHunterLookbackShort, iHunterGracePeriod) and iHunterShort 
bearishHunterMidSig = drelib.sigBearSLHunter(mainAtr, iHunterLookbackMid, iHunterGracePeriod) and iHunterMid
bearishHunterLongSig = drelib.sigBearSLHunter(mainAtr, iHunterLookbackLong, iHunterGracePeriod) and iHunterLong
bearishHunterSig = bearishHunterShortSig or bearishHunterMidSig or bearishHunterLongSig

alertcondition(gFilter and bullishHunterSig, title = 'DRE Bullish hunter', message = 'hunter')
alertcondition(gFilter and bearishHunterSig, title = 'DRE Bearish hunter', message = 'hunter')
plotshape(bullishHunterSig and iBullishHunter, title = 'bullish hunter', location = location.belowbar, color = color.new(color.green, 0), style = shape.triangleup, text = 'hunter', textcolor = color.new(color.green, 0))
plotshape(bearishHunterSig and iBearishHunter, title = 'bearish hunter', location = location.abovebar, color = color.new(color.red, 0), style = shape.triangledown, text = 'hunter', textcolor = color.new(color.red, 0))


//stepper sig
iBullishStepper = input.bool(defval = false, title = 'bullish', display = display.none, group = 'stepper')
iBullishLongerStepper = input.bool(defval = false, title = 'bullish longer stepper', display = display.none, group = 'stepper')
iStepperLookback = input.int(defval = 325, title = 'lookback', minval = 100, maxval = 750, step = 5, display = display.none, group = 'stepper')
iStepperMaDist = input.float(defval = 1.25, title = 'max vwap-ma dist.', minval = 0.0, maxval = 5.0, step = 0.25, display = display.none, group = 'stepper')
iLongerStepperDist = input.int(defval = 5, title = 'longer-stepper max. distance', minval = 0, maxval = 20, display = display.none, group = 'stepper')

bullishStepperSig = drelib.sigBullStepper(mainAtr, mainMa, iStepperLookback, iStepperMaDist)
bullishLongerStepperSig = ta.barssince(longerSig) <= iLongerStepperDist and bullishStepperSig
bullishSLongerStepperSig = ta.barssince(smallerLongerSig) <= 3 and bullishStepperSig

alertcondition(gFilter and bullishStepperSig, title = 'DRE Bullish stepper', message = 'stepper')
alertcondition(gFilter and bullishLongerStepperSig, title = 'DRE Bullish longer-stepper', message = 'l.stepper')
alertcondition(gFilter and bullishSLongerStepperSig, title = 'DRE Bullish s-longer-stepper', message = 's-l.stepper')
plotshape(bullishStepperSig and not bullishLongerStepperSig and iBullishStepper, title = 'bullish stepper', location = location.belowbar, color = color.new(color.green, 0), style = shape.triangleup, text = 'stepper', textcolor = color.new(color.green, 0))
plotshape(bullishLongerStepperSig and iBullishLongerStepper, title = 'bullish l.stepper', location = location.belowbar, color = color.new(color.green, 0), style = shape.triangleup, text = 'l.stepper', textcolor = color.new(color.green, 0))
plotshape(bullishSLongerStepperSig and iBullishLongerStepper, title = 'bullish s-l.stepper', location = location.belowbar, color = color.new(color.green, 0), style = shape.triangleup, text = 's-l.stepper', textcolor = color.new(color.green, 0))


//obv sig
iBullishObv = input.bool(defval = false, title = 'bullish', display = display.none, group = 'obv', inline = 'obv1')
iBearishObv = input.bool(defval = false, title = 'bearish', display = display.none, group = 'obv', inline = 'obv1')
iObvMaLength = input.int(defval=100, title='Ma len.', minval=10, maxval=250, display = display.none, group='obv')
iObvSource = input.source(close, title = 'Source', display = display.none, group = 'obv')
iObvStdDevBand = input.float(defval = 0.35, title = 'StdDev.', minval = 0, maxval = 10.0, step = 0.05, display = display.none, group = 'obv')

func_obv(_source) =>
    ta.cum(math.sign(ta.change(_source)) * volume)

var cumVol = 0.
cumVol += nz(volume)
if barstate.islast and cumVol == 0
    runtime.error("No volume is provided by the data vendor.")

obv = func_obv(iObvSource)
obcMa = ta.sma(obv, iObvMaLength)
obvStdDev = ta.stdev(obv, iObvMaLength)
bullishObvCross = drelib.crossover2(obv, obcMa + iObvStdDevBand * obvStdDev)
bearishObvCross = drelib.crossunder2(obv, obcMa - iObvStdDevBand * obvStdDev)
bullishObvCrossSince = ta.barssince(bullishObvCross)
bearishObvCrossSince = ta.barssince(bearishObvCross)
bullishObvSig = bullishObvCross and bullishObvCrossSince[1] > bearishObvCrossSince[1]
bearishObvSig = bearishObvCross and bullishObvCrossSince[1] < bearishObvCrossSince[1]

alertcondition(gFilter and bullishObvSig, title = 'DRE Bullish obv', message = 'obv')
alertcondition(gFilter and bearishObvSig, title = 'DRE Bearish obv', message = 'obv')
plotshape(bullishObvSig and iBullishObv, title = 'bullish obv', location = location.belowbar, color = color.new(color.green, 0), style = shape.triangleup, text = 'obv', textcolor = color.new(color.green, 0))
plotshape(bearishObvSig and iBearishObv, title = 'bearish obv', location = location.abovebar, color = color.new(color.red, 0), style = shape.triangledown, text = 'obv', textcolor = color.new(color.red, 0))

//rmv sig
iBullishRmv = input.bool(defval = false, title = 'bullish', display = display.none, group = 'rmv', inline = 'rmv1')
iBearishRmv = input.bool(defval = false, title = 'bearish', display = display.none, group = 'rmv', inline = 'rmv1')
iBullishRmvPb = input.bool(defval = false, title = 'bullish-pb', display = display.none, group = 'rmv', inline = 'rmv2')
iBearishRmvPb = input.bool(defval = false, title = 'bearish-pb', display = display.none, group = 'rmv', inline = 'rmv2')
iRmvLookbackPeriod = input.int(30, minval = 1, title = 'Lookback Period', display = display.none, group = 'rmv')
iRmvShortLookback1 = input.int(13, minval = 1, title = 'Short-term ATR Lookback 1', display = display.none, group = 'rmv')
iRmvShortLookback2 = input.int(8, minval = 1, title = 'Short-term ATR Lookback 2', display = display.none, group = 'rmv')
iRmvshortLookback3 = input.int(5, minval = 1, title = 'Short-term ATR Lookback 3', display = display.none, group = 'rmv')
iRmvLowLevel = input.int(25, title = 'Low Level Threshold', display = display.none, group = 'rmv')
iRmvPbLen = input.int(11, title = 'Pullback Len.', display = display.none, group = 'rmv')

func_rmv(_artShortLen1, _artShortLen2, _artShortLen3, _MainLookback) =>
    shortAtrAvg = (ta.atr(_artShortLen1) + ta.atr(_artShortLen2) + ta.atr(_artShortLen3)) / 3
    highestShortAvg = ta.highest(shortAtrAvg, _MainLookback)
    lowestShortAvg = ta.lowest(shortAtrAvg, _MainLookback)
    result = (shortAtrAvg - lowestShortAvg) / math.max(highestShortAvg - lowestShortAvg, 0.001) * 100
    result

rmv = func_rmv(iRmvShortLookback1, iRmvShortLookback2, iRmvshortLookback3, iRmvLookbackPeriod)
lowRmv = rmv <= iRmvLowLevel
highRmv = rmv >= 100 - iRmvLowLevel / 2
earnings = request.earnings(ticker = syminfo.tickerid, field = earnings.actual)
earningsSig = earnings != earnings[1]

rmvCond = lowRmv[1] and not lowRmv or highRmv and lowRmv[2] or rmv == 100 and lowRmv[3]
bullishRmvSig = rmvCond and close > close[2] and volume > gVolMa and close > gVShortMa1 and close > gVShortMa2 and close > shortMa
bullishRmvPbAgo = ta.barssince(bullishRmvSig)
bullishRmvPbSig = not bullishRmvSig and bullishRmvPbAgo <= iRmvPbLen and drelib.crossover(low[bullishRmvPbAgo])
bearishRmvSig = rmvCond and close < close[2] and volume > gVolMa and close < gVShortMa1 and close < gVShortMa2 and close < shortMa
bearishRmvPbAgo = ta.barssince(bearishRmvSig)
bearishRmvPbSig = not bearishRmvSig and bearishRmvPbAgo <= iRmvPbLen and drelib.crossunder(high[bearishRmvPbAgo])

alertcondition(gFilter and bullishRmvSig, title = 'DRE Bullish rmv', message = 'rmv')
alertcondition(gFilter and bullishRmvPbSig, title = 'DRE Bullish rmv-pb', message = 'rmv-pb')
alertcondition(gFilter and bearishRmvSig, title = 'DRE Bearish rmv', message = 'rmv')
alertcondition(gFilter and bearishRmvPbSig, title = 'DRE Bearish rmv-pb', message = 'rmv-pb')
//plotshape(bullishRmvSig and iBullishRmv, title = 'bullish rmv', location = location.belowbar, color = color.new(color.green, 0), style = shape.triangleup, text = 'rmv', textcolor = color.new(color.green, 0))
//plotshape(bullishRmvPbSig and iBullishRmvPb, title = 'bullish rmv-pb', location = location.belowbar, color = color.new(color.green, 0), style = shape.triangleup, text = 'rmv-pb', textcolor = color.new(color.green, 0))
//plotshape(bullishRmvEarningsSig and iBullishRmvEarnings, title = 'bullish rmv-e', location = location.belowbar, color = color.new(color.green, 0), style = shape.triangleup, text = 'rmv-e', textcolor = color.new(color.green, 0))
//plotshape(bullishRmvEarningsPbSig and iBullishRmvEarningsPb, title = 'bullish rmv-e-pb', location = location.belowbar, color = color.new(color.green, 0), style = shape.triangleup, text = 'rmv-e-pb', textcolor = color.new(color.green, 0))
//plotshape(bearishRmvSig and iBearishRmv, title = 'bearish rmv', location=location.abovebar, color = color.new(color.red, 0), style = shape.triangledown, text = 'rmv', textcolor = color.new(color.red, 0))
//plotshape(bearishRmvPbSig and iBearishRmvPb, title = 'bearish rmv-pb', location=location.abovebar, color = color.new(color.red, 0), style = shape.triangledown, text = 'rmv-pb', textcolor = color.new(color.red, 0))
//plotshape(bearishRmvEarningsSig and iBearishRmvEarnings, title = 'bearish rmv-e', location=location.abovebar, color = color.new(color.red, 0), style = shape.triangledown, text = 'rmv-e', textcolor = color.new(color.red, 0))
//plotshape(bearishRmvEarningsPbSig and iBearishRmvEarningsPb, title = 'bearish rmv-e-pb', location=location.abovebar, color = color.new(color.red, 0), style = shape.triangledown, text = 'rmv-e-pb', textcolor = color.new(color.red, 0))


//mtb sig (Minevrini + Trigger Bar / Shakeout Demand Tail / Gap Down Reversal)
iBullishMtb = input.bool(defval = false, title = 'bullish', display = display.none, group = 'mtb', inline = 'mtb1')
iMaxDistFromMaPctRank = input.int(defval = 10, title = 'Max. distance from MA', minval = 1, maxval = 99, display = display.none, group = 'mtb')
iTriggerBarMaxPercentile = input.int(defval = 30, title = 'Trigger Bar max. percentiles', minval = 1, maxval = 99, display = display.none, group = 'mtb')

sma50 = ta.sma(close, 50)
sma150 = ta.sma(close, 150)
sma200 = ta.sma(close, 200)
yearlyHigh = ta.highest(252)
yearlyLow = ta.lowest(252)
// shares = request.financial(syminfo.tickerid, "TOTAL_SHARES_OUTSTANDING", "FQ") // max 30M shares

//Minevrini trend
sma200GoingUp_10 = sma200 > sma200[1] ? 1 : 0
sma200GoingUpCond = math.sum(sma200GoingUp_10, 60) > 30
maCond = close > sma150 and close > sma200 and sma50 > sma150 and sma150 > sma200 and sma200 > sma200[1]
loHiCond = close > 1.25 * yearlyLow and close > yearlyHigh / 1.25
sma50Cond = close > sma50 / 1.08
 // and RS Score > 70
benchmark = request.security("SPY", timeframe.period, close)
simpleRelativeStrengthCond = close / benchmark > close[126] / benchmark[126] and close / benchmark > close[63] / benchmark[63]
minevriniTrendCond = maCond and loHiCond and sma50Cond and sma200GoingUpCond and simpleRelativeStrengthCond

//Jack Corsellis - Trigger Bar
candleHeight = high - low
candleHeightPrctRank = ta.percentrank(candleHeight, 50)
latestHigh = math.max(nz(math.abs(ta.highestbars(50)), 1), 50)
volumePrctRank = ta.percentrank(volume, latestHigh)
shortMaDistPrctRank = ta.percentrank(math.abs(ohlc4 - shortMa), 50)
maDistCond = shortMaDistPrctRank < iMaxDistFromMaPctRank
triggerBarCond = candleHeightPrctRank < iTriggerBarMaxPercentile and volumePrctRank < iTriggerBarMaxPercentile and maDistCond
bodySize = math.abs((open - close) / (high - low))
lowerWickSize = math.abs((low - math.min(open, close)) / (high - low))
hammerCandle = bodySize < 0.2 and lowerWickSize > 0.7
shakeoutDemandTailCond = hammerCandle and candleHeightPrctRank > 50 and volumePrctRank > 50 and maDistCond
gapDownReversalCandle = close[1] < open[1] and open < close[1] and close > close[1] and bodySize > bodySize[1]
gapDownReversalCond = gapDownReversalCandle and candleHeightPrctRank > 50 and volumePrctRank > 50 and maDistCond

mtbSig = ta.barssince(minevriniTrendCond) < 15 and (triggerBarCond or shakeoutDemandTailCond and gapDownReversalCond)

alertcondition(gFilter and mtbSig, title = 'DRE Bullish mtb', message = 'mtb')
plotshape(mtbSig and iBullishMtb, title = 'bullish mtb', location = location.belowbar, color = color.new(color.green, 0), style = shape.triangleup, text = 'mtb', textcolor = color.new(color.green, 0))

//price - volume corelation
iPcvMinCorrelation = input.float(defval = 0.75, title = 'PCV - min. correlation', minval = -1.0, maxval = 1.0, step = 0.05, display = display.none, group = 'price-vol. corralation')
priceMa = ta.ema(close, 50)
volumeMa = ta.ema(volume, 50)
pvCorrelation = ta.correlation(priceMa, volumeMa, 50)
pvc = priceMa > priceMa[1] and pvCorrelation > iPcvMinCorrelation
pvc2 = pvc and gVShortMa1 > gVShortMa2 and close > shortMa
//end

bullishRmvSigs = bullishRmvSig or bullishRmvPbSig
bearishRmvSigs = bearishRmvSig or bearishRmvPbSig
bullishSig = juniorSig or bullishStarterSig or bullishFireStarterSig or bullishHunterSig or longerSig or bullishStepperSig or bullishLongerStepperSig or bullishObvSig or bullishRmvSigs or mtbSig
bearishSig = topSig or bearishStarterSig or bearishHunterSig or bearishObvSig or bearishRmvSigs

alertcondition(gFilter and bullishSig, title = 'DRE Bullish pattern sig', message = 'bullish pattern')
alertcondition(gFilter and bearishSig, title = 'DRE Bearish pattern sig', message = 'bearish pattern')

alertcondition(gFilter and (bullishSig or bearishSig), title = 'DRE ALL pattern sig', message = 'all patterns')


iBoVolumeMultiple = input.float(defval = 2.0, title = 'Breakout volume multiple', minval = 0.0, maxval = 5.0, step = 0.1, display = display.none, group = 'Breakout parameters')
iBoMaxRiskPct = input.float(defval = 7.0, title = 'Breakout max risk', minval = 0.0, maxval = 12.0, step = 0.5, display = display.none, group = 'Breakout parameters')

currCandleRelativeVol(int _iMaLength) =>
    candleVolPart = volume / ta.sma(volume, _iMaLength)
    candleTimePart = (math.min(timenow, time_close) - time) / (time_close - time)
    relativeVol = candleVolPart / candleTimePart
    relativeVol

candleRelativeVol = currCandleRelativeVol(iShortMaLength)
bullishRisk = 100 * (close / low[1] - 1)
bearisjRisk = 100 * (close / high[1] - 1)
candleBullishBoOnVolumeCond = close > high[1] and candleRelativeVol > iBoVolumeMultiple and bullishRisk < iBoMaxRiskPct
candleBearishBoOnVolumeCond = close < low[1] and candleRelativeVol > iBoVolumeMultiple and bearisjRisk < iBoMaxRiskPct

alertcondition(candleBullishBoOnVolumeCond and gFilter and mtbSig[1], title = 'DRE Bullish mtb BO sig', message = 'bullish mtb BO')
alertcondition(candleBullishBoOnVolumeCond and gFilter and bullishSig[1], title = 'DRE Bullish pattern BO sig', message = 'bullish pattern BO')
alertcondition(candleBearishBoOnVolumeCond and gFilter and bearishSig[1], title = 'DRE Bearish pattern BO sig', message = 'bearish pattern BO')

alertcondition(gFilter and (candleBullishBoOnVolumeCond and bullishSig[1] or candleBearishBoOnVolumeCond and bearishSig[1]), title = 'DRE ALL pattern BO sig', message = 'all patterns BO')

//only for general market turnaround (as William O'Neil)
iTurnaroundGo = input.bool(defval = false, title = "O'Neail big index turnaround GO", display = display.none, group = "William O'Neil turnaround and GO")
iTurnaroundExtremeAgo = input.int(defval = 45, title = "max. peak/bottom ago", minval = 20, maxval = 60, step = 5, display = display.none, group = "William O'Neil turnaround and GO")
iturnaroundGoDayMinRange = input.float(defval = 0.0, title = "min. day range", minval = 0.0, maxval = 10.0, step = 0.1, display = display.none, group = "William O'Neil turnaround and GO", tooltip = "Use 0 for auto calculation based on adr. \nfor adr < 0.017 uses 0.017\nfor adr >= 0.017 uses 0.017 + (adr - 0.017) / 4")
iTurnaroundMinGoDays = input.int(defval = 3, title = "min. days", minval = 1, maxval = 10, display = display.none, group = "William O'Neil turnaround and GO")

vol50sma = ta.sma(volume, 50)

adr = adrPct / 100
turnaroundGoDayMinRange = iturnaroundGoDayMinRange > 0.0 ? iturnaroundGoDayMinRange / 100 : (adr < 0.017 ? 0.017 : 0.017 + (adr - 0.017) / 4)

bullGoSig = drelib.sigWONTurnaroundUp(iTurnaroundExtremeAgo, iTurnaroundMinGoDays, turnaroundGoDayMinRange, mainMa, vol50sma)
plotshape(bullGoSig and iTurnaroundGo, title = 'bullish GO', location = location.belowbar, color = color.new(color.green, 0), style = shape.triangleup, text = 'GO', textcolor = color.new(color.green, 0))

bearGoSig = drelib.sigWONTurnaroundDn(iTurnaroundExtremeAgo, iTurnaroundMinGoDays, turnaroundGoDayMinRange, mainMa, vol50sma)
plotshape(bearGoSig and iTurnaroundGo, title = 'bearish GO', location = location.abovebar, color = color.new(color.red, 0), style = shape.triangledown, text = 'GO', textcolor = color.new(color.red, 0))

//firestarter - GO - sma200crossover
iFStarterGoSmaCrossover = input.bool(defval = false, title = "F.starter - GO - sma200crossover", display = display.none, group = "F.starter - GO - sma200crossover")
fstarterNotLongAgo = ta.barssince(bullishFireStarterSig) < 150
bollGoNotLongAgo = ta.barssince(bullGoSig) < 150
fstarterGoSmaCrossover = drelib.crossover(mainMa) and fstarterNotLongAgo and bollGoNotLongAgo
sma175 = ta.sma(close, 175)
fstarterGoSma175Crossover = drelib.crossover(sma175) and fstarterNotLongAgo and bollGoNotLongAgo
plotshape(fstarterGoSmaCrossover and iFStarterGoSmaCrossover, title = 'bullish fstarter-GO-CO', location = location.belowbar, color = color.new(color.green, 0), style = shape.triangleup, text = 'FS-GO-CO', textcolor = color.new(color.green, 0))
plotshape(fstarterGoSma175Crossover and iFStarterGoSmaCrossover, title = 'bullish fstarter-GO-CO175', location = location.belowbar, color = color.new(color.green, 0), style = shape.triangleup, text = 'FS-GO-CO2', textcolor = color.new(color.green, 0))

//check performance
//sig stats table
iMinSigSuccessRate = input.float(defval = 41.0, title = 'Min. sig success rate pct.', minval = 0.0, maxval = 100.0, step = 1.0, display = display.none, group = 'Signals')
iMinSigReturnAdrMultiple = input.float(defval = 0.9, title = 'Min. avg. return by ADR multiple', minval = -1.0, maxval = 5.0, step = 0.05, display = display.none, group = 'Signals')

adrCond = iMinSigReturnAdrMultiple * adrPct

// iShowSigPerfPlots = input.bool(defval = false, title = 'show plots', display = display.none, group = 'Sig. performnce check')
iShowSigPerfTable = input.bool(defval = false, title = 'show table', display = display.none, group = 'Sig. performnce check')
iShowOnlyGoodSigs = input.bool(defval = true, title = 'show only good sigs.', display = display.none, group = 'Sig. performnce check')
iGoSigsExtremeLen = input.int(defval = 2, title = 'lowest, highest len. for GO sigs.', display = display.none, group = 'Sig. performnce check')

showRow(_iShowOnlyGoodSigs, sigOk) =>
    _iShowOnlyGoodSigs and sigOk or not _iShowOnlyGoodSigs

lowestFew = ta.lowest(iGoSigsExtremeLen)
highestFew = ta.highest(iGoSigsExtremeLen)

[s1SuccRate, s1SuccCount, s1SigCount, s1AvgReturn, s1SuccRateOk, s1SuccRateStr, s1Score] = dreperf.successRateAllTimeStatsFull(juniorSig, juniorSig ? low : na, iMinSigSuccessRate, adrCond)
[s2SuccRate, s2SuccCount, s2SigCount, s2AvgReturn, s2SuccRateOk, s2SuccRateStr, s2Score] = dreperf.successRateAllTimeStatsFull(junior2Sig, junior2Sig ? low : na, iMinSigSuccessRate, adrCond)
[s3SuccRate, s3SuccCount, s3SigCount, s3AvgReturn, s3SuccRateOk, s3SuccRateStr, s3Score] = dreperf.successRateAllTimeStatsFull(juniorLateSig, juniorLateSig ? low : na, iMinSigSuccessRate, adrCond)
[s4SuccRate, s4SuccCount, s4SigCount, s4AvgReturn, s4SuccRateOk, s4SuccRateStr, s4Score] = dreperf.successRateAllTimeStatsFull(bullishStarterSig, bullishStarterSig ? low : na, iMinSigSuccessRate, adrCond)
[s5SuccRate, s5SuccCount, s5SigCount, s5AvgReturn, s5SuccRateOk, s5SuccRateStr, s5Score] = dreperf.successRateAllTimeStatsFull(bullishFireStarterSig, bullishFireStarterSig ? low : na, iMinSigSuccessRate, adrCond)
[s6SuccRate, s6SuccCount, s6SigCount, s6AvgReturn, s6SuccRateOk, s6SuccRateStr, s6Score] = dreperf.successRateAllTimeStatsFull(longerSig, longerSig ? low : na, iMinSigSuccessRate, adrCond)
[s7SuccRate, s7SuccCount, s7SigCount, s7AvgReturn, s7SuccRateOk, s7SuccRateStr, s7Score] = dreperf.successRateAllTimeStatsFull(smallerLongerSig, smallerLongerSig ? low : na, iMinSigSuccessRate, adrCond)
[s8SuccRate, s8SuccCount, s8SigCount, s8AvgReturn, s8SuccRateOk, s8SuccRateStr, s8Score] = dreperf.successRateAllTimeStatsFull(bullishStepperSig, bullishStepperSig ? low : na, iMinSigSuccessRate, adrCond)
[s9SuccRate, s9SuccCount, s9SigCount, s9AvgReturn, s9SuccRateOk, s9SuccRateStr, s9Score] = dreperf.successRateAllTimeStatsFull(bullishLongerStepperSig, bullishLongerStepperSig ? low : na, iMinSigSuccessRate, adrCond)
[s10SuccRate, s10SuccCount, s10SigCount, s10AvgReturn, s10SuccRateOk, s10SuccRateStr, s10Score] = dreperf.successRateAllTimeStatsFull(bullishSLongerStepperSig, bullishSLongerStepperSig ? low : na, iMinSigSuccessRate, adrCond)
[s11SuccRate, s11SuccCount, s11SigCount, s11AvgReturn, s11SuccRateOk, s11SuccRateStr, s11Score] = dreperf.successRateAllTimeStatsFull(bullishObvSig, bullishObvSig ? low : na, iMinSigSuccessRate, adrCond)
[s12SuccRate, s12SuccCount, s12SigCount, s12AvgReturn, s12SuccRateOk, s12SuccRateStr, s12Score] = dreperf.successRateAllTimeStatsFull(bullishRmvSig, bullishRmvSig ? low : na, iMinSigSuccessRate, adrCond)
[s13SuccRate, s13SuccCount, s13SigCount, s13AvgReturn, s13SuccRateOk, s13SuccRateStr, s13Score] = dreperf.successRateAllTimeStatsFull(fstarterGoSma175Crossover, fstarterGoSma175Crossover ? lowestFew : na, iMinSigSuccessRate, adrCond)
[s14SuccRate, s14SuccCount, s14SigCount, s14AvgReturn, s14SuccRateOk, s14SuccRateStr, s14Score] = dreperf.successRateAllTimeStatsFull(mtbSig, mtbSig ? low : na, iMinSigSuccessRate, adrCond)
[s15SuccRate, s15SuccCount, s15SigCount, s15AvgReturn, s15SuccRateOk, s15SuccRateStr, s15Score] = dreperf.successRateAllTimeStatsFull(pvc, pvc ? low : na, iMinSigSuccessRate, adrCond)
[s16SuccRate, s16SuccCount, s16SigCount, s16AvgReturn, s16SuccRateOk, s16SuccRateStr, s16Score] = dreperf.successRateAllTimeStatsFull(pvc2, pvc2 ? low : na, iMinSigSuccessRate, adrCond)
[s17SuccRate, s17SuccCount, s17SigCount, s17AvgReturn, s17SuccRateOk, s17SuccRateStr, s17Score] = dreperf.successRateAllTimeStatsFull(bullishHunterSig, bullishHunterSig ? low : na, iMinSigSuccessRate, adrCond)
[s18SuccRate, s18SuccCount, s18SigCount, s18AvgReturn, s18SuccRateOk, s18SuccRateStr, s18Score] = dreperf.successRateAllTimeStatsFull(bearishHunterSig, bearishHunterSig ? high : na, false, iMinSigSuccessRate, adrCond)
[s19SuccRate, s19SuccCount, s19SigCount, s19AvgReturn, s19SuccRateOk, s19SuccRateStr, s19Score] = dreperf.successRateAllTimeStatsFull(bullGoSig, bullGoSig ? lowestFew : na, iMinSigSuccessRate, adrCond)
[s20SuccRate, s20SuccCount, s20SigCount, s20AvgReturn, s20SuccRateOk, s20SuccRateStr, s20Score] = dreperf.successRateAllTimeStatsFull(bearGoSig, bearGoSig ? highestFew : na, false, iMinSigSuccessRate, adrCond)
[s21SuccRate, s21SuccCount, s21SigCount, s21AvgReturn, s21SuccRateOk, s21SuccRateStr, s21Score] = dreperf.successRateAllTimeStatsFull(fstarterGoSmaCrossover, fstarterGoSmaCrossover ? lowestFew : na, iMinSigSuccessRate, adrCond)


if barstate.islast and iShowSigPerfTable
    var tbl = table.new(position = position.top_right, columns = 2, rows = 23)
    txtSize = size.small
    table.cell(table_id = tbl, column = 0, row = 0, text = '')
    table.cell(table_id = tbl, column = 1, row = 0, text = '')
    table.cell(table_id = tbl, column = 0, row = 1, text = "sig", text_size = txtSize)
    table.cell(table_id = tbl, column = 1, row = 1, text = str.format("perf {0,number,#.#} {1,number,#.#}", iMinSigSuccessRate, adrCond), text_size = txtSize)

    if showRow(iShowOnlyGoodSigs, s1SuccRateOk)
        table.cell(table_id = tbl, column = 0, row = 2, text = "junior", text_size = txtSize)
        table.cell(table_id = tbl, column = 1, row = 2, text = s1SuccRateStr, text_size = txtSize)
    if showRow(iShowOnlyGoodSigs, s2SuccRateOk)
        table.cell(table_id = tbl, column = 0, row = 3, text = "junior2", text_size = txtSize)
        table.cell(table_id = tbl, column = 1, row = 3, text = s2SuccRateStr, text_size = txtSize)
    if showRow(iShowOnlyGoodSigs, s3SuccRateOk)
        table.cell(table_id = tbl, column = 0, row = 4, text = "late-junior", text_size = txtSize)
        table.cell(table_id = tbl, column = 1, row = 4, text = s3SuccRateStr, text_size = txtSize)
    if showRow(iShowOnlyGoodSigs, s4SuccRateOk)
        table.cell(table_id = tbl, column = 0, row = 5, text = "Starter", text_size = txtSize)
        table.cell(table_id = tbl, column = 1, row = 5, text = s4SuccRateStr, text_size = txtSize)
    if showRow(iShowOnlyGoodSigs, s5SuccRateOk)
        table.cell(table_id = tbl, column = 0, row = 6, text = "FireStarter", text_size = txtSize)
        table.cell(table_id = tbl, column = 1, row = 6, text = s5SuccRateStr, text_size = txtSize)
    if showRow(iShowOnlyGoodSigs, s6SuccRateOk)
        table.cell(table_id = tbl, column = 0, row = 7, text = "longer", text_size = txtSize)
        table.cell(table_id = tbl, column = 1, row = 7, text = s6SuccRateStr, text_size = txtSize)
    if showRow(iShowOnlyGoodSigs, s7SuccRateOk)
        table.cell(table_id = tbl, column = 0, row = 8, text = "s-longer", text_size = txtSize)
        table.cell(table_id = tbl, column = 1, row = 8, text = s7SuccRateStr, text_size = txtSize)
    if showRow(iShowOnlyGoodSigs, s8SuccRateOk)
        table.cell(table_id = tbl, column = 0, row = 9, text = "Stepper", text_size = txtSize)
        table.cell(table_id = tbl, column = 1, row = 9, text = s8SuccRateStr, text_size = txtSize)
    if showRow(iShowOnlyGoodSigs, s9SuccRateOk)
        table.cell(table_id = tbl, column = 0, row = 10, text = "LongerStepper", text_size = txtSize)
        table.cell(table_id = tbl, column = 1, row = 10, text = s9SuccRateStr, text_size = txtSize)
    if showRow(iShowOnlyGoodSigs, s10SuccRateOk)
        table.cell(table_id = tbl, column = 0, row = 11, text = "s-LongerStepper", text_size = txtSize)
        table.cell(table_id = tbl, column = 1, row = 11, text = s10SuccRateStr, text_size = txtSize)
    if showRow(iShowOnlyGoodSigs, s11SuccRateOk)
        table.cell(table_id = tbl, column = 0, row = 12, text = "obv", text_size = txtSize)
        table.cell(table_id = tbl, column = 1, row = 12, text = s11SuccRateStr, text_size = txtSize)
    if showRow(iShowOnlyGoodSigs, s12SuccRateOk)
        table.cell(table_id = tbl, column = 0, row = 13, text = "rmv", text_size = txtSize)
        table.cell(table_id = tbl, column = 1, row = 13, text = s12SuccRateStr, text_size = txtSize)
    if showRow(iShowOnlyGoodSigs, s13SuccRateOk)
        table.cell(table_id = tbl, column = 0, row = 14, text = "FS-GO-CO2", text_size = txtSize)
        table.cell(table_id = tbl, column = 1, row = 14, text = s13SuccRateStr, text_size = txtSize)
    if showRow(iShowOnlyGoodSigs, s14SuccRateOk)
        table.cell(table_id = tbl, column = 0, row = 15, text = "mtb", text_size = txtSize)
        table.cell(table_id = tbl, column = 1, row = 15, text = s14SuccRateStr, text_size = txtSize)
    if showRow(iShowOnlyGoodSigs, s15SuccRateOk)
        table.cell(table_id = tbl, column = 0, row = 16, text = "pvc", text_size = txtSize)
        table.cell(table_id = tbl, column = 1, row = 16, text = s15SuccRateStr, text_size = txtSize)
    if showRow(iShowOnlyGoodSigs, s16SuccRateOk)
        table.cell(table_id = tbl, column = 0, row = 17, text = "pvc2", text_size = txtSize)
        table.cell(table_id = tbl, column = 1, row = 17, text = s16SuccRateStr, text_size = txtSize)
    if showRow(iShowOnlyGoodSigs, s17SuccRateOk)
        table.cell(table_id = tbl, column = 0, row = 18, text = "bullishHunter", text_size = txtSize)
        table.cell(table_id = tbl, column = 1, row = 18, text = s17SuccRateStr, text_size = txtSize)
    if showRow(iShowOnlyGoodSigs, s18SuccRateOk)
        table.cell(table_id = tbl, column = 0, row = 19, text = "bearishHunter", text_size = txtSize)
        table.cell(table_id = tbl, column = 1, row = 19, text = s18SuccRateStr, text_size = txtSize)
    if showRow(iShowOnlyGoodSigs, s19SuccRateOk)
        table.cell(table_id = tbl, column = 0, row = 20, text = "WON-bullGO", text_size = txtSize)
        table.cell(table_id = tbl, column = 1, row = 20, text = s19SuccRateStr, text_size = txtSize)
    if showRow(iShowOnlyGoodSigs, s20SuccRateOk)
        table.cell(table_id = tbl, column = 0, row = 21, text = "WON-bearGO", text_size = txtSize)
        table.cell(table_id = tbl, column = 1, row = 21, text = s20SuccRateStr, text_size = txtSize)
    if showRow(iShowOnlyGoodSigs, s21SuccRateOk)
        table.cell(table_id = tbl, column = 0, row = 22, text = "FS-GO-CO", text_size = txtSize)
        table.cell(table_id = tbl, column = 1, row = 22, text = s21SuccRateStr, text_size = txtSize)
