// This Pine Script® code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © drebel
//calc_bars_count = 3024 (12 years of 252 bars/year) - no need for more

//@version=6
indicator("early trend strong breakout", overlay = true, calc_bars_count = 12 * 252)

import drebel/DRELib/39 as drelib
import drebel/DREPerf/24 as dreperf

//common filters inputs
iGeneralFilterCond = input.bool(defval = true, title = 'Filter ON', display = display.none, group = 'General filter for signal')
iMinTurnover = input.float(defval = 0.20, title = 'Min. Turnover[M]', minval = 0.2, display = display.none, group = 'General filter for signal')
iMinAdr = input.float(defval = 3, title = 'Min. ADR[%]', minval = 0, step = 0.2, display = display.none, group = 'General filter for signal')
iMinPrice = input.float(defval = 1.0, title = 'Min.-max. price', minval = 0, display = display.none, inline = 'min max price', group = 'General filter for signal')
iMaxPrice = input.float(defval = 1750.0, title = '-', minval = 0, display = display.none, inline = 'min max price', group = 'General filter for signal')
iMaxDistFromLoDPct = input.int(defval = 67, title = 'Max. distance from LoD [%]', minval = 0, maxval = 300, step = 5, display = display.none, group = 'General filter for signal')
iMinBenchmarkNotBearishSince = input.int(defval = 31, title = 'Min. days from benchmark bearish', minval = 0, maxval = 63, display = display.none, group = 'General filter for signal')

//sig success rate filter
iShowEt3sbSig = input.bool(defval = true, title = 'Show et3sb', display = display.none, group = 'Signals')
iShowEt4sbSig = input.bool(defval = true, title = 'Show et4sb', display = display.none, group = 'Signals')
iShowRmv1Sig = input.bool(defval = true, title = 'Show rmv', display = display.none, group = 'Signals', inline = "rmv")
iShowRmv2Sig = input.bool(defval = true, title = '2', display = display.none, group = 'Signals', inline = "rmv")
iShowRmv3Sig = input.bool(defval = true, title = '3', display = display.none, group = 'Signals', inline = "rmv")
iShowEtc1sbSig = input.bool(defval = true, title = 'Show etcsb', display = display.none, group = 'Signals', inline = "etcsb")
iShowEtc2sbSig = input.bool(defval = true, title = 'c2', display = display.none, group = 'Signals', inline = "etcsb")
iShowEtc3sbSig = input.bool(defval = true, title = 'c3', display = display.none, group = 'Signals', inline = "etcsb")
iShowObvDivSig = input.bool(defval = true, title = 'Show Obv-Div-sb', display = display.none, group = 'Signals')
iShowMinevriniTrendSig = input.bool(defval = true, title = 'Show MinevriniTrend-contr-sb', display = display.none, group = 'Signals', inline = "mtsb")
iShowMinevriniTrendC1Sig = input.bool(defval = true, title = 'c1', display = display.none, group = 'Signals', inline = "mtsb")
iShowMinevriniTrendC2Sig = input.bool(defval = true, title = 'c2', display = display.none, group = 'Signals', inline = "mtsb")
iShowMinevriniTrendC3Sig = input.bool(defval = true, title = 'c3', display = display.none, group = 'Signals', inline = "mtsb")
iShowRagPb = input.bool(defval = true, title = 'Show RAG-pb', display = display.none, group = 'Signals')
iShowWONHP = input.bool(defval = true, title = "Show O''Neil Inspired: hi-percentiles", display = display.none, group = 'Signals')
iShowWONTurnaroundGo = input.bool(defval = true, title = "Show O''Neil Inspired: turnaround GO", display = display.none, group = 'Signals')
iShowMinVwapTAG = input.bool(defval = true, title = "Show Min Vwap TouchAndGo", display = display.none, group = 'Signals')
iShowMinVwapTAGDebug = input.bool(defval = true, title = "Show Min Vwap TouchAndGo - debug", display = display.none, group = 'Signals')

iSigCheckTime = input.int(defval = 15, title = 'Signal check time', minval = 5, maxval = 200, display = display.none, group = 'Signals')
iSigStopLossDay = input.int(defval = 0, title = 'Stop loss (day of low)', minval = 0, maxval = 5, display = display.none, group = 'Signals')
iMinSigSuccessRate = input.float(defval = 41.0, title = 'Min. sig success rate pct.', minval = 0.0, maxval = 100.0, step = 1.0, display = display.none, group = 'Signals')
iMinSigReturnAdrMultiple = input.float(defval = 0.9, title = 'Min. avg. return by ADR multiple', minval = -1.0, maxval = 5.0, step = 0.05, display = display.none, group = 'Signals')

//common filters calculations 
int sigMod = drelib.getWideIndexAndSectorSignalMod(iMinBenchmarkNotBearishSince)
bool generalFilter = drelib.generalFilter(iMinTurnover, iMinAdr, iMinPrice, iMaxPrice, 30, iMaxDistFromLoDPct, sigMod)
bool gFilter = generalFilter and iGeneralFilterCond or not iGeneralFilterCond

adrPct = 100.0 * (ta.sma(high / low, 100) - 1)
adrCond = iMinSigReturnAdrMultiple * adrPct

var series float benchIdx = drelib.getDefaultBenchmarkClose()
rs = close / benchIdx
rsMa = ta.sma(rs, 100)
rsCondRaw = rs > rsMa
rsCond_10 = rsCondRaw ? 1 : 0

obvCondRaw = drelib.isAboveObvSmaStddev(100, 0.35)
obvCond_10 = obvCondRaw ? 1 : 0

[nonBrokenLowsPct, nonBrokenHighsPct, nonBrokenExtremesPct, lowsHighsRatio] = drelib.nonBrokenExtremesPct(100)
nbeCondRaw = nonBrokenLowsPct > nonBrokenHighsPct and nonBrokenExtremesPct >= 10
nbeCond_10 = nbeCondRaw ? 1 : 0

iBreakoutLookback = input.int(defval = 7, title = 'Min. breakout lookback', minval = 1, maxval = 21, display = display.none, group = 'Breakout params')
iBreakoutMultiples = input.bool(defval = true, title = 'Use also multiples of lookback', display = display.none, group = 'Breakout params')
iInitialMinVolumePct = input.int(defval = 600, title = 'Initial min. relative volume Pct.', minval = 100, display = display.none, group = 'Breakout params')
iDayEndMinVolumePct = input.int(defval = 125, title = 'Day end min. relative volume Pct.', minval = 100, display = display.none, group = 'Breakout params')

sigMod += nonBrokenExtremesPct <= 14 ? -1 : 0
strongBreakout = drelib.strongBreakout(iBreakoutLookback, iBreakoutMultiples, iInitialMinVolumePct, iDayEndMinVolumePct, sigMod, true)

aboveIchimokuCloudCondRaw = drelib.isAboveIchimokuCloud()
aboveIchimokuCloudCond_10 = aboveIchimokuCloudCondRaw ? 1 : 0

totalCond = 4
etCondSum = rsCond_10 + obvCond_10 + aboveIchimokuCloudCond_10 + nbeCond_10
et3 = etCondSum == totalCond - 1
et4 = etCondSum == totalCond
et3sb = et3 and strongBreakout
et4sb = et4 and strongBreakout
etsb = et3sb or et4sb

//Qullamaggie inspired - additionali signal if there is an OpeningRangeBrakeout the next day after main signal
//for low turnover 60 minute orb, for mid-high turnover 5 minute orb
minTurnoverForOrb5 = drelib.minTurnoverOk(10 * iMinTurnover, 30)
orb5 = drelib.openingRangeBreakout(5, true, true)
orb60 = drelib.openingRangeBreakout(60, true, true)
orb = minTurnoverForOrb5 ? orb5 : orb60

//pct time since session beggining 
dttTime = drelib.dttTimePct()

//rmv sig (like in "DRE parabolic top" v444)
iRmvMinVolumeMultiple = input.float(defval = 1.15, title = 'Rmv volume multiple', minval = 0.0, maxval = 3.0, step = 0.05, display = display.none, group = 'Contraction (RMV)')

iContr1RmvMainLookback = input.int(defval = 13, title = 'Lookbacks (main/s1/s2/s3)', minval = 8, maxval = 200, display = display.none, inline = 'rmv lookbacks', group = 'Contraction (RMV) params 1 (v. short)')
iContr1RmvS1Lookback = input.int(defval = 5, title = '', minval = 1, maxval = 50, display = display.none, inline = 'rmv lookbacks', group = 'Contraction (RMV) params 1 (v. short)')
iContr1RmvS2Lookback = input.int(defval = 3, title = '', minval = 1, maxval = 50, display = display.none, inline = 'rmv lookbacks', group = 'Contraction (RMV) params 1 (v. short)')
iContr1RmvS3Lookback = input.int(defval = 2, title = '', minval = 1, maxval = 50, display = display.none, inline = 'rmv lookbacks', group = 'Contraction (RMV) params 1 (v. short)')
iContr1MaxBarsSinceContraction = input.int(defval = 2, title = 'Max. bars since contraction', minval = 0, display = display.none, group = 'Contraction (RMV) params 1 (v. short)')

iContr2RmvMainLookback = input.int(defval = 21, title = 'Lookbacks (main/s1/s2/s3)', minval = 10, maxval = 200, display = display.none, inline = 'rmv lookbacks', group = 'Contraction (RMV) params 2 (short)')
iContr2RmvS1Lookback = input.int(defval = 8, title = '', minval = 1, maxval = 50, display = display.none, inline = 'rmv lookbacks', group = 'Contraction (RMV) params 2 (short)')
iContr2RmvS2Lookback = input.int(defval = 5, title = '', minval = 1, maxval = 50, display = display.none, inline = 'rmv lookbacks', group = 'Contraction (RMV) params 2 (short)')
iContr2RmvS3Lookback = input.int(defval = 3, title = '', minval = 1, maxval = 50, display = display.none, inline = 'rmv lookbacks', group = 'Contraction (RMV) params 2 (short)')
iContr2MaxBarsSinceContraction = input.int(defval = 3, title = 'Max. bars since contraction', minval = 0, display = display.none, group = 'Contraction (RMV) params 2 (short)')

iContr3RmvMainLookback = input.int(defval = 55, title = 'Lookbacks (main/s1/s2/s3)', minval = 10, maxval = 200, display = display.none, inline = 'rmv lookbacks', group = 'Contraction (RMV) params 3 (medium)')
iContr3RmvS1Lookback = input.int(defval = 34, title = '', minval = 1, maxval = 50, inline = 'rmv lookbacks', display = display.none, group = 'Contraction (RMV) params 3 (medium)')
iContr3RmvS2Lookback = input.int(defval = 21, title = '', minval = 1, maxval = 50, inline = 'rmv lookbacks', display = display.none, group = 'Contraction (RMV) params 3 (medium)')
iContr3RmvS3Lookback = input.int(defval = 13, title = '', minval = 1, maxval = 50, inline = 'rmv lookbacks', display = display.none, group = 'Contraction (RMV) params 3 (medium)')
iContr3MaxBarsSinceContraction = input.int(defval = 5, title = 'Max. bars since contraction', minval = 0, display = display.none, group = 'Contraction (RMV) params 3 (medium)')

shortMa = ta.sma(close, 50)
mainMa = ta.sma(close, 200)
gVShortMa1 = ta.ema(close, 10)
gVolMa = ta.sma(volume, 30)
gVol50Ma = ta.sma(volume, 50)
rmvLowLevel = 25
otherRmvCond = close > close[2] and volume > iRmvMinVolumeMultiple * gVolMa and close > gVShortMa1 and close > shortMa and dttTime > 0.85

rmvContraction1 = drelib.rmv(iContr1RmvMainLookback, iContr1RmvS1Lookback, iContr1RmvS2Lookback, iContr1RmvS3Lookback)
lowRmv1 = rmvContraction1 <= rmvLowLevel
highRmv1 = rmvContraction1 >= 100 - rmvLowLevel / 2
rmv1Cond = not lowRmv1 and lowRmv1[1] or highRmv1 and lowRmv1[2] or rmvContraction1 == 100 and lowRmv1[3]
bullishRmv1 = rmv1Cond and otherRmvCond

rmvContraction2 = drelib.rmv(iContr2RmvMainLookback, iContr2RmvS1Lookback, iContr2RmvS2Lookback, iContr2RmvS3Lookback)
lowRmv2 = rmvContraction2 <= rmvLowLevel
highRmv2 = rmvContraction2 >= 100 - rmvLowLevel / 2
rmv2Cond = not lowRmv2 and lowRmv2[1] or highRmv2 and lowRmv2[2] or rmvContraction2 == 100 and lowRmv2[3]
bullishRmv2 = rmv2Cond and otherRmvCond

rmvContraction3 = drelib.rmv(iContr3RmvMainLookback, iContr3RmvS1Lookback, iContr3RmvS2Lookback, iContr3RmvS3Lookback)
lowRmv3 = rmvContraction3 <= rmvLowLevel
highRmv3 = rmvContraction3 >= 100 - rmvLowLevel / 2
rmv3Cond = not lowRmv3 and lowRmv3[1] or highRmv3 and lowRmv3[2] or rmvContraction3 == 100 and lowRmv3[3]
bullishRmv3 = rmv3Cond and otherRmvCond


etc1sb = etsb and (rmv1Cond or lowRmv1)
etc2sb = etsb and (rmv2Cond or lowRmv2)
etc3sb = etsb and (rmv3Cond or lowRmv3)

iDivergence = input.int(50, title = 'Min. obv-price div. pct', minval = 0, maxval = 100, display = display.none, group = 'Signal: Obv-price divergence sb')
obvMa = ta.sma(ta.obv, 100)
priceMa = ta.sma(close, 100)
risingObv = obvMa > obvMa[1]
risingPrice = priceMa > priceMa[1]
divergence = risingObv and not risingPrice
divergenceSum = math.sum(divergence ? 1 : 0, 100)
obvDiv = divergenceSum > iDivergence and strongBreakout

//minevrini trend /contraction/ strong breakout
iIncludeEarnings = input.bool(defval = true, title = 'Include earnings', display = display.none, group = 'Signal: Minevrini trend /contraction/ strong breakout')
iBetterEarningsRate = input.float(defval = 0.5, title = 'Min. earnings change rate', minval = 0.0, maxval = 1.0, step = 0.1, display = display.none, group = 'Signal: Minevrini trend /contraction/ strong breakout')

doIncludeEarnings = sigMod >= 1 ? false : iIncludeEarnings
bool minevriniTrend = drelib.isMinevriniBullishTrend(true, doIncludeEarnings, iBetterEarningsRate)

minevriniTrendCond = ta.barssince(minevriniTrend) < 63

mtsb = minevriniTrendCond and strongBreakout
mtc1sb = minevriniTrendCond and (rmv1Cond or lowRmv1) and strongBreakout
mtc2sb = minevriniTrendCond and (rmv2Cond or lowRmv2) and strongBreakout
mtc3sb = minevriniTrendCond and (rmv3Cond or lowRmv3) and strongBreakout

//RunAwayGap-pullback
iBullishRagPbMaxTimeSinceRag = input.int(defval = 50, title = 'Max. pullback time', minval = 2, maxval = 60, display = display.none, group = 'Signal: RunAwayGap - pullback')
iBullishRagPbAdrMultiple = input.float(defval = 1.5, title = 'Gap Min. Adr Multiple', minval = 0.5, maxval = 3.0, step = 0.1, display = display.none, group = 'Signal: RunAwayGap - pullback')
runAwayGap = low > high[1] + iBullishRagPbAdrMultiple * adrPct / 100 * high[1] and volume > gVolMa
runAwayGapAgo = ta.barssince(runAwayGap)
ragPb = not runAwayGap and runAwayGapAgo < iBullishRagPbMaxTimeSinceRag and drelib.crossover(low[runAwayGapAgo]) and shortMa > shortMa[1]

//William O''Neil Inspired: hi-percentile - strong breakout
countChanges(series, length) =>
    math.sum(series != series[1] ? 1 : 0, length)

iOneilPercentileLookback = input.int(200, title = 'Main percentile lookback', minval = 20, maxval = 756, display = display.none, group = "Signal: O''Neil Inspired: hi-percentile sb")
iOneilEpsYearsCheck = input.int(3, title = 'Eps years check', minval = 1, maxval = 5, display = display.none, group = "Signal: O''Neil Inspired: hi-percentile sb")
iOneilMinPercentileAvg = input.float(70, title = 'Min. percentile average', minval = 50, maxval = 99, display = display.none, group = "Signal: O''Neil Inspired: hi-percentile sb")
oiObvPercentile = ta.percentrank(ta.obv, iOneilPercentileLookback)
oiRsPercentile = ta.percentrank(rs, iOneilPercentileLookback)
totalShares1M = syminfo.shares_outstanding_total / 1000000.0
epsAct1M = request.earnings(ticker = syminfo.tickerid, field = earnings.actual) / totalShares1M
oiEpsPercentile = ta.percentrank(epsAct1M, iOneilEpsYearsCheck * 252)
epsChanges = countChanges(epsAct1M, iOneilEpsYearsCheck * 252)
oiPercentileAvg = math.avg(oiObvPercentile, oiRsPercentile, oiEpsPercentile)
oiPercentilesOkAgo = ta.barssince(oiPercentileAvg > (100 + iOneilMinPercentileAvg) / 2)
wonHpSb = oiPercentileAvg > iOneilMinPercentileAvg and oiPercentilesOkAgo < 50 and (rmv1Cond or rmv2Cond or rmv3Cond) and epsChanges > 3 * iOneilEpsYearsCheck and strongBreakout

//William O''Neil Inspired: turnaround GO: usually for general market turnaround
iTurnaroundExtremeAgo = input.int(defval = 45, title = "max. peak/bottom ago", minval = 20, maxval = 60, step = 5, display = display.none, group = "Signal: O''Neil Inspired: turnaround and GO")
iturnaroundGoDayMinRange = input.float(defval = 0.0, title = "min. day range", minval = 0.0, maxval = 10.0, step = 0.1, display = display.none, group = "Signal: O''Neil Inspired: turnaround and GO", tooltip = "Use 0 for auto calculation based on adr. \nfor adr < 0.017 uses 0.017\nfor adr >= 0.017 uses 0.017 + (adr - 0.017) / 4")
iTurnaroundMinGoDays = input.int(defval = 3, title = "min. days", minval = 1, maxval = 10, display = display.none, group = "Signal: O''Neil Inspired: turnaround and GO")

adr = adrPct / 100
turnaroundGoDayMinRange = iturnaroundGoDayMinRange > 0.0 ? iturnaroundGoDayMinRange / 100 : (adr < 0.017 ? 0.017 : 0.017 + (adr - 0.017) / 4)

wonTurnGoUp = drelib.sigWONTurnaroundUp(iTurnaroundExtremeAgo, iTurnaroundMinGoDays, turnaroundGoDayMinRange, mainMa, gVol50Ma)

// riding min AVWAP - touch and go (relay: majorLow → minorLow1 → minorLow2 → minorLow3)
iMinVwapTAGLMajorLowLookup = input.int(defval = 150, title = "major low lookup", minval = 50, maxval = 300, display = display.none, group = "Signal: Min Vwap TouchAndGo")
iRidingMinVwapLag = input.int(defval = 1, title = "lag blabla", minval = 0, maxval = 2, display = display.none, group = "Signal: Min Vwap TouchAndGo")
iRidingMinVwapLowsBelow = input.int(defval = 5, title = "Max. lows below vwap", minval = 1, maxval = 10, display = display.none, group = "Signal: Min Vwap TouchAndGo")
iRidingMinVwapObvCond = input.bool(defval = true, title = 'Include above OBV cond.', display = display.none, group = "Signal: Min Vwap TouchAndGo")
loweringMa = ta.barssince(mainMa < mainMa[1])
lowest200 = ta.lowest(iMinVwapTAGLMajorLowLookup)
majorLow = low == lowest200 and loweringMa < 50 and low < mainMa
majorLowVwap = ta.vwap(low, majorLow)
barsSinceMajorLow = ta.barssince(majorLow)
lowsBelowMjVwap = math.sum(low < majorLowVwap ? 1 : 0, 10)
vwapTouch = barsSinceMajorLow > 20 and barsSinceMajorLow < 300 and drelib.crossover(majorLowVwap) and mainMa > mainMa[1] and lowsBelowMjVwap <= iRidingMinVwapLowsBelow
lowest10 = ta.lowest(10)
minorLow1 = vwapTouch and lowest10 == low
minorL1Vwap = ta.vwap(low, minorLow1)
minorLow1Vwap = ta.barssince(majorLow) < ta.barssince(minorLow1) ? na : minorL1Vwap
lowsBelowML1Vwap = math.sum(low < minorLow1Vwap ? 1 : 0, 10)
vwapTouch2 = drelib.crossover(minorLow1Vwap) and mainMa > mainMa[1] and lowsBelowML1Vwap <= iRidingMinVwapLowsBelow
minorLow2 = vwapTouch2 and lowest10 == low
minorL2Vwap = ta.vwap(low, minorLow2)
minorLow2Vwap = ta.barssince(majorLow) < ta.barssince(minorLow2) ? na : minorL2Vwap
lowsBelowML2Vwap = math.sum(low < minorLow2Vwap ? 1 : 0, 10)
vwapTouch3 = drelib.crossover(minorLow2Vwap) and mainMa > mainMa[1] and lowsBelowML2Vwap <= iRidingMinVwapLowsBelow
minorLow3 = vwapTouch3 and lowest10 == low
minorL3Vwap = ta.vwap(low, minorLow3)
minorLow3Vwap = ta.barssince(majorLow) < ta.barssince(minorLow3) ? na : minorL3Vwap
lowsBelowML3Vwap = math.sum(low < minorLow3Vwap ? 1 : 0, 10)
vwapTouch4 = drelib.crossover(minorLow3Vwap) and mainMa > mainMa[1] and lowsBelowML3Vwap <= iRidingMinVwapLowsBelow
minVwapTAG = (
    ((vwapTouch or vwapTouch[iRidingMinVwapLag] or vwapTouch2 or vwapTouch2[iRidingMinVwapLag]) and not (vwapTouch3 or vwapTouch3[iRidingMinVwapLag] or vwapTouch4 or vwapTouch4[iRidingMinVwapLag]))
or ((vwapTouch2 or vwapTouch2[iRidingMinVwapLag] or vwapTouch3 or vwapTouch3[iRidingMinVwapLag]) and not (vwapTouch or vwapTouch[iRidingMinVwapLag] or vwapTouch4 or vwapTouch4[iRidingMinVwapLag]))
or ((vwapTouch3 or vwapTouch3[iRidingMinVwapLag] or vwapTouch4 or vwapTouch4[iRidingMinVwapLag]) and not (vwapTouch or vwapTouch[iRidingMinVwapLag] or vwapTouch2 or vwapTouch2[iRidingMinVwapLag]))
) and close >= high[1] and (iRidingMinVwapObvCond and obvCondRaw or not iRidingMinVwapObvCond)

//check performance
iShowSigPerfPlots = input.bool(defval = false, title = 'show plots', display = display.none, group = 'Sig. performnce check')
iShowSigPerfTable = input.bool(defval = false, title = 'show table', display = display.none, group = 'Sig. performnce check')
iShowOnlyGoodSigs = input.bool(defval = true, title = 'show only good sigs.', display = display.none, group = 'Sig. performnce check')

showRow(_iShowOnlyGoodSigs, sigOk) =>
    _iShowOnlyGoodSigs and sigOk or not _iShowOnlyGoodSigs

sl = low[iSigStopLossDay]
[et3sbSuccRate, et3sbSuccCount, et3sbSigCount, et3sbAvgReturn, et3sbSuccRateOk, et3sbSuccRateStr, et3sbScore] = dreperf.successRateAllTimeStatsFull(et3sb, sl, true, iMinSigSuccessRate, adrCond, iSigCheckTime)
[et4sbSuccRate, et4sbSuccCount, et4sbSigCount, et4sbAvgReturn, et4sbSuccRateOk, et4sbSuccRateStr, et4sbScore] = dreperf.successRateAllTimeStatsFull(et4sb, sl, true, iMinSigSuccessRate, adrCond, iSigCheckTime)
[rmv1SuccRate, rmv1SuccCount, rmv1SigCount, rmv1AvgReturn, rmv1SuccRateOk, rmv1SuccRateStr, rmv1Score] = dreperf.successRateAllTimeStatsFull(bullishRmv1, sl, true, iMinSigSuccessRate, adrCond, iSigCheckTime)
[rmv2SuccRate, rmv2SuccCount, rmv2SigCount, rmv2AvgReturn, rmv2SuccRateOk, rmv2SuccRateStr, rmv2Score] = dreperf.successRateAllTimeStatsFull(bullishRmv2, sl, true, iMinSigSuccessRate, adrCond, iSigCheckTime)
[rmv3SuccRate, rmv3SuccCount, rmv3SigCount, rmv3AvgReturn, rmv3SuccRateOk, rmv3SuccRateStr, rmv3Score] = dreperf.successRateAllTimeStatsFull(bullishRmv3, sl, true, iMinSigSuccessRate, adrCond, iSigCheckTime)
[etc1sbSuccRate, etc1sbSuccCount, etc1sbSigCount, etc1sbAvgReturn, etc1sbSuccRateOk, etc1sbSuccRateStr, etc1sbScore] = dreperf.successRateAllTimeStatsFull(etc1sb, sl, true, iMinSigSuccessRate, adrCond, iSigCheckTime)
[etc2sbSuccRate, etc2sbSuccCount, etc2sbSigCount, etc2sbAvgReturn, etc2sbSuccRateOk, etc2sbSuccRateStr, etc2sbScore] = dreperf.successRateAllTimeStatsFull(etc2sb, sl, true, iMinSigSuccessRate, adrCond, iSigCheckTime)
[etc3sbSuccRate, etc3sbSuccCount, etc3sbSigCount, etc3sbAvgReturn, etc3sbSuccRateOk, etc3sbSuccRateStr, etc3sbScore] = dreperf.successRateAllTimeStatsFull(etc3sb, sl, true, iMinSigSuccessRate, adrCond, iSigCheckTime)
[obvDivSuccRate, obvDivSuccCount, obvDivSigCount, obvDivAvgReturn, obvDivSuccRateOk, obvDivSuccRateStr, obvDivScore] = dreperf.successRateAllTimeStatsFull(obvDiv, sl, true, iMinSigSuccessRate, adrCond, iSigCheckTime)
[mtsbSuccRate, mtsbSuccCount, mtsbSigCount, mtsbAvgReturn, mtsbSuccRateOk, mtsbSuccRateStr, mtsbScore] = dreperf.successRateAllTimeStatsFull(mtsb, sl, true, iMinSigSuccessRate, adrCond, iSigCheckTime)
[mtc1sbSuccRate, mtc1sbSuccCount, mtc1sbSigCount, mtc1sbAvgReturn, mtc1sbSuccRateOk, mtc1sbSuccRateStr, mtc1sbScore] = dreperf.successRateAllTimeStatsFull(mtc1sb, sl, true, iMinSigSuccessRate, adrCond, iSigCheckTime)
[mtc2sbSuccRate, mtc2sbSuccCount, mtc2sbSigCount, mtc2sbAvgReturn, mtc2sbSuccRateOk, mtc2sbSuccRateStr, mtc2sbScore] = dreperf.successRateAllTimeStatsFull(mtc2sb, sl, true, iMinSigSuccessRate, adrCond, iSigCheckTime)
[mtc3sbSuccRate, mtc3sbSuccCount, mtc3sbSigCount, mtc3sbAvgReturn, mtc3sbSuccRateOk, mtc3sbSuccRateStr, mtc3sbScore] = dreperf.successRateAllTimeStatsFull(mtc3sb, sl, true, iMinSigSuccessRate, adrCond, iSigCheckTime)
[ragPbSuccRate, ragPbSuccCount, ragPbSigCount, ragPbAvgReturn, ragPbSuccRateOk, ragPbSuccRateStr, ragPbScore] = dreperf.successRateAllTimeStatsFull(ragPb, sl, true, iMinSigSuccessRate, adrCond, iSigCheckTime)
[wonHpSbSuccRate, wonHpSbSuccCount, wonHpSbSigCount, wonHpSbAvgReturn, wonHpSbSuccRateOk, wonHpSbSuccRateStr, wonHpSbScore] = dreperf.successRateAllTimeStatsFull(wonHpSb, sl, true, iMinSigSuccessRate, adrCond, iSigCheckTime)
[wonTurnGoUpSuccRate, wonTurnGoUpSuccCount, wonTurnGoUpSigCount, wonTurnGoUpAvgReturn, wonTurnGoUpSuccRateOk, wonTurnGoUpSuccRateStr, wonTurnGoUpScore] = dreperf.successRateAllTimeStatsFull(wonTurnGoUp, sl, true, iMinSigSuccessRate, adrCond, iSigCheckTime)
[minVwapTAGSuccRate, minVwapTAGSuccCount, minVwapTAGSigCount, minVwapTAGAvgReturn, minVwapTAGSuccRateOk, minVwapTAGSuccRateStr, minVwapTAGScore] = dreperf.successRateAllTimeStatsFull(minVwapTAG, sl, true, iMinSigSuccessRate, adrCond, iSigCheckTime)

//plot sig performance
et3sbSigColor = color.new(color.blue, 0)
et4sbSigColor = color.new(color.lime, 0)
rmvSigColor = color.new(color.maroon, 0)
etcsbSigColor = color.new(color.fuchsia, 0)
obvDivSigColor = color.new(color.navy, 0)
mtsbSigColor = color.new(color.gray, 0)
ragPbSigColor = color.new(color.olive, 0)
wonHpSbSigColor = color.new(color.teal, 0)
minVwapTAGSigColor = color.new(color.aqua, 0)


//plot(series = iShowSigPerfPlots ? et3sbSuccRate : na, title = 'et3sb', color = et3sbSigColor, linestyle = plot.linestyle_solid)
//plot(series = iShowSigPerfPlots ? et4sbSuccRate : na, title = 'et4sb', color = et4sbSigColor, linestyle = plot.linestyle_solid)
//plot(series = iShowSigPerfPlots ? rmv1SuccRate : na, title = 'rmv1', color = rmvSigColor, linestyle = plot.linestyle_solid)
//plot(series = iShowSigPerfPlots ? rmv2SuccRate : na, title = 'rmv2', color = rmvSigColor, linestyle = plot.linestyle_solid)
//plot(series = iShowSigPerfPlots ? rmv3SuccRate : na, title = 'rmv3', color = rmvSigColor, linestyle = plot.linestyle_solid)
//plot(series = iShowSigPerfPlots ? etc1sbSuccRate : na, title = 'etc1sb', color = etcsbSigColor, linestyle = plot.linestyle_solid)
//plot(series = iShowSigPerfPlots ? etc2sbSuccRate : na, title = 'etc2sb', color = etcsbSigColor, linestyle = plot.linestyle_solid)
//plot(series = iShowSigPerfPlots ? etc3sbSuccRate : na, title = 'etc3sb', color = etcsbSigColor, linestyle = plot.linestyle_solid)
//plot(series = iShowSigPerfPlots ? obvDivSuccRate : na, title = 'obvDiv', color = obvDivSigColor, linestyle = plot.linestyle_solid)
//plot(series = iShowSigPerfPlots ? mtsbSuccRate : na, title = 'mtsb', color = mtsbSigColor, linestyle = plot.linestyle_solid)
//plot(series = iShowSigPerfPlots ? mtc1sbSuccRate : na, title = 'mtc1sb', color = mtsbSigColor, linestyle = plot.linestyle_solid)
//plot(series = iShowSigPerfPlots ? mtc2sbSuccRate : na, title = 'mtc2sb', color = mtsbSigColor, linestyle = plot.linestyle_solid)
//plot(series = iShowSigPerfPlots ? mtc3sbSuccRate : na, title = 'mtc3sb', color = mtsbSigColor, linestyle = plot.linestyle_solid)
//plot(series = iShowSigPerfPlots ? ragPbSuccRate : na, title = 'rag-pb', color = ragPbSigColor, linestyle = plot.linestyle_solid)
//plot(series = iShowSigPerfPlots ? wonHpSbSuccRate : na, title = 'WON:hp-sb', color = wonHpSbSigColor, linestyle = plot.linestyle_solid)
//plot(series = iShowSigPerfPlots ? wonTurnGoUpSuccRate : na, title = 'WON:turnUp', color = wonHpSbSigColor, linestyle = plot.linestyle_solid)
//plot(series = iShowSigPerfPlots ? minVwapTAGSuccRate : na, title = 'minVwapTAG', color = minVwapTAGSigColor, linestyle = plot.linestyle_solid)


//print sig performance table
if barstate.islast and iShowSigPerfTable
    var tbl = table.new(position = position.top_right, columns = 2, rows = 19)
    txtSize = size.small
    table.cell(table_id = tbl, column = 0, row = 0, text = '')
    table.cell(table_id = tbl, column = 1, row = 0, text = '')
    table.cell(table_id = tbl, column = 0, row = 1, text = "sig", text_size = txtSize)
    table.cell(table_id = tbl, column = 1, row = 1, text = "perf " + str.tostring(iMinSigSuccessRate, "#.# ") + str.tostring(adrCond, "#.#"), text_size = txtSize)

    if showRow(iShowOnlyGoodSigs, et3sbSuccRateOk)
        table.cell(table_id = tbl, column = 0, row = 2, text = "et3sb", text_color = et3sbSigColor, text_size = txtSize)
        table.cell(table_id = tbl, column = 1, row = 2, text = et3sbSuccRateStr, text_size = txtSize)
    if showRow(iShowOnlyGoodSigs, et4sbSuccRateOk)
        table.cell(table_id = tbl, column = 0, row = 3, text = "et4sb", text_color = et4sbSigColor, text_size = txtSize)
        table.cell(table_id = tbl, column = 1, row = 3, text = et4sbSuccRateStr, text_size = txtSize)
    if showRow(iShowOnlyGoodSigs, rmv1SuccRateOk)
        table.cell(table_id = tbl, column = 0, row = 4, text = "rmv1", text_color = rmvSigColor, text_size = txtSize)
        table.cell(table_id = tbl, column = 1, row = 4, text = rmv1SuccRateStr, text_size = txtSize)
    if showRow(iShowOnlyGoodSigs, rmv2SuccRateOk)
        table.cell(table_id = tbl, column = 0, row = 5, text = "rmv2", text_color = rmvSigColor, text_size = txtSize)
        table.cell(table_id = tbl, column = 1, row = 5, text = rmv2SuccRateStr, text_size = txtSize)
    if showRow(iShowOnlyGoodSigs, rmv3SuccRateOk)
        table.cell(table_id = tbl, column = 0, row = 6, text = "rmv3", text_color = rmvSigColor, text_size = txtSize)
        table.cell(table_id = tbl, column = 1, row = 6, text = rmv3SuccRateStr, text_size = txtSize)
    if showRow(iShowOnlyGoodSigs, etc1sbSuccRateOk)
        table.cell(table_id = tbl, column = 0, row = 7, text = "etc1sb", text_color = etcsbSigColor, text_size = txtSize)
        table.cell(table_id = tbl, column = 1, row = 7, text = etc1sbSuccRateStr, text_size = txtSize)
    if showRow(iShowOnlyGoodSigs, etc2sbSuccRateOk)
        table.cell(table_id = tbl, column = 0, row = 8, text = "etc2sb", text_color = etcsbSigColor, text_size = txtSize)
        table.cell(table_id = tbl, column = 1, row = 8, text = etc2sbSuccRateStr, text_size = txtSize)
    if showRow(iShowOnlyGoodSigs, etc3sbSuccRateOk)
        table.cell(table_id = tbl, column = 0, row = 9, text = "etc3sb", text_color = etcsbSigColor, text_size = txtSize)
        table.cell(table_id = tbl, column = 1, row = 9, text = etc3sbSuccRateStr, text_size = txtSize)
    if showRow(iShowOnlyGoodSigs, obvDivSuccRateOk)
        table.cell(table_id = tbl, column = 0, row = 10, text = "obvDiv", text_color = obvDivSigColor, text_size = txtSize)
        table.cell(table_id = tbl, column = 1, row = 10, text = obvDivSuccRateStr, text_size = txtSize)
    if showRow(iShowOnlyGoodSigs, mtsbSuccRateOk)
        table.cell(table_id = tbl, column = 0, row = 11, text = "mtsb", text_color = mtsbSigColor, text_size = txtSize)
        table.cell(table_id = tbl, column = 1, row = 11, text = mtsbSuccRateStr, text_size = txtSize)
    if showRow(iShowOnlyGoodSigs, mtc1sbSuccRateOk)
        table.cell(table_id = tbl, column = 0, row = 12, text = "mtc1sb", text_color = mtsbSigColor, text_size = txtSize)
        table.cell(table_id = tbl, column = 1, row = 12, text = mtc1sbSuccRateStr, text_size = txtSize)
    if showRow(iShowOnlyGoodSigs, mtc2sbSuccRateOk)
        table.cell(table_id = tbl, column = 0, row = 13, text = "mtc2sb", text_color = mtsbSigColor, text_size = txtSize)
        table.cell(table_id = tbl, column = 1, row = 13, text = mtc2sbSuccRateStr, text_size = txtSize)
    if showRow(iShowOnlyGoodSigs, mtc3sbSuccRateOk)
        table.cell(table_id = tbl, column = 0, row = 14, text = "mtc3sb", text_color = mtsbSigColor, text_size = txtSize)
        table.cell(table_id = tbl, column = 1, row = 14, text = mtc3sbSuccRateStr, text_size = txtSize)
    if showRow(iShowOnlyGoodSigs, ragPbSuccRateOk)
        table.cell(table_id = tbl, column = 0, row = 15, text = "rag-pb", text_color = ragPbSigColor, text_size = txtSize)
        table.cell(table_id = tbl, column = 1, row = 15, text = ragPbSuccRateStr, text_size = txtSize)
    if showRow(iShowOnlyGoodSigs, wonHpSbSuccRateOk)
        table.cell(table_id = tbl, column = 0, row = 16, text = "WON:hp-sb", text_color = wonHpSbSigColor, text_size = txtSize)
        table.cell(table_id = tbl, column = 1, row = 16, text = wonHpSbSuccRateStr, text_size = txtSize)
    if showRow(iShowOnlyGoodSigs, wonTurnGoUpSuccRateOk)
        table.cell(table_id = tbl, column = 0, row = 17, text = "WON:turnUp", text_color = wonHpSbSigColor, text_size = txtSize)
        table.cell(table_id = tbl, column = 1, row = 17, text = wonTurnGoUpSuccRateStr, text_size = txtSize)
    if showRow(iShowOnlyGoodSigs, minVwapTAGSuccRateOk)
        table.cell(table_id = tbl, column = 0, row = 18, text = "minVwapTAG", text_color = minVwapTAGSigColor, text_size = txtSize)
        table.cell(table_id = tbl, column = 1, row = 18, text = minVwapTAGSuccRateStr, text_size = txtSize)

//plot signals on price chart
plotshape(iShowEt3sbSig and et3sb and showRow(iShowOnlyGoodSigs, et3sbSuccRateOk), title = 'et3sb', location = location.belowbar, color = et3sbSigColor, style = shape.triangleup, text = 'et3sb', textcolor = et3sbSigColor)
plotshape(iShowEt4sbSig and et4sb and showRow(iShowOnlyGoodSigs, et4sbSuccRateOk), title = 'et4sb', location = location.belowbar, color = et4sbSigColor, style = shape.triangleup, text = 'et4sb', textcolor = et4sbSigColor)
plotshape(iShowRmv1Sig and bullishRmv1 and showRow(iShowOnlyGoodSigs, rmv1SuccRateOk), title = 'rmv1', location = location.belowbar, color = rmvSigColor, style = shape.triangleup, text = 'rmv1', textcolor = rmvSigColor)
plotshape(iShowRmv2Sig and bullishRmv2 and showRow(iShowOnlyGoodSigs, rmv2SuccRateOk), title = 'rmv2', location = location.belowbar, color = rmvSigColor, style = shape.triangleup, text = 'rmv2', textcolor = rmvSigColor)
plotshape(iShowRmv3Sig and bullishRmv3 and showRow(iShowOnlyGoodSigs, rmv3SuccRateOk), title = 'rmv3', location = location.belowbar, color = rmvSigColor, style = shape.triangleup, text = 'rmv3', textcolor = rmvSigColor)
plotshape(iShowEtc1sbSig and etc1sb and showRow(iShowOnlyGoodSigs, etc1sbSuccRateOk), title = 'etc1sb', location = location.belowbar, color = etcsbSigColor, style = shape.triangleup, text = 'etc1sb', textcolor = etcsbSigColor)
plotshape(iShowEtc2sbSig and etc2sb and showRow(iShowOnlyGoodSigs, etc2sbSuccRateOk), title = 'etc2sb', location = location.belowbar, color = etcsbSigColor, style = shape.triangleup, text = 'etc2sb', textcolor = etcsbSigColor)
plotshape(iShowEtc3sbSig and etc3sb and showRow(iShowOnlyGoodSigs, etc3sbSuccRateOk), title = 'etc3sb', location = location.belowbar, color = etcsbSigColor, style = shape.triangleup, text = 'etc3sb', textcolor = etcsbSigColor)
plotshape(iShowObvDivSig and obvDiv and showRow(iShowOnlyGoodSigs, obvDivSuccRateOk), title = 'obvDiv', location = location.belowbar, color = obvDivSigColor, style = shape.triangleup, text = 'obvDiv', textcolor = obvDivSigColor)
plotshape(iShowMinevriniTrendSig and mtsb and showRow(iShowOnlyGoodSigs, mtsbSuccRateOk), title = 'mtsb', location = location.belowbar, color = mtsbSigColor, style = shape.triangleup, text = 'mtsb', textcolor = mtsbSigColor)
plotshape(iShowMinevriniTrendC1Sig and mtc1sb and showRow(iShowOnlyGoodSigs, mtc1sbSuccRateOk), title = 'mtc1sb', location = location.belowbar, color = mtsbSigColor, style = shape.triangleup, text = 'mtc1sb', textcolor = mtsbSigColor)
plotshape(iShowMinevriniTrendC2Sig and mtc2sb and showRow(iShowOnlyGoodSigs, mtc2sbSuccRateOk), title = 'mtc2sb', location = location.belowbar, color = mtsbSigColor, style = shape.triangleup, text = 'mtc2sb', textcolor = mtsbSigColor)
plotshape(iShowMinevriniTrendC3Sig and mtc3sb and showRow(iShowOnlyGoodSigs, mtc3sbSuccRateOk), title = 'mtc3sb', location = location.belowbar, color = mtsbSigColor, style = shape.triangleup, text = 'mtc3sb', textcolor = mtsbSigColor)
plotshape(iShowRagPb and ragPb and showRow(iShowOnlyGoodSigs, ragPbSuccRateOk), title = 'rag-pb', location = location.belowbar, color = ragPbSigColor, style = shape.triangleup, text = 'rag-pb', textcolor = ragPbSigColor)
plotshape(iShowWONHP and wonHpSb and showRow(iShowOnlyGoodSigs, wonHpSbSuccRateOk), title = 'WON:hp-sb', location = location.belowbar, color = wonHpSbSigColor, style = shape.triangleup, text = 'WON:hp-sb', textcolor = wonHpSbSigColor)
plotshape(iShowWONTurnaroundGo and wonTurnGoUp and showRow(iShowOnlyGoodSigs, wonTurnGoUpSuccRateOk), title = 'WON:turnUP', location = location.belowbar, color = wonHpSbSigColor, style = shape.triangleup, text = 'WON:turnUp', textcolor = wonHpSbSigColor)
plotshape(iShowMinVwapTAG and minVwapTAG and showRow(iShowOnlyGoodSigs, minVwapTAGSuccRateOk), title = 'minVwapTAG', location = location.belowbar, color = minVwapTAGSigColor, style = shape.triangleup, text = 'minVwapTAG', textcolor = minVwapTAGSigColor)
plotshape(iShowMinVwapTAG and iShowMinVwapTAGDebug and majorLow and showRow(iShowOnlyGoodSigs, minVwapTAGSuccRateOk), title = '1L', location = location.belowbar, color = minVwapTAGSigColor, style = shape.triangleup, text = '1L', textcolor = minVwapTAGSigColor)
plotshape(iShowMinVwapTAG and iShowMinVwapTAGDebug and minorLow1 and showRow(iShowOnlyGoodSigs, minVwapTAGSuccRateOk), title = '2L', location = location.belowbar, color = minVwapTAGSigColor, style = shape.triangleup, text = '2L', textcolor = minVwapTAGSigColor)
plotshape(iShowMinVwapTAG and iShowMinVwapTAGDebug and minorLow2 and showRow(iShowOnlyGoodSigs, minVwapTAGSuccRateOk), title = '3L', location = location.belowbar, color = minVwapTAGSigColor, style = shape.triangleup, text = '3L', textcolor = minVwapTAGSigColor)
plotshape(iShowMinVwapTAG and iShowMinVwapTAGDebug and minorLow3 and showRow(iShowOnlyGoodSigs, minVwapTAGSuccRateOk), title = '4L', location = location.belowbar, color = minVwapTAGSigColor, style = shape.triangleup, text = '4L', textcolor = minVwapTAGSigColor)
plot(series = iShowMinVwapTAGDebug ? majorLowVwap : na, title = "majorLowVwap", color = minVwapTAGSigColor)
plot(series = iShowMinVwapTAGDebug ? minorLow1Vwap : na, title = "minorLow1Vwap", color = minVwapTAGSigColor, linestyle = plot.linestyle_dotted, style = plot.style_linebr)
plot(series = iShowMinVwapTAGDebug ? minorLow2Vwap : na, title = "minorLow2Vwap", color = minVwapTAGSigColor, linestyle = plot.linestyle_dotted, style = plot.style_linebr)
plot(series = iShowMinVwapTAGDebug ? minorLow3Vwap : na, title = "minorLow3Vwap", color = minVwapTAGSigColor, linestyle = plot.linestyle_dotted, style = plot.style_linebr)

//issuing alerts
et3sbSig = et3sb and et3sbSuccRateOk
et3sbSig_p1D = et3sbSig[1] and orb
et4sbSig = et4sb and et4sbSuccRateOk
et4sbSig_p1D = et4sbSig[1] and orb
bullishRmvSig = (bullishRmv1 and rmv1SuccRateOk) or (bullishRmv2 and rmv2SuccRateOk) or (bullishRmv3 and rmv3SuccRateOk)
bullishRmvSig_p1D = bullishRmvSig[1] and orb
etcsbSig = (etc1sb and etc1sbSuccRateOk) or (etc2sb and etc2sbSuccRateOk) or (etc3sb and etc3sbSuccRateOk)
etcsbSig_p1D = etcsbSig[1] and orb
obvDivSig = obvDiv and obvDivSuccRateOk
obvDivSig_p1D = obvDivSig[1] and orb
mtsbSig = (mtsb and mtsbSuccRateOk) or (mtc1sb and mtc1sbSuccRateOk) or (mtc2sb and mtc2sbSuccRateOk) or (mtc3sb and mtc3sbSuccRateOk)
mtsbSig_p1D = mtsbSig[1] and orb
ragPbSig = ragPb and ragPbSuccRateOk
ragPbSig_p1D = ragPbSig[1] and orb
wonHpSbSig = wonHpSb and wonHpSbSuccRateOk
wonHpSbSig_p1D = wonHpSbSig[1] and orb
wonTurnGoUpSig = wonTurnGoUp and wonTurnGoUpSuccRateOk
wonTurnGoUpSig_p1D = wonTurnGoUpSig[1] and orb
minVwapTAGSig = minVwapTAG and minVwapTAGSuccRateOk
minVwapTAGSig_p1D = minVwapTAGSig[1] and orb

allGoodSig = et3sbSig or et3sbSig_p1D or et4sbSig or et4sbSig_p1D or bullishRmvSig or bullishRmvSig_p1D or etcsbSig or etcsbSig_p1D or obvDivSig or obvDivSig_p1D or mtsbSig or mtsbSig_p1D or ragPbSig or ragPbSig_p1D or wonHpSbSig or wonHpSbSig_p1D or wonTurnGoUpSig or wonTurnGoUpSig_p1D or minVwapTAGSig or minVwapTAGSig_p1D

alertcondition(gFilter and (allGoodSig), title = 'best LONG', message = 'best LONG')

alertcondition(gFilter and (et3sbSig or et3sbSig_p1D), title = 'bullish ET3SB', message = 'ET3SB')
alertcondition(gFilter and (et4sbSig or et4sbSig_p1D), title = 'bullish ET4SB', message = 'ET4SB')
alertcondition(gFilter and (bullishRmvSig or bullishRmvSig_p1D), title = 'bullish RMV', message = 'RMV')
alertcondition(gFilter and (etcsbSig or etcsbSig_p1D), title = 'bullish ETCSB', message = 'ETCSB')
alertcondition(gFilter and (obvDivSig or obvDivSig_p1D), title = 'bullish obvDiv', message = 'obvDiv')
alertcondition(gFilter and (mtsbSig or mtsbSig_p1D), title = 'bullish mtsb', message = 'mtsb')
alertcondition(gFilter and (ragPbSig or ragPbSig_p1D), title = 'bullish RunAwayGap-pb', message = 'rag-pb')
alertcondition(gFilter and (wonHpSbSig or wonHpSbSig_p1D), title = "bullish O''Neil inspired: hi-percentile sb", message = 'WON:hp-sb')
alertcondition(gFilter and (wonTurnGoUpSig or wonTurnGoUpSig_p1D), title = "bullish O''Neil inspired: turnaround GO Up", message = 'WON:turUp')
alertcondition(gFilter and (minVwapTAGSig or minVwapTAGSig_p1D), title = "bullish min vwap TAG", message = 'minVwapTAG')
