// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © drebel

//@version=4
study(title="DRE RSI + candles + volume", shorttitle="DRE Swing Signals 3", overlay=true)

// Get user input
res = input(title="RSI Timeframe", type=input.resolution, defval="")
rsiSource = input(title="RSI Source", type=input.source, defval=close)
rsiLength = input(title="RSI Length", type=input.integer, defval=14)
rsiOverbought = input(title="RSI Overbought Level", type=input.integer, defval=70)
rsiOversold = input(title="RSI Oversold Level", type=input.integer, defval=30)
volMulti = input(title="volume multilier", type=input.float, defval=1.1)

// Get RSI value
rsi = rsi(rsiSource, rsiLength)
rsiRes = security(syminfo.tickerid, res, rsi, barmerge.gaps_on, barmerge.lookahead_off)
rsiOB = rsiRes >= rsiOverbought
rsiOS = rsiRes <= rsiOversold

//volume sma
volAvg = sma(volume, 20)

//candles
//relative candle size
candleSizeMa = sma(high - low, 50)

//tolerance 0.1 pct
tol = 0.001
tol_p = 1 + tol
tol_m = 1 - tol

//candle parameters
highShadow = high != low ? (high - max(open, close)) / (high-low) : 0
candleBody = high != low ? (max(open, close) - min(open, close)) / (high-low) : 0
lowShadow = high != low ? (min(open, close) - low) / (high-low) : 0
candleColor = close > open ? 1 : close < open ? -1 : 0

//candles beariish
spadajacaGwiazda = highShadow > 0.6 and lowShadow < 0.15 and high-low > candleSizeMa and low >= tol_m*max(low[1], low[2], low[3])
objecieBessy = candleColor == -1 and candleColor[1] == 1 and candleBody > 0.6 and close <= open[1] and open >= close[1] and low >= low[2] and high-low > candleSizeMa and low[1] >= tol_m*max(low[2], low[3], low[4]) //bearish_engulfing
zaslonaCiemnejChmury = candleColor == -1 and candleColor[1] == 1 and close >= open[1] and close <= close[1] - 0.5 * candleBody[1] and open >= high[1] and low >= low[2] and high-low > candleSizeMa and low[1] >= tol_m*max(low[2], low[3], low[4]) //dark_cloud_cover
haramiSpadkowe = candleColor <= 0 and candleColor[1] == 1 and close >= open[1] and open <= close[1] and low >= low[2] and high-low > candleSizeMa and low[1] >= tol_m*max(low[2], low[3], low[4])
gwiazdaWieczorna = candleColor == -1 and candleColor[2] == 1 and candleBody[1] < min(candleBody, candleBody[2]) and open <= min(open[1], close[1]) and close[2] <= min(open[1], close[1]) and min(low, low[2]) >= low[3] and high-low > candleSizeMa and low[2] >= tol_m*max(low[3], low[4], low[5]) //evening_star
bearishCandle = spadajacaGwiazda or objecieBessy or zaslonaCiemnejChmury or haramiSpadkowe or gwiazdaWieczorna

//candles bullish
mlot = lowShadow > 0.6 and highShadow < 0.15 and high-low > candleSizeMa and high <= tol_p*min(high[1], high[2], high[3]) //hammer
objecieHossy = candleColor == 1 and candleColor[1] == -1 and candleBody > 0.6 and close >= open[1] and open <= close[1] and high <= high[2] and high-low > candleSizeMa and high[1] <= tol_p*min(high[2], high[3], high[4]) //bullish_engulfing
formacjaPrzenikania = candleColor == 1 and candleColor[1] == -1 and close >= close[1] + 0.5 * candleBody[1] and close <= open[1] and open <= low[1] and high <= high[2] and high-low > candleSizeMa and high[1] <= tol_p*min(high[2], high[3], high[4]) //piercing_line
haramiWzrostowe = candleColor >= 0 and candleColor[1] == -1 and close <= open[1] and open >= close[1] and high <= high[2] and high-low > candleSizeMa and high[1] <= tol_p*min(high[2], high[3], high[4])
gwiazdaPoranna = candleColor == 1 and candleColor[2] == -1 and candleBody[1] < min(candleBody, candleBody[2]) and open >= min(open[1], close[1]) and close[2] >= min(open[1], close[1]) and max(high, high[2]) <= high[3] and high-low > candleSizeMa and high[2] <= tol_p*min(high[3], high[4], high[5]) //morning_star
bullishCandle = mlot or objecieHossy or formacjaPrzenikania or haramiWzrostowe or gwiazdaPoranna


//signals
bullishSignal = (rsiOS or rsiOS[1]) and bullishCandle
bearisgSignal = (rsiOB or rsiOB[1]) and bearishCandle
volSignal = volume > 0 ? volume > volAvg * volMulti : true
//volume signal could be lagging a little bit
tradeSignal = (volSignal and (bullishSignal or bearisgSignal)) or (volSignal and (bullishSignal[1] or bearisgSignal[1]))


// Plot signals to chart
plotshape(volSignal and bullishSignal or volSignal and bullishSignal[1], title="Long", location=location.belowbar, color=color.green, style=shape.triangleup, text="SwL")
plotshape(volSignal and bearisgSignal or volSignal and bearisgSignal[1], title="Short", location=location.abovebar, color=color.red, style=shape.triangledown, text="SwS")
// Send out an alert if this candle meets our conditions
alertcondition(tradeSignal, title="RSI Trade Alert!", message="RSI Swing Signal for XXX")