// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © drebel

//@version=6

// @description: Library supporting performance checking of signals
library('DREPerf')

const int DEFAULT_SIG_CHECK_TIME = 15
const int SIG_CHECK_TIME_LONG = 100
const int DEFAULT_STOCK_TRADING_DAYS_IN_A_YEAR = 252
const string SUCC_RATE_SHORT_FORMAT = "{0,number,#.#}% ({1}/{2})"
const string SUCC_RATE_LONG_FORMAT = "{0,number,#.#}% ({1}/{2}) {3,number,#.#}%"
const string SUCC_RATE_FULL_FORMAT = "{0,number,#.#}% ({1}/{2}) {3,number,#.#}% {4,number,#}"

export sigSuccRateOk(float _succRatePct, float _retAvgPct, float _minSuccRatePct, float _minRetAvgPct) =>
	_succRatePct > _minSuccRatePct and _retAvgPct > _minRetAvgPct

export sigScore(float _succRatePct, int _succCount, float _retAvgPct) =>
	years = bar_index / DEFAULT_STOCK_TRADING_DAYS_IN_A_YEAR
	_succRatePct * math.pow(_succCount, 0.4) * _retAvgPct / years

export sigScore(float _succRatePct, int _succCount, float _retAvgPct, bool _succRateOk) =>
	_succRateOk ? sigScore(_succRatePct, _succCount, _retAvgPct) : 0.0

export sigScore(float _succRatePct, int _succCount, float _retAvgPct, float _minSuccRatePct, float _minRetAvgPct) =>
	succRateOk = sigSuccRateOk(_succRatePct, _retAvgPct, _minSuccRatePct,  _minRetAvgPct)
	succRateOk ? sigScore(_succRatePct, _succCount, _retAvgPct) : 0.0

export formatSuccessRateStr(float sigSuccRatePct, int sigSuccCount, int sigAllCount, float retAvgPct) =>
	sigAllCount == 0 ? "-" : str.format(SUCC_RATE_LONG_FORMAT, sigSuccRatePct, sigSuccCount, sigAllCount, retAvgPct)

export formatSuccessRateStr(bool _longFormat, float sigSuccRatePct, int sigSuccCount, int sigAllCount, float retAvgPct) =>
	sigAllCount == 0 ? "-" : str.format(_longFormat ? SUCC_RATE_LONG_FORMAT : SUCC_RATE_SHORT_FORMAT, sigSuccRatePct, sigSuccCount, sigAllCount, retAvgPct)

export formatSuccessRateFullStr(float sigSuccRatePct, int sigSuccCount, int sigAllCount, float retAvgPct, float score) =>
	sigAllCount == 0 ? "-" : str.format(SUCC_RATE_FULL_FORMAT, sigSuccRatePct, sigSuccCount, sigAllCount, retAvgPct, score)

export formatSuccessRateStr(float sigSuccRatePct, int sigSuccCount, int sigAllCount, float retAvgPct, float _minSuccRatePct, float _minRetAvgPct) =>
	score = sigScore(sigSuccRatePct, sigSuccCount, retAvgPct, _minSuccRatePct, _minRetAvgPct)
	formatSuccessRateFullStr(sigSuccRatePct, sigSuccCount, sigAllCount, retAvgPct, score)

// @function This simple function checks a success rate for given signal (bool series) against a given stop loss level (float series). A success is a situation when after a signal candle price does not go below or equal given stop loss level. The counts and rates are checked for a given _lookback period.
// @param _sig A bool series indicationg signal was triggered on given candle or not.
// @param _sigCandleStopLoss A float series storing a stop loss level for a signal candle. "Success" will be determined based on this level and pricess happening between signal candle and signal candle + _checkTime number of candles.
// @param _checkTime A number of candles after the signal to check is a signal was a success or not.
// @param _lookback Time period for signal performance check eg. a last year (about 252 days).
// @returns signal success rate, signal succesc count, singal count.
export successRateInPeriodStats(series bool _sig, series float _sigCandleStopLoss, int _checkTime, int _lookback) =>
	sigSucc = ta.lowest(_checkTime) > _sigCandleStopLoss[_checkTime] and _sig[_checkTime]
	sigSucc_10 = sigSucc ? 1 : 0
	sigSuccCount = int(math.sum(sigSucc_10, _lookback))
	sigAll_10 = _sig[_checkTime] ? 1 : 0
	sigAllCount = int(math.sum(sigAll_10, _lookback))
	sigSuccRatePct = 100.0 * sigSuccCount / sigAllCount
	[sigSuccRatePct, sigSuccCount, sigAllCount]

export successRateInPeriodStr(series bool _sig, series float _sigCandleStopLoss, int _checkTime, int _lookback) =>
	[sigSuccRatePct, sigSuccCount, sigAllCount] = successRateInPeriodStats(_sig, _sigCandleStopLoss, _checkTime, _lookback)
	str.format(SUCC_RATE_SHORT_FORMAT, sigSuccRatePct, sigSuccCount, sigAllCount)

export successRateInPeriodStats(series bool _sig, series float _sigCandleStopLoss) =>
	successRateInPeriodStats(_sig, _sigCandleStopLoss, DEFAULT_SIG_CHECK_TIME, DEFAULT_STOCK_TRADING_DAYS_IN_A_YEAR)

export successRateInPeriodStr(series bool _sig, series float _sigCandleStopLoss) =>
	[sigSuccRatePct, sigSuccCount, sigAllCount] = successRateInPeriodStats(_sig, _sigCandleStopLoss, DEFAULT_SIG_CHECK_TIME, DEFAULT_STOCK_TRADING_DAYS_IN_A_YEAR)
	str.format(SUCC_RATE_SHORT_FORMAT, sigSuccRatePct, sigSuccCount, sigAllCount)

export successRateInPeriod(series bool _sig, series float _sigCandleStopLoss, int _lookback) =>
	[sigSuccRatePct, sigSuccCount, sigAllCount] = successRateInPeriodStats(_sig, _sigCandleStopLoss, DEFAULT_SIG_CHECK_TIME, _lookback)
	sigSuccRatePct

export successRateInPeriod(series bool _sig, series float _sigCandleStopLoss) =>
	[sigSuccRatePct, sigSuccCount, sigAllCount] = successRateInPeriodStats(_sig, _sigCandleStopLoss, DEFAULT_SIG_CHECK_TIME, DEFAULT_STOCK_TRADING_DAYS_IN_A_YEAR)
	sigSuccRatePct

// @function This simple function checks a success rate for given signal (bool series) against a given stop loss level (float series). A success is a situation when after a signal candle price does not go below or equal given stop loss level. The counts and rates are checked for all time.
// @param _sig A bool series indicationg signal was triggered on given candle or not.
// @param _sigCandleStopLoss A float series storing a stop loss level for a signal candle. "Success" will be determined based on this level and pricess happening between signal candle and signal candle + _checkTime number of candles.
// @param _checkTime A number of candles after the signal to check is a signal was a success or not.
// @param _long true for long plays check, false for short plays check
// @returns signal success rate, signal succesc count, singal count average pct return when succes.
export successRateAllTimeStats(series bool _sig, series float _sigCandleStopLoss, int _checkTime, bool _long) =>
	longSigSucc = _long and ta.lowest(_checkTime) > _sigCandleStopLoss[_checkTime] and _sig[_checkTime]
	shortSigSucc = not _long and ta.highest(_checkTime) < _sigCandleStopLoss[_checkTime] and _sig[_checkTime]
	sigSucc_10 = (_long ? longSigSucc : shortSigSucc) ? 1 : 0
	sigSuccCount = int(ta.cum(sigSucc_10))
	sigAll_10 = _sig[_checkTime] ? 1 : 0
	sigAllCount = int(ta.cum(sigAll_10))
	sigSuccRatePct = 100.0 * sigSuccCount / sigAllCount
	ret = (close - close[_checkTime]) / close[_checkTime]
	retSL = (_sigCandleStopLoss[_checkTime] - close[_checkTime]) / close[_checkTime]
	retCum = ta.cum(_sig[_checkTime] and (longSigSucc or shortSigSucc) ? ret : _sig[_checkTime] ? retSL : 0)
	retAvgPct = 100.0 * retCum / sigAllCount * (_long ? 1 : -1)
	[sigSuccRatePct, sigSuccCount, sigAllCount, retAvgPct]

export successRateAllTimeStats(series bool _sig, series float _sigCandleStopLoss, int _checkTime) =>
	[sigSuccRatePct, sigSuccCount, sigAllCount, retAvgPct] = successRateAllTimeStats(_sig, _sigCandleStopLoss, _checkTime, true)	

export successRateAllTimeStats(series bool _sig, series float _sigCandleStopLoss, bool _long) =>
	successRateAllTimeStats(_sig, _sigCandleStopLoss, DEFAULT_SIG_CHECK_TIME, _long)

export successRateAllTimeStats(series bool _sig, series float _sigCandleStopLoss) =>
	successRateAllTimeStats(_sig, _sigCandleStopLoss, DEFAULT_SIG_CHECK_TIME, true)

export successRateAllTimeStatsFull(series bool _sig, series float _sigCandleStopLoss, bool _long, float _minSuccRatePct, float _minRetAvgPct, int _sigCheckTime) =>
	[sigSuccRatePct, sigSuccCount, sigAllCount, retAvgPct] = successRateAllTimeStats(_sig, _sigCandleStopLoss, _sigCheckTime, _long)
	bool succRateOk = sigSuccRateOk(sigSuccRatePct, retAvgPct, _minSuccRatePct, _minRetAvgPct)
	float score = sigScore(sigSuccRatePct, sigSuccCount, retAvgPct, succRateOk)
	string succRateStr = formatSuccessRateFullStr(sigSuccRatePct, sigSuccCount, sigAllCount, retAvgPct, score)
	[sigSuccRatePct, sigSuccCount, sigAllCount, retAvgPct, succRateOk, succRateStr, score]

export successRateAllTimeStatsFull(series bool _sig, series float _sigCandleStopLoss, bool _long, float _minSuccRatePct, float _minRetAvgPct) =>
	successRateAllTimeStatsFull(_sig, _sigCandleStopLoss, _long, _minSuccRatePct, _minRetAvgPct, DEFAULT_SIG_CHECK_TIME)

export successRateAllTimeStatsFull(series bool _sig, series float _sigCandleStopLoss, float _minSuccRatePct, float _minRetAvgPct) =>
	successRateAllTimeStatsFull(_sig, _sigCandleStopLoss, true, _minSuccRatePct, _minRetAvgPct)

export successRateAllTimeStatsMin(series bool _sig, series float _sigCandleStopLoss, bool _long, float _minSuccRatePct, float _minRetAvgPct) =>
	[sigSuccRatePct, sigSuccCount, sigAllCount, retAvgPct] = successRateAllTimeStats(_sig, _sigCandleStopLoss, DEFAULT_SIG_CHECK_TIME, _long)
	bool succRateOk = sigSuccRateOk(sigSuccRatePct, retAvgPct, _minSuccRatePct, _minRetAvgPct)
	string succRateStr = formatSuccessRateStr(sigSuccRatePct, sigSuccCount, sigAllCount, retAvgPct, _minSuccRatePct, _minRetAvgPct)
	[sigSuccRatePct, succRateOk, succRateStr]

export successRateAllTimeStatsMin(series bool _sig, series float _sigCandleStopLoss, float _minSuccRatePct, float _minRetAvgPct) =>
	[sigSuccRatePct, sigSuccCount, sigAllCount, retAvgPct] = successRateAllTimeStats(_sig, _sigCandleStopLoss, DEFAULT_SIG_CHECK_TIME, true)
	bool succRateOk = sigSuccRateOk(sigSuccRatePct, retAvgPct, _minSuccRatePct, _minRetAvgPct)
	string succRateStr = formatSuccessRateStr(sigSuccRatePct, sigSuccCount, sigAllCount, retAvgPct, _minSuccRatePct, _minRetAvgPct)
	[sigSuccRatePct, succRateOk, succRateStr]

export successRateAllTimeStr(bool _longFormat, series bool _sig, series float _sigCandleStopLoss, int _checkTime, bool _long) =>
	[sigSuccRatePct, sigSuccCount, sigAllCount, retAvgPct] = successRateAllTimeStats(_sig, _sigCandleStopLoss, _checkTime, _long)
	formatSuccessRateStr(_longFormat, sigSuccRatePct, sigSuccCount, sigAllCount, retAvgPct)

export successRateAllTimeStr(bool _longFormat, series bool _sig, series float _sigCandleStopLoss, int _checkTime) =>
	[sigSuccRatePct, sigSuccCount, sigAllCount, retAvgPct] = successRateAllTimeStats(_sig, _sigCandleStopLoss, _checkTime, true)
	formatSuccessRateStr(_longFormat, sigSuccRatePct, sigSuccCount, sigAllCount, retAvgPct)

export successRateAllTimeStr(bool _longFormat, series bool _sig, series float _sigCandleStopLoss, bool _long) =>
	[sigSuccRatePct, sigSuccCount, sigAllCount, retAvgPct] = successRateAllTimeStats(_sig, _sigCandleStopLoss, _long)
	formatSuccessRateStr(_longFormat, sigSuccRatePct, sigSuccCount, sigAllCount, retAvgPct)

export successRateAllTimeStr(bool _longFormat, series bool _sig, series float _sigCandleStopLoss) =>
	[sigSuccRatePct, sigSuccCount, sigAllCount, retAvgPct] = successRateAllTimeStats(_sig, _sigCandleStopLoss)
	formatSuccessRateStr(_longFormat, sigSuccRatePct, sigSuccCount, sigAllCount, retAvgPct)

export successRateAllTimeStr(series bool _sig, series float _sigCandleStopLoss, int _checkTime, bool _long) =>
	[sigSuccRatePct, sigSuccCount, sigAllCount, retAvgPct] = successRateAllTimeStats(_sig, _sigCandleStopLoss, _checkTime, _long)
	formatSuccessRateStr(sigSuccRatePct, sigSuccCount, sigAllCount, retAvgPct)

export successRateAllTimeStr(series bool _sig, series float _sigCandleStopLoss, int _checkTime) =>
	[sigSuccRatePct, sigSuccCount, sigAllCount, retAvgPct] = successRateAllTimeStats(_sig, _sigCandleStopLoss, _checkTime, true)
	formatSuccessRateStr(sigSuccRatePct, sigSuccCount, sigAllCount, retAvgPct)

export successRateAllTimeStr(series bool _sig, series float _sigCandleStopLoss, bool _long) =>
	[sigSuccRatePct, sigSuccCount, sigAllCount, retAvgPct] = successRateAllTimeStats(_sig, _sigCandleStopLoss, _long)
	formatSuccessRateStr(sigSuccRatePct, sigSuccCount, sigAllCount, retAvgPct)

export successRateAllTimeStr(series bool _sig, series float _sigCandleStopLoss) =>
	[sigSuccRatePct, sigSuccCount, sigAllCount, retAvgPct] = successRateAllTimeStats(_sig, _sigCandleStopLoss)
	formatSuccessRateStr(sigSuccRatePct, sigSuccCount, sigAllCount, retAvgPct)

export successRateAllTime(series bool _sig, series float _sigCandleStopLoss, int _checkTime, bool _long) =>
	[sigSuccRatePct, sigSuccCount, sigAllCount, retAvgPct] = successRateAllTimeStats(_sig, _sigCandleStopLoss, _checkTime, _long)
	sigSuccRatePct

export successRateAllTime(series bool _sig, series float _sigCandleStopLoss, int _checkTime) =>
	[sigSuccRatePct, sigSuccCount, sigAllCount, retAvgPct] = successRateAllTimeStats(_sig, _sigCandleStopLoss, _checkTime, true)
	sigSuccRatePct

export successRateAllTime(series bool _sig, series float _sigCandleStopLoss, bool _long) =>
	[sigSuccRatePct, sigSuccCount, sigAllCount, retAvgPct] = successRateAllTimeStats(_sig, _sigCandleStopLoss, DEFAULT_SIG_CHECK_TIME, _long)
	sigSuccRatePct

export successRateAllTime(series bool _sig, series float _sigCandleStopLoss) =>
	[sigSuccRatePct, sigSuccCount, sigAllCount, retAvgPct] = successRateAllTimeStats(_sig, _sigCandleStopLoss, DEFAULT_SIG_CHECK_TIME, true)
	sigSuccRatePct

